### ISSUE TITLE
Many Images

### ISSUE THREAD

**Issue by ddrhost** [engintron/engintron#1010]
I have a client that owns a site with lots of images and they are not fully loaded with Nginx. How to solve?

**Comment by fevangelou** [comment]
Not fully loaded? Can you be a little more specific please?

**Comment by ddrhost** [comment]
See: http://rmlitoralimoveis.com.br

**Comment by fevangelou** [comment]
The URLs are like this: https://rmlitoralimoveis.com.br/thumb/cd625d04b436dc1906ec8fccc558efba/336/200/crop/

This indicates that a PHP script is used to resize the images.

If you call a broken image in a separate tab after a while, it loads. Which means it's an Apache or PHP availability issue. Nginx cannot load this URL into its cache because it does not have an image file extension.

**Comment by ddrhost** [comment]
It is not a PHP problem, because this does not occur when removing the engintron.

**Comment by fevangelou** [comment]
I doubt so.

**Comment by ddrhost** [comment]
I've removed Engintron and the site is now loading normally and without problems.

**Comment by fevangelou** [comment]
Yes, I can see that you removed Engintron. Now the site doesn't load at all... 😄
