### ISSUE TITLE
502 proxy error (Node.js app)

### ISSUE THREAD

**Issue by nadermedhet148** [engintron/engintron#1017]
I am trying to host multiple node.js app on my server.I am trying to configure upstream http 2 but when i try to access the domain i keep getting this error " Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /ar/."

anyone know why this happened?

**Comment by fevangelou** [comment]
What are your custom rules for this?

Anything like this perhaps?
```
if ($host ~ "mynodeapp.com") {
    set $PROXY_SCHEME "http";
    set $PROXY_TO_PORT 3000;
}
```

**Comment by nadermedhet148** [comment]
> if ($host ~ "mynodeapp.com") {
>     set $PROXY_SCHEME "http";
>     set $PROXY_TO_PORT 3000;
> }

I have add the following in my custom rules as the proxy for subdmain
if ($host ~ "beta.easyschools.org") {
    set $PROXY_SCHEME "http";
    set $PROXY_TO_PORT 9667;
}


but oit returning white page with weird dots
����������������������

**Comment by fevangelou** [comment]
If you call the app using http://domain.tld:9667, does it work?

**Comment by nadermedhet148** [comment]
> If you call the app using http://domain.tld:9667, does it work?

yes

**Comment by fevangelou** [comment]
Can you provide an actual URL to test?

**Comment by nadermedhet148** [comment]
> Can you provide an actual URL to test?

https://beta.easyschools.org

**Comment by fevangelou** [comment]
Make sure the port 9667 is not closed in your firewall (or open it for any internal requests - more on that here: https://engintron.com/docs/#/pages/Restrict-access-to-ports-8080-&-8443-used-by-Apache-only-for-Nginx) and also make sure there is no internal HTTP to HTTPS redirect in your app. It could screw things up.

**Comment by nadermedhet148** [comment]
> Make sure the port 9667 is not closed in your firewall (or open it for any internal requests - more on that here: https://engintron.com/docs/#/pages/Restrict-access-to-ports-8080-&-8443-used-by-Apache-only-for-Nginx) and also make sure there is no internal HTTP to HTTPS redirect in your app. It could screw things up.
I have opened the port in my csf configruation. however i totally diasbled it to make sure that's it is not problem and it's still not working. could you access it form your side?
moreover how could i enable https by default to all my app?

**Comment by fevangelou** [comment]
Port 9667 seems to be completely block, perhaps by your hosting provider. Doesn't respond to curl commands at all.

For the other URLs:
```
$ curl -I "http://beta.easyschools.org"
curl: (8) Weird server reply

$ curl -I "https://beta.easyschools.org"
HTTP/2 000 
server: nginx
date: Mon, 25 Feb 2019 16:53:24 GMT
x-xss-protection: 1; mode=block
x-content-type-options: nosniff

$ curl -I "http://beta.easyschools.org:9667"
(hangs)
```

**Comment by nadermedhet148** [comment]
> Port 9667 seems to be completely block, perhaps by your hosting provider. Doesn't respond to curl commands at all.
> 
> Curl results for all the URLs:
> 
> ```
> $ curl -I "http://beta.easyschools.org"
> curl: (8) Weird server reply
> 
> $ curl -I "https://beta.easyschools.org"
> HTTP/2 000 
> server: nginx
> date: Mon, 25 Feb 2019 16:53:24 GMT
> x-xss-protection: 1; mode=block
> x-content-type-options: nosniff
> 
> $ curl -I "http://beta.easyschools.org:9667"
> curl: (7) Failed to connect to beta.easyschools.org port 9667: Operation timed out
> ```

I have access to the who server vps and WHM. where can i open this port other than CSF that i opened it?

**Comment by fevangelou** [comment]
It could be /etc/hosts.deny blocking all ports but a few. It could be your provider. Sort it with them first.

**Comment by nadermedhet148** [comment]
> It could be /etc/hosts.deny blocking all ports but a few. It could be your provider. Sort it with them first.

I couldn't find the file you are referring to. however i just checked the curl command you were trying but it seems you were testing wrong port pleast try this

curl -I "http://beta.easyschools.org:9677"

**Comment by fevangelou** [comment]
```
$ curl -I "http://beta.easyschools.org:9677"
curl: (8) Weird server reply
```

Forces redirect to "https" in the browser which points to an internal loop because you proxy HTTPS to HTTP. Fix that.

**Comment by Easyschools** [comment]
@fevangelou 
It was an issue with the certificate location in the express file. Finally, we can access it back again through " https://system.easyschools.org:6555/" . while when you try to remove the port it keeps getting 502 bad gateway. how can we remove the port from the url ??

Although if you try curl -I "https://system.easyschools.org:6555/" -k it will get HTTP 1.1 as it's supposed to respond with Http2 as the express app configured for http2.

**Comment by fevangelou** [comment]
I now get a 502 error which means the proxying is not setup correctly. The fact that you see HTTP/1.1 when you call the Node app directly is because it responds in that protocol. If you're on any port other than 800 or 443, then you're not being served by Nginx.

**Comment by Easyschools** [comment]
@fevangelou I understand the situation of HTTP/1.1 . what i need now i want to remove the port so users can access the domain without seeing the report. I successfully added the port in the custom rules as you mentioned above and it's only working  like that. Please tell me how to remove the port although that i have about 10 different domains hosted on the same server and using Engintron.

**Comment by kmorton1988** [comment]
Honestly don’t think this issue is directly related to engintron

**Comment by fevangelou** [comment]
@Easyschools If you access the domain WITHOUT a port and then on subsequent page loads the port is added back in to the URLs, then it's clearly an app issue. The point of proxying is that you can mask port and URLs.

However I don't see https://system.easyschools.org/ properly pointing anywhere. I just get a 502 error. This means Nginx cannot reach the backend app (the Node app in this case). The site also does not respond to any of the ports you mentioned above...

**Comment by Easyschools** [comment]
@fevangelou @kmorton1988 
I think the situation with engintron not supporting SPDY because the app works totally fine if i am just calling HTTP 1.1 and not needing to add the port. However if used spdy for the http response i have to scenrories happens:

1- I can access the app only through the port "https://system.easyschools.org:6555" but when i try to remove the port I receive this error
`Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /index.php.

Reason: Error reading from remote server

Additionally, a 502 Bad Gateway error was encountered while trying to use an ErrorDocument to handle the request.`

2- When I added the rule you asked me at the beginning of the issue in nginx custom rules.
 I still can access the app through the port but when i remove I just recieved the error you sees which
`502 Bad Gateway
nginx`

and this are the error logs in nginx for both sitatuion 

[error] 28788#28788: *35 upstream prematurely closed connection while reading response header from upstream, client: 197.50.29.255, server: system.easyschools.org, request: "GET /favicon.ico HTTP/2.0", upstream: "http://173.249.20.190:6555/favicon.ico", host: "system.easyschools.org", referrer: "https://system.easyschools.org/"
2

**Comment by fevangelou** [comment]
First off, SPDY is deprecated now and succeeded by HTTP/2. Secondly, Nginx fully supports HTTP/2. If you look at the log entry, the GET request for the "favicon" is HTTP/2.0.

It's really not rocket science. You create a proxy rule for a certain domain/subdomain that bypasses the default backend proxy port of Apache (8080) to whatever you like (6555 in your case). If the backend app does not support HTTPS, you can even change the protocol to just HTTP. Nginx will make sure that both HTTP and HTTPS external calls will always proxy/route internally to HTTP.

People have used this technique to painlessly host Node apps in cPanel for some time now. I even put up a Ghost blog demo for a while just to showcase it was possible. This was very difficult to achieve in the past.

However, given that your Node app is a black box for me, I can't possibly know what the heck is going on or how it's built.

Since the Node app works in HTTPS (as I currently see), if you tried the following inside "custom_rules":
```
if ($host ~ "system.easyschools.org") {
    set $PROXY_TO_PORT 6555;
}
```
...then reloaded/restarted Nginx and things don't work still, then you need to check the logs in Nginx (the error log to be exact) as to why the proxying fails and returns a 502 error.

**Comment by Easyschools** [comment]
@fevangelou 
I have mentioned above that i already added this code in the "custom rules" and that's why it shows 502 error that i already seeing now if you tried to access the app and when I checked the logs It shows
[error] 28788#28788: *35 upstream prematurely closed connection while reading response header from upstream, client: 197.50.29.255, server: system.easyschools.org, request: "GET /favicon.ico HTTP/2.0",`

However I don't think it's an issue with the app because it's already working fine if i added the port to the url and HTTP2 works fine. anyway here is my node app i uploaded as attachment 

[text.txt](https://github.com/engintron/engintron/files/2923604/text.txt)

**Comment by Easyschools** [comment]
@fevangelou It's really funny that i looked again in your last comment and saw that you didn't asked me to    set $PROXY_SCHEME "http" in "custom_rules" so i thought about removing it and it actually worked :D without the port. but still there is an issue that it does't server push my files. however if I add the port i can see in the dev tools the files are server pushed.

**Comment by fevangelou** [comment]
Might I suggest you do this?
a) Disable HTTPS altogether in your Node app
b) Create a blank index.html file in your site's public_html directory and have cPanel's AutoSSL issue a certificate for it. Nginx will use this certificate to serve your site via HTTPS.
c) Go back to your custom rules and add both "http" as proxying protocol and the Node app's port.

This way, Nginx will forward both HTTP and HTTPS traffic to your Node app.

Try it and let me know.

**Comment by fevangelou** [comment]
Closing as there is no response from the OP.

**Comment by Easyschools** [comment]
I couldn't understand what you are asking me to do

**Comment by fevangelou** [comment]
The steps are specific. The point is to have cPanel issue a certificate for Apache for your domain (hence the index.html page to add). Then Nginx can pick up the certificate and use it to server HTTPS connections.

Finally, you switch your Node app entirely to HTTP and adjust your custom rules to proxy traffic to the Node app port and use "http" as proxying protocol.

**Comment by Easyschools** [comment]
I have tried what were you asking. still not working I guess because http2 and server push must have ssl certificate so still we didn't do anything. is there a file in engintron to specify the app server key. Also i tried installing ceritficate from openssl and still same issue
Does engintron even supports server push?

**Comment by fevangelou** [comment]
You can't have a custom certificate to be used with Nginx. If you're getting there, you might as well just not use cPanel at all.

https://www.nginx.com/blog/nginx-1-13-9-http2-server-push/

**Comment by nadermedhet148** [comment]
still it is not the issue with the certficate as i tried and download another [repository](https://medium.com/@sibu.it13/an-example-of-server-push-with-http-2-in-node-js-22757256f0b3) and still same issue. only can access it through the port but without the port i got error failed upstream event.

I have another node applications that is on the same server and don't have any issue. only when i try to use http2 in node and server push. 

also i got this error once when i was trying this repository but i didn't saw it again. it might help you identify the issue

`Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_REFUSED_STREAM`

**Comment by Easyschools** [comment]
@fevangelou did you find any solution for this issue? We tried to make a docker inside the server and serve our app and still the same situation!!

**Comment by fevangelou** [comment]
Nope, sorry.
