### ISSUE TITLE
Engintron+EA4+FCGId+Memcached+APCu

### ISSUE THREAD

**Issue by gitfan2** [engintron/engintron#1025]
Hi,

Thanks for a great cPanel plugin, plus the helpful pointers and tweaks in your wiki to further enhance the overall (server) performance. :)

*  Engintron+cPanel78+EA4+FCGId(for all PHP versions)+Memcached+APCu
Thinking of this combination for a new server. Is that perfectly plausible? Will FCGId play ball properly with Engintron (and vice versa)? Or, will FCGId no longer have any function with Engintron on the frontend?

*  How to uninstall Memcached, if needed, after installing it as directed in your wiki?

*  APCu: 128M cache pool ; Memcached: 256M cache pool
Are these cache pool sizes per server or per domain? Reason I am asking is, I had initially thought the PHP-OPCache size stated in the php.ini was per server, and it took me a while to realise that it is per each domain. 

Thanks.

**Comment by fevangelou** [comment]
Replying...

- Use PHP-FPM instead of FastCGI, you'll control performance better. The way PHP is run on the server only matters to overall performance, it has nothing to do with Engintron/Nginx because the latter is used in proxy mode.
- `yum remove memcached`. I highly recommend you use Memcached over APCu in any case.
- Use 512M for Memcached, 128M is more than enough for APCu for any site that can't utilize Memcached. For OPcache use:
```
opcache.memory_consumption=256
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=100000
```
256 is in MBs.

For PHP-FPM use this formula:
- pm = ondemand # (default in cPanel)
- pm.max_children = X # Where X is half your CPU count
- pm.process_idle_timeout = 1s
- pm.max_requests = Y # Use a value like 2000, 3000 or 4000 - if your CPUs are few, use a higher number here so PHP use the same thread/process to parse more requests

And let's get one thing straight. All the tutorials in regards to PHP-FPM around the web are so wrong (e.g. https://www.inmotionhosting.com/support/website/php-configuration/php-fpm-settings-for-better-optimization or https://www.kinamo.be/en/support/faq/determining-the-correct-number-of-child-processes-for-php-fpm-on-nginx). Just consider how restricted the default PHP-FPM values are in cPanel by default.

At some point in the coming weeks, I plan on upgrading the performance optimization guides to include more up-to-date info.

**Comment by gitfan2** [comment]
Hi Fotis,

Thanks for your helpful advice. A couple of final queries :)

*  Your recommended cache memory figures above for Memcached and APCu, are they per site or shared by all the sites on the server using those caches?

*  In your Engintron_EA4_2018_v3 recommended profile, there are a few caching modules and a couple of compression modules selected for Apache 2.4. Can all of these modules still be of use while Engintron/Nginx is in action?
https://github.com/engintron/engintron/blob/master/cpanel/EasyApache_Profiles/EA4/Engintron_EA4_2018_v3.json:
mod_cache_disk
mod_cache
mod_cache_socache
mod_file_cache
mod_brotli
mod_deflate

*  If https traffic is offloaded to Nginx, as described in one of the user contributed guides in your wiki, is there any need to install the Apache http2 module via EA4? Do you advise that the http2 module should be installed regardless of?  
https://engintron.com/docs/#/pages/Offload-HTTPS-traffic-to-Nginx-only

Thanks.

**Comment by fevangelou** [comment]
Replying...
1. Shared for Memcached, APCu is per PHP-FPM pool (so keep it low).
2. They require additional configuration. I merely include them should anyone wish to use them.
3. Proxying is done via HTTP/1.1 by Nginx for the backend, so I don't see any benefits there. But again, there's no harm in using it. E.g. you may have to switch Nginx off for a while for some reason, so if you use HTTP/2 in Apache, you'll simply get the best out of Apache for that short time.
