### ISSUE TITLE
NGINX Session Stealing 

### ISSUE THREAD

**Issue by gareth-johnstone** [engintron/engintron#1031]
This might be more an issue with NGINX itself rather than Engintron, but i'm currently unsure ...

We are using an application called BookStack app ... and this appears to be the only application with this issue..

Anyways, the issue is this, we have our servers in France - and our office is located in Scotland, if 2 of us (in the same office and same external IP) connect to our application in France, we noticed that we suddenly start "stealing" each others sessions (so i'm logged in as me but after a refresh end up logged in as them)

If i disable NGINX the application behaves as intended.

What would be the recommended way to rectify this?

**Comment by dylanhansch** [comment]
This is likely either due to [micro caching](https://engintron.com/docs/#/pages/About-Engintrons-micro-caching-features), cookies being cached, or both. I suggest disabling dynamic page micro caching since you're running a site with sessions. You'll want to make sure you add your application's cookies to the list of cookies not to cache in the config too.

**Comment by gareth-johnstone** [comment]
@dylanhansch thanks - thats solved it :)
