### ISSUE TITLE
Microcaching

### ISSUE THREAD

**Issue by igorhrq** [engintron/engintron#1038]
Hello,

In pass with engintron was have some issues with microcaching sessions, another clients was can see other sessions cause the microcaching, this issue was fixed ?

Best Regards!

**Comment by jimcouts** [comment]
@igorhrq - Wondering, would this have been a laravel/code ignitor app you had issues with on this being crossed up? The reason why I ask is that on a laravel app of ours, I found to be showing one other's secure logged in session until I turned this off and they've never had this issue.

**Comment by hubertus2017** [comment]
hello, we installed eningtron and suddenly some customers saw in their order other orders of other customers (Magento 2). After we disabled micro caching completely, this seems to be solved.
Is this a standard behaviour?

**Comment by vowave** [comment]
Hello,
This problem is really annoying, Im using laravel and i tried even to turn the set $CACHE_BYPASS_FOR_DYNAMIC 1; solution but still my users sessions are getting conflicted and they get logged in to each others account.
dear @fevangelou please help me with this.
everything was working fine but after update this happened to me.

**Comment by fevangelou** [comment]
Add a custom rule to disable dynamic caching for affected domains. If you still get issues after you do that, either you implemented wrong rules or the issue lies in the app.
