### ISSUE TITLE
cPanel pricing changes - discussion

### ISSUE THREAD

**Issue by newmaza** [engintron/engintron#1078]
Hello,

Maybe asking here is not a good option but lot of companies planing to move away from cpanel, as well us, but i like Engintron and i hope there is any development for other control panel too like DirectAdmin?

**Comment by fevangelou** [comment]
Not really, sorry.

**Comment by fevangelou** [comment]
I actually thought the new pricing you mentioned would be something trivial... It isn't, at least for small agencies that use cPanel to manage dozens to hundreds of accounts on cheap EU hosting. So I can see a lot of people moving away from cPanel as it won't make sense for them to keep using it due to the increased pricing, as in many cases, the license cost will be higher than the actual server cost.

For reference, here are some links on the new pricing changes:
https://cpanel.net/pricing/
https://blog.cpanel.com/announcing-account-based-pricing/ (official announcement)
https://www.theregister.co.uk/2019/06/28/cpanel_price_hikes/
https://www.lowendtalk.com/discussion/158547/new-cpanel-licensing-and-pricing-structure-thoughts (top discussion on LowEndTalk)
http://www.webhostingtalk.com/showthread.php?t=1770316
https://forums.cpanel.net/threads/announcing-account-based-pricing.656071/

Since the fund that owns cPanel (for about a year already) also owns Plesk (along with WHMCS & SolusVM), it looks like some users are sceptical on moving to Plesk, fearing a similar pricing model change.

This leaves a few "viable" alternatives, with DirectAdmin (DA) being the most serious contender.

Seeing that DA has a plugin architecture, I can exclude packaging Engintron for it as well in the near future.

But let's see how things progress first and how developers/agencies brace the new cPanel pricing changes.

**Comment by newmaza** [comment]
For us it is 200% extra, and TBH i think it is monopoly, anyway as Engintron lover i will hope too see you soon on DA :)

**Comment by fevangelou** [comment]
I'll see how things progress to be honest. I was already eyeing Plesk as the next platform to support (their Nginx implementation could be improved), so DA is not that far away given it also uses PHP for their plugin system (like Plesk does).

**Comment by zstergios** [comment]
Many clients request me to integrate my products with http://centos-webpanel.com/

@fevangelou do you consider to intergrate it with centos-webpanel?

**Comment by fevangelou** [comment]
@zstergios I've used it in the past, but it's not cPanel-solid for sure. Not to mention updating packages required recompiling as in the old EasyApache3 days... Finally, the project had some serious security issues in the past as far as I know. Plus last version was shipped in 2018 for CentOS 7: http://centos-webpanel.com/changelog-cwp7

If you're looking for alternatives, consider Plesk or DirectAdmin. Anything will probably be a waste of your time and your client's patience.

**Comment by informdev** [comment]
I know this is marked as closed but I wanted to chime in, still. I've tried CWP and it's just not a viable option as far as I can tell. It's not that user-friendly. I'm no novice when it comes to software/panels things of that nature and I even have trouble navigating through it.

Also their cPanel import option is still buggy (at least in my case).

Plesk... meh. I may try it again since I haven't in about decade though.

I did buy a DirectAdmin license and moved a bunch of my non-money-sites over to it. And the entire time all I could think was "man I wish Enginton would port to this" Lol. It's easy enough, but still not the most user-friendly interface.

Please keep us updated on whatever direction you go. Also, you and I had discussed at one point a premium option for Engintron, given what's happened with cPanel I bet a lot of your users would be more open to that than ever.

**Comment by fevangelou** [comment]
Once the dust settles down, I will surely evaluate Plesk & DirectAdmin. Plesk has a PHP API so it's relatively easy & I've used it in the past. I think DirectAdmin has a PHP API as well, but I've never used it so it requires actual testing and surely more time. In any case, Engintron is an active project, so it will adapt according to user needs and market fit of course.

**Comment by newmaza** [comment]
Thank you @fevangelou tbh Plesk & cpanel backed by same VC so it is more became market monopoly in terms of price :( I move several servers to DA for my clients and my self, and DA more friendly for nginx as compare to cpanel or plesk and I hope you consider this too

**Comment by zstergios** [comment]
I think DA it's better option right now to start.

**Comment by fevangelou** [comment]
Thanks for your comments folks :)
