### ISSUE TITLE
Does this work with Stackpath?

### ISSUE THREAD

**Issue by lvdlrs** [engintron/engintron#1097]
I manage to work it and configure the engintron in our website with luck, which at first try I have 502 bad gateway error but I manage to work with it with the help of the issues already been raise here and solve, I just have few questions.

1. Is this work with stackpath CDN? because we use stackpath full site integration
2. We host our sites in VPS bluehost, what will I use the Dedicated IP or the IP Address of stackpath?for clarification only.
3. How will I know that it affects my site performance? We try to use this in order to improve site speed and performance.

thanks for the answers and Clarification more blessing to the contributor of this very useful plugin

**Comment by fevangelou** [comment]
Replying...

1. Since Stackpath works like CloudFlare if I recall correctly, then follow the guide to setup Engintron as you would with CloudFlare. You'll basically just enforce your VPS's IP in Engintron's "custom rules". Comments are in place in that file to help you out.

2. The VPS's dedicated IP of course.

3. First use "curl" via terminal to check one of your site's headers (use something like `curl -I https://domain.tld`). If you host WordPress sites exclusively, you can bump the dynamic cache TTL in Engintron's "proxy_params_dynamic" from 1s to say 3m (m is for minutes). 1s is a safe micro-cache TTL for all types of sites & CMSs. After that, learn how to run an ApacheBench (AB) or Siege test on your server to test how it responds.

**Comment by lvdlrs** [comment]
Thanks After running the curl -I https://domain.tld

i have this results so it means nginx working properly?


HTTP/1.1 301 Moved Permanently
Date: Mon, 12 Aug 2019 20:33:52 GMT
Accept-Ranges: bytes
Content-Type: text/html; charset=iso-8859-1
Server: nginx
Location: https://blueskytestingground.com/bemaxsite/
Cache-Control: max-age=2592000
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Nginx-Cache-Status: MISS
X-Server-Powered-By: Engintron
Access-Control-Allow-Origin: *
X-HW: 1565642032.cds083.da2.hn,1565642032.cds114.da2.sc,1565642032.cds114.da2.p
Connection: keep-alive
Content-Length: 251

**Comment by fevangelou** [comment]
Correct.
