### ISSUE TITLE
Magento 2 - form_key gets cached| why not varnish?

### ISSUE THREAD

**Issue by an4rei** [engintron/engintron#1105]
Hello!
I've read about 10 issues here concerning Varnish.
Well, today I've tried Engitron for nginx's microcaching feature.
I've changed 
`set $EXPIRES_FOR_DYNAMIC 30m;`
`proxy_cache_valid              200 30m;`

I did this because I have an average of 8 users max online at the same time therefore, 1s caching would definitely not help me. 

All good until I found out that the cart products of  'user 1' get replicated in the cart products of 'user 2' and so on.
I've went deeper and found out that the 'form_key' is the same for each user thanks to the page caching.

Therefore what would the solution be for Magento 2 if not Varnish?

Here is the VCL that Magento 2 exported for me:
```
vcl 4.0;

import std;
# The minimal Varnish version is 4.0
# For SSL offloading, pass the following header in your proxy server or load balancer: 'X-Forwarded-Proto: https'

backend default {
    .host = "127.0.0.1";
    .port = "8080";
    .first_byte_timeout = 600s;
    .probe = {
        .url = "/pub/health_check.php";
        .timeout = 2s;
        .interval = 5s;
        .window = 10;
        .threshold = 5;
   }
}

acl purge {
    "127.0.0.1";
}

sub vcl_recv {
    if (req.method == "PURGE") {
        if (client.ip !~ purge) {
            return (synth(405, "Method not allowed"));
        }
        # To use the X-Pool header for purging varnish during automated deployments, make sure the X-Pool header
        # has been added to the response in your backend server config. This is used, for example, by the
        # capistrano-magento2 gem for purging old content from varnish during it's deploy routine.
        if (!req.http.X-Magento-Tags-Pattern && !req.http.X-Pool) {
            return (synth(400, "X-Magento-Tags-Pattern or X-Pool header required"));
        }
        if (req.http.X-Magento-Tags-Pattern) {
          ban("obj.http.X-Magento-Tags ~ " + req.http.X-Magento-Tags-Pattern);
        }
        if (req.http.X-Pool) {
          ban("obj.http.X-Pool ~ " + req.http.X-Pool);
        }
        return (synth(200, "Purged"));
    }

    if (req.method != "GET" &&
        req.method != "HEAD" &&
        req.method != "PUT" &&
        req.method != "POST" &&
        req.method != "TRACE" &&
        req.method != "OPTIONS" &&
        req.method != "DELETE") {
          /* Non-RFC2616 or CONNECT which is weird. */
          return (pipe);
    }

    # We only deal with GET and HEAD by default
    if (req.method != "GET" && req.method != "HEAD") {
        return (pass);
    }

    # Bypass shopping cart, checkout and search requests
    if (req.url ~ "/checkout" || req.url ~ "/catalogsearch") {
        return (pass);
    }

    # Bypass health check requests
    if (req.url ~ "/pub/health_check.php") {
        return (pass);
    }

    # Set initial grace period usage status
    set req.http.grace = "none";

    # normalize url in case of leading HTTP scheme and domain
    set req.url = regsub(req.url, "^http[s]?://", "");

    # collect all cookies
    std.collect(req.http.Cookie);

    # Compression filter. See https://www.varnish-cache.org/trac/wiki/FAQ/Compression
    if (req.http.Accept-Encoding) {
        if (req.url ~ "\.(jpg|jpeg|png|gif|gz|tgz|bz2|tbz|mp3|ogg|swf|flv)$") {
            # No point in compressing these
            unset req.http.Accept-Encoding;
        } elsif (req.http.Accept-Encoding ~ "gzip") {
            set req.http.Accept-Encoding = "gzip";
        } elsif (req.http.Accept-Encoding ~ "deflate" && req.http.user-agent !~ "MSIE") {
            set req.http.Accept-Encoding = "deflate";
        } else {
            # unknown algorithm
            unset req.http.Accept-Encoding;
        }
    }

    # Remove all marketing get parameters to minimize the cache objects
    if (req.url ~ "(\?|&)(gclid|cx|ie|cof|siteurl|zanpid|origin|fbclid|mc_[a-z]+|utm_[a-z]+|_bta_[a-z]+)=") {
        set req.url = regsuball(req.url, "(gclid|cx|ie|cof|siteurl|zanpid|origin|fbclid|mc_[a-z]+|utm_[a-z]+|_bta_[a-z]+)=[-_A-z0-9+()%.]+&?", "");
        set req.url = regsub(req.url, "[?|&]+$", "");
    }

    # Static files caching
    if (req.url ~ "^/(pub/)?(media|static)/") {
        # Static files should not be cached by default
        return (pass);

        # But if you use a few locales and don't use CDN you can enable caching static files by commenting previous line (#return (pass);) and uncommenting next 3 lines
        #unset req.http.Https;
        #unset req.http.X-Forwarded-Proto;
        #unset req.http.Cookie;
    }

    return (hash);
}

sub vcl_hash {
    if (req.http.cookie ~ "X-Magento-Vary=") {
        hash_data(regsub(req.http.cookie, "^.*?X-Magento-Vary=([^;]+);*.*$", "\1"));
    }

    # For multi site configurations to not cache each other's content
    if (req.http.host) {
        hash_data(req.http.host);
    } else {
        hash_data(server.ip);
    }

    if (req.url ~ "/graphql") {
        call process_graphql_headers;
    }

    # To make sure http users don't see ssl warning
    if (req.http.X-Forwarded-Proto) {
        hash_data(req.http.X-Forwarded-Proto);
    }
    
}

sub process_graphql_headers {
    if (req.http.Store) {
        hash_data(req.http.Store);
    }
    if (req.http.Content-Currency) {
        hash_data(req.http.Content-Currency);
    }
}

sub vcl_backend_response {

    set beresp.grace = 3d;

    if (beresp.http.content-type ~ "text") {
        set beresp.do_esi = true;
    }

    if (bereq.url ~ "\.js$" || beresp.http.content-type ~ "text") {
        set beresp.do_gzip = true;
    }

    if (beresp.http.X-Magento-Debug) {
        set beresp.http.X-Magento-Cache-Control = beresp.http.Cache-Control;
    }

    # cache only successfully responses and 404s
    if (beresp.status != 200 && beresp.status != 404) {
        set beresp.ttl = 0s;
        set beresp.uncacheable = true;
        return (deliver);
    } elsif (beresp.http.Cache-Control ~ "private") {
        set beresp.uncacheable = true;
        set beresp.ttl = 86400s;
        return (deliver);
    }

    # validate if we need to cache it and prevent from setting cookie
    if (beresp.ttl > 0s && (bereq.method == "GET" || bereq.method == "HEAD")) {
        unset beresp.http.set-cookie;
    }

   # If page is not cacheable then bypass varnish for 2 minutes as Hit-For-Pass
   if (beresp.ttl <= 0s ||
       beresp.http.Surrogate-control ~ "no-store" ||
       (!beresp.http.Surrogate-Control &&
       beresp.http.Cache-Control ~ "no-cache|no-store") ||
       beresp.http.Vary == "*") {
       # Mark as Hit-For-Pass for the next 2 minutes
        set beresp.ttl = 120s;
        set beresp.uncacheable = true;
    }

    return (deliver);
}

sub vcl_deliver {
    if (resp.http.X-Magento-Debug) {
        if (resp.http.x-varnish ~ " ") {
            set resp.http.X-Magento-Cache-Debug = "HIT";
            set resp.http.Grace = req.http.grace;
        } else {
            set resp.http.X-Magento-Cache-Debug = "MISS";
        }
    } else {
        unset resp.http.Age;
    }

    # Not letting browser to cache non-static files.
    if (resp.http.Cache-Control !~ "private" && req.url !~ "^/(pub/)?(media|static)/") {
        set resp.http.Pragma = "no-cache";
        set resp.http.Expires = "-1";
        set resp.http.Cache-Control = "no-store, no-cache, must-revalidate, max-age=0";
    }

    unset resp.http.X-Magento-Debug;
    unset resp.http.X-Magento-Tags;
    unset resp.http.X-Powered-By;
    unset resp.http.Server;
    unset resp.http.X-Varnish;
    unset resp.http.Via;
    unset resp.http.Link;
}

sub vcl_hit {
    if (obj.ttl >= 0s) {
        # Hit within TTL period
        return (deliver);
    }
    if (std.healthy(req.backend_hint)) {
        if (obj.ttl + 300s > 0s) {
            # Hit after TTL expiration, but within grace period
            set req.http.grace = "normal (healthy server)";
            return (deliver);
        } else {
            # Hit after TTL and grace expiration
            return (fetch);
        }
    } else {
        # server is not healthy, retrieve from cache
        set req.http.grace = "unlimited (unhealthy server)";
        return (deliver);
    }
}
```

note: form_key cookie is also present on every page of the website so exclusion by cookie would end up with no caching at all.

**Comment by an4rei** [comment]
![image](https://user-images.githubusercontent.com/11984860/63446136-55548980-c442-11e9-9339-9bdfe7257921.png)

also did this for the 'checkout' link that was being executed when adding a product to cart or removing it.

**Comment by an4rei** [comment]
Could you possibly provide us the correct way to use Varnish with Engitron?

**Comment by fevangelou** [comment]
The cache time you set is not recommended if you don't have the proper exclusions in place first.

Additionally, any custom exclusions can easily be set in your custom rules file, so there's no reason to edit Engintron core files. Example:
```
if ($request_uri ~* "(/checkout|/catalogsearch)") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1;
}
```
I would also recommend you add the user login/logout URLs as well in the above example.

For the record, exclusions can be achieved in 3 ways primarily: HTTP header, cookie or URL path. You got the last one. If you could also check for a cookie set when a user performs a cart action ("X-Magento-Vary" perhaps?), you could easily add that cookie in your custom rules file and also enforce cache shutdown. E.g.:
```
if ($http_cookie ~* "(X-Magento-Vary)") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1;
}
```

**Comment by an4rei** [comment]
well basically I'd have to exclude all the product pages/category pages(where I have add to cart) button as I did the exclusions above and the behaviour was the same. 

Is Varnish configuration really that hard for engintron?

**Comment by fevangelou** [comment]
They are different things for sure. Also keep in mind that from the little I looked, there is no real benefit with Varnish's cache setup as it basically creates per users caches (which is pointless for caching)...

**Comment by an4rei** [comment]
> However, in Magento 2, it is not possible to cache
> dynamic content because every page load is unique to a user
> session. This explains why integrations with reverse proxies like
> Varnish tend to be complex; pages are typically separated into
> blocks of cacheable static data and dynamic data.
> Due to this limitation, Nginx microcaching cannot easily be used for
> all Magento 2 content. Typical Magento 2 page-load waterfalls often
> involves well over 100 requests for JavaScript and CSS files, which
> places heavy load onto the web server. Using the Nginx microcache
> to cache these static files removes load from the web server, freeing
> it to focus on dynamic requests. This method makes it possible to
> set the cache-lifetime for 30 seconds or more. 

Source: https://smhttp-nex.nexcesscdn.net/803313/static/vten/white-paper/Nexcess-Magento-Whitepaper-2018.pdf

Therefore the nginx microcaching feature can only be used for static files when it comes to magento 2 and if I'd want to use it for dynamic content as well, I'd probably have to modifiy magento2's source code. Does the configuration of varnish with engitron needs more than just port adjusting?

**Comment by fevangelou** [comment]
> > However, in Magento 2, it is not possible to cache
> > dynamic content because every page load is unique to a user
> > session. This explains why integrations with reverse proxies like
> > Varnish tend to be complex; pages are typically separated into
> > blocks of cacheable static data and dynamic data.
> > Due to this limitation, Nginx microcaching cannot easily be used for
> > all Magento 2 content. Typical Magento 2 page-load waterfalls often
> > involves well over 100 requests for JavaScript and CSS files, which
> > places heavy load onto the web server. Using the Nginx microcache
> > to cache these static files removes load from the web server, freeing
> > it to focus on dynamic requests. This method makes it possible to
> > set the cache-lifetime for 30 seconds or more.
> 
> Source: https://smhttp-nex.nexcesscdn.net/803313/static/vten/white-paper/Nexcess-Magento-Whitepaper-2018.pdf

In other words, prefer the standard 1 sec micro-cache that comes with Engintron by default. Static files are already cached in Nginx for 1 min (unless they are passed to some PHP script for output).

Finally, it's beyond the scope of the support I provide here to map your Varnish configuration to Nginx. Furthermore, you're not reading what I write.

> there is no real benefit with Varnish's cache setup as it basically creates per user caches
(which is inline to the whitepaper you mention)

**Comment by an4rei** [comment]
Thanks for the info.
My main question which I haven't actually pointed was how could I make the proper exclusions in order for nginx dynamic microcaching feature to work flawless with Magento 2.

I noticed that it caches even the same PHPSESSID(incognito and normal had same id).
From what you told me above is to do something like:

```
if ($http_cookie ~* "(X-Magento-Vary|PHPSESSID)") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1;
}
```
and yes, this would fix the issue(magic carts that share products between users) by getting a BYPASS on each page because each guest/user session has the same cookie. Is this the way that nginx should respond to this exclusion? How can we make it so it doesn't cache the original user's PHPSESSID that loaded the page.

Thank you!

**Comment by fevangelou** [comment]
The answer is simple. You can't cache Magento the way you cache other CMSs like WordPress. Magento, like Joomla, phpBB and others uses sessions even for guest users. This makes it impossible to cache these CMSs "out of the box" and requires workarounds (Joomla is probably the easiest to fix for the record).

If Magento sets a session for each visitor, what's the point of excluding the PHPSESSID cookie? Everyone will have it, so you'd be effectively killing your cache. That's not how you do proper caching. You can of course enforce Nginx (or Varnish) to ignore that cookie and cache the crap out of everything. But in order to make things work correctly, you need to keep some exclusions (e.g. the user login page I mentioned, or the cart), so that an identifier is set by the browser (cookie or HTTP header) that can then INSTRUCT the server upon subsequent requests to NOT CACHE anything. This is caching 101 really.

What Magento does with Varnish is probably stupid. They should trigger a cookie or HTTP header when a user performs a cart action or when they login. That's the only way you can safely use aggressive caching for pages that can be cached (e.g. the homepage, product pages, categories etc.) while at the same time be able to shut down caching when a user starts interacting with your site.

Did around the Magento community for a plugin to do just that (set a cookie on the browser when a user performs a cart action). Then create certain entry points (login page), which you'll add to the path exceptions. Whenever such a path is loaded or the cookie I mentioned before is detected, Nginx can shut off any caching. Is there any point not to cache product pages for example?

**Comment by hubertus2017** [comment]
Hello,
we also have a magento 2 shop and faced the same issues with customer "shared carts" after installation of eningtron.
We set with help of Fortis (thanks!) cache_bypass for different SITE_URI as domain/checkout and domain/customer or domain/contact and since then it was working.

However the only reason we installed eningtron is because of its capability to make varnish "useable" in conjunction with Http2 and Apache in backend as SSL Terminal . Before we had xvarnish, which did not work with http2 (and we had to deinstall).

I jumped in this forum to ask the question, if anybody could briefly explain how the settings are in eningtron with Varnish. Now i read "Varnish does not work (well, at all ???) with magento 2". 
I am totally  surprised and unsettled because we had a well working and very fast solution with xvarnish. After de-installation, everything is quite slow and bad google speed again. After installation of eningtron nothing felt improved. But i also did not really expect, because we planned to install varnish, so all ok.
I don't know if i did not get the point with varnish / eningtron/ magento now?

Has anybody varnish installed with Eningtron as (simply and only) SSL Terminal in a working solution and can post the settings in eningtron for this? This would be nice:-)

hub

**Comment by an4rei** [comment]
I successfully installed engintron(using nginx micro caching only for the static files) and varnish.
Hit me up at andreibacila35@yahoo.com.

It's more of an trial and error process.

**Comment by fevangelou** [comment]
It's not a trial & error process. If you understand frontend caching, it's not rocket science to have a Magento site (as well as any other site with user-generated content or frontend user interactions). The key here is to have specific entry points for users. Think of Amazon's login. It's a specific path/URL. Once you're logged in (same with Magento) you can set a cookie that Engintron will detect and shut down any caching for the logged in user. For everyone else, you can serve fully cached pages via Nginx.

@hubertus2017 If you look closely at the Magento/Varnish configuration, you'll notice that what they do is essentially create a cache PER USER. This is really stupid by design for such an app. WordPress for example handles that part a ton times better. Is it THAT hard for the Magento folks to copy that process? It's not like Magento is featherweight and doesn't need any caching...

**Comment by an4rei** [comment]
@fevangelou You are totally wrong about Varnish. It does not create cache PER USER. I can bet that you never used varnish yourself. Dont hate talk about something you didn't use.

Nginx has its benefits but when it comes to Magento, Varnish or Litespeed with LiteMage goes beyond  what nginx microcaching can do.

**Comment by fevangelou** [comment]
@an4rei I use Varnish extensively beyond cPanel - hell I even wrote https://gist.github.com/fevangelou/84d2ce05896cab5f730a (google "joomla varnish" to see what comes up first).

But the fact remains: when it comes to cPanel, Nginx is the best overall caching solution at no extra cost. If it weren't, I wouldn't make Engintron in the first place. As for microcaching, this is just a concept. Nginx can do caching like Varnish just fine.

**Comment by an4rei** [comment]
shit, I'm out; litespeed does it for me.
nginx micro-caching really is awesome but it was not my solution for magento2.
thanks!
