### ISSUE TITLE
HTTPD fails to start after installing latest version of engintron 2020-03-30. Removing engintron solves the issue.

### ISSUE THREAD

**Issue by dsfsvsdva** [engintron/engintron#1171]
In the latest version of engintron (today's date of 2020-03-30) on CentOS 7.7 x64 (7.7.1908 (Core)), using latest version of cpanel v86.0.16:

**httpd fails to start, restart, stop, or anything. In SSH it simply hangs and fails. Syntax is OK. In cpanel, apache restart also hangs indefinitely.**

After troubleshooting I found that nginx is using the port and will not allow httpd to restart or start.

It works if I simply install engintron and leave it alone, but if httpd needs to be restarted, which it will for many reasons, there is no way to restart it except to uninstall and/or reinstall engintron.

This is NOT a problem with my system. Uninstalling engintron solves the issue immediately. Reinstalling engintron once again gives same issue.

Websites are all UP and reachable. For now anyway. It will become a problem when I need to restart httpd.

This is a critical issue that needs to be fixed.

```
# netstat -ltnp | grep :80
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      13898/httpd
tcp6       0      0 :::80                   :::*                    LISTEN      14099/nginx: master
tcp6       0      0 :::8080                 :::*                    LISTEN      13898/httpd
```

```
# sudo httpd -t
Syntax OK
```

```
# service httpd status
● httpd.service - Apache web server managed by cPanel EasyApache
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2020-03-30 13:31:30 PDT; 4min 11s ago
  Process: 13443 ExecStop=/usr/local/cpanel/scripts/restartsrv_httpd stop --no-verbose (code=exited, status=0/SUCCESS)
  Process: 15501 ExecStart=/usr/local/cpanel/scripts/restartsrv_httpd --no-verbose (code=exited, status=1/FAILURE)
 Main PID: 13057 (code=killed, signal=KILL)

Mar 30 13:31:30 server.ser systemd[1]: Starting Apache web server managed by cPanel EasyApache...
Mar 30 13:31:30 server.ser restartsrv_httpd[15501]: (98)Address already in use: AH00072: make_sock: could not bind to address [::]:8080
Mar 30 13:31:30 server.ser restartsrv_httpd[15501]: (98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:8080
Mar 30 13:31:30 server.ser restartsrv_httpd[15501]: no listening sockets available, shutting down
Mar 30 13:31:30 server.ser restartsrv_httpd[15501]: AH00015: Unable to open logs
Mar 30 13:31:30 server.ser systemd[1]: httpd.service: control process exited, code=exited status=1
Mar 30 13:31:30 server.ser systemd[1]: Failed to start Apache web server managed by cPanel EasyApache.
Mar 30 13:31:30 server.ser systemd[1]: Unit httpd.service entered failed state.
Mar 30 13:31:30 server.ser systemd[1]: httpd.service failed.
```

part of journal -xe:
```
# journalctl -xe
 systemd-logind[1680]: Failed to remove runtime directory /run/user/1042: Device or resource busy
```

**Comment by fevangelou** [comment]
If for some reason ports are not released by either Apache or Nginx (it can happen), do this via terminal:
```
fuser -k 8080/tcp
fuser -k 80/tcp
```

Then start both Apache and Nginx.

**Comment by dsfsvsdva** [comment]
Thank you for the workaround, but the problem still remains. Now it's one additional step to restart httpd. There is an issue that needs to be fixed.

**Comment by fevangelou** [comment]
This is not a workaround, this is a way to kill stuck services. You should probably reboot your server if these issues persist.

**Comment by dsfsvsdva** [comment]
It is a workaround. There is no stuck service. Problem persists on server reboot, that was the first thing I did. This is a problem with Engintron and needs to be immediately addressed.

**Comment by fevangelou** [comment]
If it was indeed a bug in Engintron, it would probably be visible on the dozens of thousands of servers using Engintron worldwide... The issue is clearly on your server and could stem from a few reasons, e.g. an older install of Nginx through another plugin.

**Comment by dsfsvsdva** [comment]
I do NOT have an older version of NGINX. There is nothing different about my server. Fresh install with no plugins except engintron. ENGINTRON ISSUE. Issue also exists with the thousands of other users.

**Comment by fevangelou** [comment]
Look, if Engintron doesn't work for you, don't use it.

> Issue also exists with the thousands of other users using the same latest version of cpanel and same latest version of vanilla un-edited CentOS 7.7.

I would love to see these stats if you have them.

**Comment by dsfsvsdva** [comment]
> Look, if Engintron doesn't work for you, don't use it.
> 
> > Issue also exists with the thousands of other users using the same latest version of cpanel and same latest version of vanilla un-edited CentOS 7.7.
> 
> I would love to see these stats if you have them.

ok just give me SSH access to thousands of users. May create a privacy violation.

**Comment by fevangelou** [comment]
What's the fix if it's simple?

**Comment by dsfsvsdva** [comment]
Good question. I did not develop this app so I don't know how to fix it. It only appeared on this most recent version of Engintron on my new server.

By the way I appreciate your work I even donated to Engintron previously and one of the only open source projects I've donated to.

**Comment by fevangelou** [comment]
Like I said, this is server specific. And I've only had 1 more person report a similar issue, that's why I added a "force restart" option in Engintron which does exactly that.

I don't know the exact specifics of why a process can get stuck like this and occupy a given port without releasing it even for itself (if the process is restarted). My guess is that termination fails and a duplicate process is started.

If the problem persists even after uninstalling and re-installing Engintron then it's most likely on Apache and not Nginx.

As a last resort, uninstall Engintron via SSH, reboot, then install Engintron again and let it finish. Even if it takes more time than usual to restart Apache in the last steps. Just wait for the entire process to complete. Keep in mind that I don't just do "service httpd restart" (which is snappy), I call a specific cPanel script that performs various checks before gracefully restarting Apache.

**Comment by dsfsvsdva** [comment]
No, it isn't server specific. More than one person has reported the same issue. 99% of people DO NOT REPORT ISSUES. Therefore if more than one person reports the same issue, then there is a problem.

**Comment by dsfsvsdva** [comment]
No, it isn't server specific. More than one person has reported the same issue. 99% of people DO NOT REPORT ISSUES. Therefore if more than one person reports the same issue, then there is a problem.

Previous versions did not have this issue, therefore the issue is with changes in a more recent version.

**Comment by dsfsvsdva** [comment]
> I've had 1 more person report a similar issue

No, it isn't server specific. More than one person has reported the same issue. 99% of people DO NOT REPORT ISSUES. Therefore if more than one person reports the same issue, then there is a problem.

Previous versions did not have this issue, therefore the issue is with changes in a more recent version.

**Comment by frilogg** [comment]
I have used Engintron since it was first released, and stil luse it on a dozen of servers for both my own company and on behalf of customers. I have not notices any trouble after upgrade. Sometimes services might hang, and need to be "killed" and restarted and then everything goes quite fast up and running again, so I will think it is server spesific. And after working with computers and servers for 20 years. most people do actually repport issues if its critical and it cant be fixed.

**Comment by dsfsvsdva** [comment]
Your previous experience is irrelevant to this issue. Not all people are affected by this issue but some are and thus there is an issue that needs resolved. Please refrain from irrelevant comments.

**Comment by fevangelou** [comment]
I'm sorry but I don't like your attitude. Nothing "needs to be resolved". This is an open source project which is provided to everyone for free to be used as-is. There is no obligation on my side against you or anyone else. If the product does not fit your needs, don't use it. It's that simple.

**Comment by cmqiwunaxw** [comment]
I have the same problem

**Comment by czwcasw** [comment]
Me too same problem

> I'm sorry but I don't like your attitude. Nothing "needs to be resolved". This is an open source project which is provided to everyone for free to be used as-is. There is no obligation on my side against you or anyone else. If the product does not fit your needs, don't use it. It's that simple.

Clearly something needs to be resolved because multiple users are having the same issue. It appears in reality you just don't know how to fix it and don't want to spend the time. If you aren't making enough in donations that's fair, but using ad hominem attacks against customers including donators like myself with valid issues isn't helping matters any. I expect a higher degree of professionalism and I am disappointed with your attitude in regards to real and valid issues.

**Comment by McL1V3** [comment]
Me too same problem
