### ISSUE TITLE
problem with xenforo sessions

### ISSUE THREAD

**Issue by petethumped** [engintron/engintron#12]
running latest WHM / Apache + memcached on a different host. installed engintron, everything rockets along, then users logged into my xenforo forum started showing up under other logged-in users' sessions, gaining full access to the other person's account. Including mine. Not good. Unsure if the problem affected other session stuff.

**Comment by Eniyi** [comment]
today I had the same problem, is there any uptodate solution for this issue ? all my websites are user-generated content like forums, or wp on this server, should I avoid to use engintron ?

**Comment by fevangelou** [comment]
@Eniyi The new version of Engintron (v1.5+) is completely re-written so you should not have this problem. If you do, you can either disable the dynamic cache (see the Wiki - installation article) or add exceptions for XenForo (cookies and URLs where users login) for the best results. By exceptions I mean specific cookies that XenForo may use for logged-in users or specific URLs where users login (e.g. /login) so that Nginx can shut off caching entirely. Similar exclusions are already built in for WordPress, Joomla and others in Engintron and if you can get this info from XenForo, I'll be happy to integrate them in Engintron's Nginx configuation.

**Comment by SashRaven** [comment]
>  add exceptions for XenForo (cookies and URLs where users login)

Is it possible to disable 1sec cache for domain?

**Comment by Nirjonadda** [comment]
@fevangelou Do you have any fix update ?

**Comment by fevangelou** [comment]
@sashraven yes, I'll update the Nginx config files with commented examples in the next (imminent) update.

@nirjonadda fix for what?

**Comment by MiguelMachadoM** [comment]
before I had the same problem with IPB & XenForo.

Solution for me:

edit default.conf from WHM 

	location @backend {
		include proxy_params_common;
		# === MICRO CACHING ===
		# Comment the following line to disable 1 second micro-caching for dynamic HTML content
		include proxy_params_dynamic;  (comment this line)
	}

**Comment by Nirjonadda** [comment]
A strange thing happening, Every time I am logging in, I'm being logged as a different user (probably with the ID's in my friend's list). After one or two refresh; I am being logged as my username.

**Comment by fevangelou** [comment]
@Nirjonadda disable micro-caching for dynamic content. Comment out line 32 in default.conf via Engintron's WHM app.
