### ISSUE TITLE
Issue with charsets "UTF-8" and "iso-8859-1"

### ISSUE THREAD

**Issue by vinaykumar9999** [engintron/engintron#1237]
Getting this in error log

[error] 14823#14823: *1521 no "charset_map" between the charsets "iso-8859-1" and "UTF-8" while reading response header from upstream, client: ::ffff:34.83.190.242, server: localhost, request: "GET /robots.txt HTTP/1.1", subrequest: "/robots.txt", upstream: "http://SERVERIP:8080/robots.txt", host: "www.domain.com"

[error] 14821#14821: *2273 no "charset_map" between the charsets "UTF-8" and "iso-8859-1" while reading response header from upstream, client: ::ffff:66.102.6.181, server: domain.com, request: "GET /robots.txt HTTP/1.1", subrequest: "/robots.txt", upstream: "https://SERVERIP:8443/robots.txt", host: "www.domain.com", referrer: "https://www.domain.com/"

How can i fix this ?

**Comment by fevangelou** [comment]
Let's start with the basics... Have you modified Engintron's Nginx configuration by any chance?

**Comment by vinaykumar9999** [comment]
Nothing has been changed. It is fresh install.

**Comment by vinaykumar9999** [comment]
@fevangelou 

These Errors are increasing in error.log

I have uninstalled engintron and reinstalled engintron, but still errors is coming.

How can i fix this? Please help.

**Comment by fevangelou** [comment]
The issue implies a specified charset value in Nginx's config. That's why I asked if anything's modified. Double-check with anyone else that may have changed Engintron's configs.

Otherwise treat it as a generic Nginx issue and Google it for potential solutions. I have, and it points to certain values in nginx.conf which are not present by default in Engintron's Nginx setup.

**Comment by danreb** [comment]
Following, confirming that this error is also present in my engintron installation in a Live website

2020/10/07 18:37:06 [error] 35398#35398: *8014 no "charset_map" between the charsets "iso-8859-1" and "utf-8" while reading response header from upstream, client: 2001:41d0:2:51d::, server: localhost, request: "GET /rss.xml HTTP/1.1", subrequest: "/rss.xml", upstream: "http://333.45.6.22:8080/rss.xml", host: "www.livedomain.com"
2020/10/07 18:44:57 [error] 38382#38382: *19717 no "charset_map" between the charsets "UTF-8" and "iso-8859-1" while reading response header from upstream, client: ::ffff:333.45.6.22, server: livedomain.com, request: "GET /apple-touch-icon.png HTTP/2.0", subrequest: "/apple-touch-icon.png", upstream: "https://333.45.6.22:8443/apple-touch-icon.png", host: "livedomain.com", referrer: "https://livedomain.com/"

Looking for solution too

**Comment by fevangelou** [comment]
If you Google the error, all you get is Nginx configs with special charset* directives in them. E.g. https://forum.nginx.org/read.php?2,285058,285091

If you never had another installation in Nginx or one that comes from another repo, perhaps it's an Nginx bug, in which case https://forum.nginx.org would be more appropriate to ask.

**Comment by locksmithunit** [comment]
is not nginx bug... i check it.
I even delete the Nginx folder and install engintron again.

this isiue come from dynamic cache inside engintron and APACHE CPANEL VHOST.

I tried almost everything:
https://www.w3.org/International/questions/qa-htaccess-charset
and even cPanel support change the MAIN INCLUDE.

Engintron gets all the time the same error.
is because the HTML (dynamic cache)

usually, even plugins, excluded the robots.txt and sitemap from NGINX...
issue does not come from engintron but engintron is part of it.

you must configure charset_map.
my configuration remove ISO completely ( this because I put the charset map empty ):
```
## MIME ##
include         /etc/nginx/mime.types;
default_type application/octet-stream;
## Charset ##
charset                                     utf-8;
override_charset                          on;
charset_map       iso-8859-1 utf-8 { }
```

charset_map       iso-8859-1 utf-8 { }
is empty,,, between the { }

need to be right mapping... you must do it for the dynamic cache...
i will search as well, but @fevangelou 

if you have the right mapping code. 
send me here I will test it.

is that 100%
I have paid support from cPanel.
they get inside my server and help me anytime i need help.

i tell you @fevangelou 

if you provide the right: 
charset_map       iso-8859-1 utf-8 { 
 

 the real mapping code need be here @fevangelou 

}

Promise you this is the solution 100%
as i said i will try get the right mapping from the ARIN registry. (WHIOS)

but if you can help me @fevangelou is be helpful.
