### ISSUE TITLE
Not working after make some new SSL for website

### ISSUE THREAD

**Issue by hizkiace** [engintron/engintron#1250]
Hello i have problem after installing new ssl into a website. when i try to install ssl into new site and it was installed, the certificates show invalid SSL. its diffrence when i disable my engintron, its working. but when i enable engintron again its invalid. any help?

Thanks

**Comment by fevangelou** [comment]
Engintron requires a few seconds to spot such changes in order to copy the certificate data into its own configs.

Afterwards, you need to verify the SSL is properly used by Engintron by opening a private window on you browser. You do that because browsers cache certificates for a few minutes and you won't see such a change instantly unless you use a private window. For everyone else the certificate will be active a few minutes later.
