### ISSUE TITLE
1.14 update caching issues with wp multisite

### ISSUE THREAD

**Issue by bfleck313** [engintron/engintron#1255]
I have a couple different environments setup (multiple servers) with single and multisite installations of wordpress and engintron. Been working great for years. Since the 1.14 update, I'm having issues with any of the post updates refreshing for non-logged in users. I have to purge cache and temp files in engintron in order for the websites to update for the public.

The problem seems only isolated to the multisite environments, b/c single site posts can be updated with zero issues. I haven't changed any of the custom settings in engintron config files. I've since had to disable engintron until the problem is solved :(

Any ideas?

Thanks,
Bryan

**Comment by fevangelou** [comment]
Engintron will respect any cache-control headers that these WP sites may send and as such, cache the content accordingly. This is not a side-effect, this is how caching should work.

If you need instant refreshing, you got caching wrong.

**Comment by savoures** [comment]
Hello
I have exactly the same problem in normal installations of WP. I don’t know if it should be like this but it should not !!! I have problems with all my sites now. 
Could you suggest any way to fix this ?!

**Comment by fevangelou** [comment]
If your site(s) send cache-control headers with a defined time (or an "Expires" header with a date set in the future), then things work as expected. Unless you provide a test domain to run a curl command, I can't know for sure though...

**Comment by fevangelou** [comment]
P.S. The trick for WP content managers is to also login. This shuts down any caches and it's the proper way of managing content in such scenarios.

**Comment by savoures** [comment]
As me and bfleck313 said when you are logged in everything works as expected. The problem is when you are not logged in.
Before the 1.14 update it was working as expected, meaning that when I change something and refresh I can see the change without being logged in. This is a problem because if I want to show some changes to my client I can't. Ok you will tell me to login to who and delete the cache, but its not always evitable. Imagine that I have e reseller who of course has no access to the whm. This means that when he wants to show the changes to his clients it would be impossible. Also the logical thing is when I use a caching plugin to have to empty the cache (ok yes understandable) but not to access the server every time 
If you want to check I could give you some domains. Toklasikon.gr , onefootforward.gr , escaped.gr , escaperoute.gr , zolithros.gr , kifisiarun.gr 
Some of these sites are on Cloudflare and some are not !! Also some are using caching plugins and some are not

**Comment by savoures** [comment]
Also I tried to use your script to install APCU and noticed that you have included up to version 1.18. The latest version is 1.19 !!!
If you could update that so I could update also :D

**Comment by fevangelou** [comment]
Your .htaccess file probably sets a very high cache-control value. See this:

```
$ curl -I "onefootforward.gr"
HTTP/1.1 301 Moved Permanently
Date: Tue, 24 Nov 2020 16:00:15 GMT
Content-Type: text/html; charset=iso-8859-1
Connection: keep-alive
Set-Cookie: __cfduid=df524d3efc17ce109377f311664d71a721606233615; expires=Thu, 24-Dec-20 16:00:15 GMT; path=/; domain=.onefootforward.gr; HttpOnly; SameSite=Lax
Location: https://onefootforward.gr/
**Cache-Control: max-age=31536000**
Expires: Wed, 24 Nov 2021 15:39:01 GMT
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Nginx-Upstream-Cache-Status: HIT
X-Server-Powered-By: Engintron
CF-Cache-Status: DYNAMIC
cf-request-id: 069c95048e000038ce62834000000001
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=FOU7WRmX6wa3N5BhBInmVP1OrW4GaaKbyKeeDzIFdBaPE3xqGfUzlqF2oulVaNQN%2FhyjsFbpKzDkVAYhf3Vt2Yeh4rXUX5Cvq24uqJH%2BUiDV%2FcTEA1rknPCnFGZiOw%3D%3D"}],"group":"cf-nel","max_age":604800}
NEL: {"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 5f745780efa038ce-ATH
```

Engintron respects any cache-control headers and this is how caching should work. If you need to disable caching for dynamic content, it's a one liner in custom rules.

**Comment by savoures** [comment]
ok I ll try that !!
tell me something else. I am trying to set cache expiration for jpg and other kind of files through htaccess but when I check the website in PageSpeed or other tool I see that still the expiration is not as set (I set it far but they expire short) what is wrong ?

**Comment by savoures** [comment]
Also the Cache-Control: max-age=31536000
that you mention is not in all of my sites !!!!

**Comment by fevangelou** [comment]
Engintron pre-configures the expiration time for static files to 30 days. Longer caching is impractical.

I didn't check all your sites.

**Comment by savoures** [comment]
ok please check for example escaped.gr cause I can't see any cache-control there. In general what we are asking is that with the same htaccess files and configuration with Engintron 1.13 everything worked as we describe .. after 1.14 it does not. How can we have the 1.13 configuration in order to make it work as before ?

**Comment by savoures** [comment]
Any update on this ? It really is problematic and must be solved somehow, it is not the htaccess files and I will say it again .. in 1.13 it worked ...now it is not working so either fix it or at least tell us a way to downgrade to 1.13 !!!!!

**Comment by fevangelou** [comment]
"Demanding" to fix something (that isn't broken by the way) from an open source project will always have the opposite effect and probably get you banned from a few communities.

You pay for cPanel already, so don't be a cheapskate, pay someone to optimize your server with Engintron (or without, I don't take any commission either way) and also explain to you how caching works. Or don't use Engintron and enjoy crap performance off your VPS in the UK.

We're done here.

**Comment by savoures** [comment]
I apologise for being misunderstood !!!!! I am not demanding and for sure I am thankful to your effort and work so far. It is just my tone so I am sorry !!!!
