### ISSUE TITLE
Problems after uninstalling

### ISSUE THREAD

**Issue by brunocerq** [engintron/engintron#1304]
What exactly the uninstall does? It reverts back the old whm configuration stored somewhere?
I ask this because when I first installed engintron the server was on another VPS instance ( google compute engine ) I then created a new instance based on a snapshot, and everytime a new instance is created a new internal IP is generated ( google controled ) so I had to use the migration tool to update the new IP, and now when I uninstalled engintron on this new instance, I lost connection to all websites, and after some review, I noticed that the local IP was again pointed to the original first installed IP and not the current one.

**Comment by fevangelou** [comment]
Engintron may configure the NAT IPs in the relevant Apache module which in turn configures Apache logging properly, since Apache is used behind a proxy (Nginx). Engintron (and Nginx by extension) do not store any IPs. You can configure proxying by IP (instead of DNS resolving), but YOU have to do this, Engintron does not do it on its own.

But the issue boils down to cPanel itself.

If you cloned a VM with cPanel on it, yeah, it's like begging for trouble, I can guarantee you that... 😄

**Comment by brunocerq** [comment]
I have made a test, I remade the snapshot recover and this time I disabled engintron instead of uninstalling, by only disabling it everything works fine, but if I uninstalled it, it stops working, I lose access to websites.
Any idea why?

**Comment by fevangelou** [comment]
The uninstall routine is pretty clear. Perhaps some stuck port is causing issues. Check that Apache switches back to 80 & 443 in Tweak Settings. Then reboot the VM.
