### ISSUE TITLE
http to https redirect rule causes redirect loop on non-existing static files in case try to access on http

### ISSUE THREAD

**Issue by kepesv** [engintron/engintron#1306]
Hello 

We are hosting various Drupal CMS websites on Cpanel + Engintron. We're redirects our website visitors to the https version of site. We are using a standard declaration in .htaccess like this or equivalent:

```
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```

This redirect working well on URLs pointing to existing static files and URLs handled by the CMS witout static extension but we have issues in a special case:

1., somebody tries to access a static file (url) with a file extension like .xml, .csv, .jpg etc
2., on http protocol
3., which file doesn't exist

What's happening?
- User tries to access http://mydomain.com/static.xml which doesn't exist
- Because of the rule in the .htaccess file Engintron gets 301 redirect to https://mydomain.com/static.xml  
- Engintron sends to the client the 301 redirect to https://mydomain.com/static.xml AND store in its microcache(?) without procotol something like this: mydomain.com/static.xml redirects to mydomain.com/static.xml
- Client send a new request to the https version https://mydomain.com/static.xml
- Engintron find it in its cache and says: Ohh, hit! I know that mydomain.com/static.xml is a 301 redirect to mydomain.com/static.xml and send this to the client.
- And voila here is a 301 redirect loop instead of expected "404 not found" OR (in my case) the expected http 200: in my case the .xml file is not a real file but neither 404: Drupal should catch the url and dynamicall generate an xml. But Drupal never get the request because of the redirect loop.

I would like to ask for a suggestion to solve this problem.

I think the main problem is that Engintron handles http and https equal in its cache Engintron can't distinguish http and https on cache hits but the response should be different.

**Comment by fevangelou** [comment]
If this was a problem, no redirect would work. Nginx does not care what happens with rewrites in Apache. It cares about paths/file types. If it's a static file (by extension) it will be treated differently to say HTML content. However there is no intervention in Apache's redirects. My guess is there \*may\* be some other redirect in Drupal which you need to figure out.

**Comment by kepesv** [comment]
Okay, I've created a Drupal-free "minimal" test environment:
- new cpanel account + a domain points on it + installed ssl certificate 
- just one .htaccess file in the publix_html directory - no other. Its content:

`
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
`

Then I've tried to access the non-existing http://mydomain.com/xyz.xml from my browser.
The result is the 301 redirect loop.

Please check it on your engintron environment. I'm sure that you'll experience it because I've tested this on 2 servers working with engintron. These servers are independent from each other.

**Comment by fevangelou** [comment]
Are you manually inserting this redirect or using cPanel for that?

**Comment by fevangelou** [comment]
2 more things:
a) You also need "RewriteEngine On" above the 2 lines you mentioned in your .htaccess file.
b) An actual URL would help as I can check the redirects via cURL.

I host multiple Drupal sites on various cPanel configs. There is no redirect loop whatsoever. And this is why:

Nginx HTTP receives request, passes it to Apache HTTP which redirects to the HTTPS version of Nginx, which in turn passes the request to Apache HTTPS.

Perhaps you're using CloudFlare flexible SSL which does HTTPS to HTTP proxying and this is what's causing your issues.

**Comment by kepesv** [comment]
"Are you manually inserting this redirect or using cPanel for that?" I've manually created the .htaccess file and inserted the code above.

"a) You also need "RewriteEngine On" above the 2 lines you mentioned in your .htaccess file." Yes i know. I've added this line. It does not change anything, apache do the redirect both with and without this line. 

"b) An actual URL would help as I can check the redirects via cURL." http://andras.eu/anything.xml  - you can type any filename  with extension e.g.: xml, jpeg etc. (there is no any existing file in the directory. Only .htaccess.). It is important that first call the url on http protocoll because in case you call the non existing file first time on https protocol you will not experience any error as there will be no redirection and engintron will cache the file properly and in this case in the microcache lifetime the file will available both http and https protocol.

"Perhaps you're using CloudFlare flexible SSL which does HTTPS to HTTP proxying and this is what's causing your issues."
No I don't use CloudFlare.

**Comment by fevangelou** [comment]
The .htaccess code you mentioned above is not the only thing that you have obviously as you need more rules to handle Drupal's rewrites (e.g. for .xml files as the URL you referenced). My guess is that the redirect loop occurs because Drupal is re-redirecting. Why this doesn't occur in Apache alone? Well, Nginx is less forgiving compared to Apache :)

Additionally, search for any common Apache includes that may cause problem.

According to https://trends.builtwith.com/framework/Engintron there are more than 400,000 sites served via Engintron. You're the first to raise such an issue. So statistically speaking only, it's most likely an issue on your end only.

**Comment by kepesv** [comment]
"My guess is that the redirect loop occurs because Drupal is re-redirecting." - I don't understand why are you still mentioned Drupal: Eventually I've clarified and tested above that the bug is independent of Drupal and provided an URL where you can check it and you can check here too that there is no CMS. 

"So statistically speaking only, it's most likely an issue on your end only." - I would think so too, but We can make sure of this if you are so kind and take a test on one or two of your server: "clear/new" cpanel account, public_html with only one file:  .htaccess, content is: 

```
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```
And make a request from your browser to e.g. anything.xml via http protocol.

**Comment by hron84** [comment]
I followed what @kepesv talked about with a brand new cPanel account and I experiencing the same. No other files are contained other than the `.htaccess` file, and the redirect loop happened to me with default configs.

**Comment by hron84** [comment]
I dug into this issue and it seems like Engintron 1.14.0 update made a change how the caching working. On my server, `/etc/nginx/proxy_params_static` file contained this:

```
proxy_cache_key                "$host$request_uri";
```

And I found a `/etc/nginx/proxy_params_static.bak` file, the comments said it's from Engintron 1.9.1 and the corresponding setting was

```
proxy_cache_key         "$request_method$scheme$host$request_uri";
```

Copying this setting to the active `/etc/nginx/proxy_params_static` (I changed nothing else but this setting), restarting Nginx and clearing Engintron cache seems solves the problem. With this setting I can get redirects working normally. 

This is because this setting generally controls how Nginx stores the cache. Nginx uses its cache as a key-value store and stores/fetches the cache by keys. `proxy_cache_key` tells how the cache key was generated. If it does not contain the `$scheme` part, you get same answers for both HTTP and HTTPS requests. While storing cache without scheme reduces the size of the cache by up to 50%, it causes issues when you store redirections in the cache too. 

@fevangelou May I ask you why did you change this setting in 1.14.0? It was purposed to reduce cache size?

**Comment by kepesv** [comment]
@hron84 Thank you for your help: I've changed proxy_cache_key based on your suggestion and this is solved the problem. 
@fevangelou As you can see, it causes issues if the cache key does not contain the protocol so it would be worthwhile to fix in the next release what one of the previous release corrupted.

**Comment by fevangelou** [comment]
Actually I think the issue is elsewhere. Changing "proxy_cache_key" is just one way of fixing this. But the most optimal way is to change this line https://github.com/engintron/engintron/blob/master/nginx/proxy_params_static#L47 from `proxy_cache_valid              10s;
` to `proxy_cache_valid              200 10s;` so only HTTP requests a with a 200 code are cached and not redirects (like 301 or 302 which are now indeed cached).

I've issued v1.15.0 for that. Thank you for your persistence :)

And yes, the reason I changed how the cache object hash is created boils down to slimming the Nginx cache overall, so you can enjoy longer cache times when using the right cache-control headers. This means that Engintron's Nginx config merges GET and HEAD requests, as well as HTTP and HTTPS requests.

**Comment by fevangelou** [comment]
@dhmetros No, it isn't. $scheme is used to build the hash for each cache object. Totally unrelated to actual traffic...

**Comment by hron84** [comment]
@dhmetros let me shamelessly quote myself:

> Nginx uses its cache as a key-value store and stores/fetches the cache by keys. `proxy_cache_key` tells how the cache key was generated. If it does not contain the `$scheme` part, you get same answers for both HTTP and HTTPS requests. 

The cache key will be used to generate the hash that is used to access the cache entries. If the cache key did not contain the scheme, Nginx tried to serve same content for both HTTP and HTTPS schemes. If you have a redirect from HTTP to HTTPS and it gets cached by Nginx, it will always respond with a redirect, even if the URL is already called from HTTPS, since this is the response it fetches from the cache. This is why important to differentiate HTTP and HTTPS responses (or disable caching for 301/302 responses). 

But Nginx uses this only for getting things from cache. From communication perspective, it otherwise follows the rules: if the URL is called from HTTPS then it serves it over SSL, if called from HTTP, then it serves it unencrypted.

**Comment by dhmetros** [comment]
@hron84 Ah, so you did.  My apologies.  Consider my post then a stress of what you had already stated.  :)
