### ISSUE TITLE
Engintron WIKI | optimization-guide-apache

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1386]
I Know it's little bit out of the scoop @fevangelou 
**but the best recommendations i see on the network for cPanel, you the number 1 (the best).**
I prefer to try my luck maybe get a straight answer from you.

I see you changed the WIKI DOC'S TOTALY, even in the OPTIMIZATION section.

I looked at the APACHE CONFIGURATION:
https://engintron.com/docs/#/pages/optimization-guide-apache

I know you recommended here in GitHub the mpm_worker ( i use it of course ):
https://github.com/engintron/engintron/blob/master/cpanel/EasyApache_Profiles/EA4/Engintron_EA4_2022_v1_EL7.json

NOW I KNOW CPANEL IS DESIGNED FOR MPM_PREFORK...

Your recommendation is for very high machines in the ENGINTRON WIKI **( I HAVE 2RAM 2CPU - 2X2 )**

Can be an option for NEW WIKI DOC'S for 2X2 machines?
or if you can give me a tip here it be very very helpful :)

I was thinking to follow the WIKI docs and removing 50% from what you did ( your docs its for 4x8 ):

```
StartServers        5
# Same as your CPU core count, no less than 5 though

MinSpareServers     5
# Same as your CPU core count, no less than 5 though

MaxSpareServers     10
# Double as your CPU core count, no less than 10 though

ServerLimit         250
# 500 is a good base point for an average 4-8 CPU core system with 8-16 GBs of RAM. If your server has higher specs, you can increase up to 800-1000, anything beyond that is probably overkill

MaxRequestWorkers   250
# Same as "ServerLimit"

MaxRequestsPerChild 2500
# 10 times "ServerLimit"

Timeout             300
# Stick to the default value that comes with cPanel, there is no reason to lower this value. If you also have Engintron installed, Nginx's timeout is also at 300 sec to align with this setting in Apache.

```

What do you think @fevangelou  ? ( if its possible give a little tip for small machines to fit APACHE to Engintron. )

**Comment by locksmithunit** [comment]
I actually find the original worker recommendation ( even cPanel docs provide them )...

From the day i used Engintron, i moved from prefork to worker.
but i didn't know the cPanel configuration shipped with PREFORK DEFAULT.

I investigated that this week:
https://www.youtube.com/watch?v=oaKczgPD3Ys

recommended for everybody:
https://docs.cpanel.net/ea4/apache/multi-processing-modules-mpm/

if you look good, they offer this:
https://httpd.apache.org/docs/current/mod/worker.html

This it's because cPanel developers have already designed cPanel to fit mpm_worker AUTOMATICALLY.
THE ONLY THING THAT NEEDS TO DO, ITS CHANGE 2 VALUES:
START SERVERS - 2 ( this not the default. **default it's 3**, but APACHE doc's offer this as a better option - optimized value )
SERVER LIMIT - 16 ( Default )

All the rest will be adjusted automatically to this configuration at the bottom of this file:
https://httpd.apache.org/docs/current/mod/worker.html

cPanel offers this link in their docs.
I actually try it, have a very good result.
**Recommended to everybody.**

Actually much better for Engintron.
Everything comes from Engintron, Apache needs to be optimized for lower resursece.
**I have machine 2x2, from the minute i change these 2 values, i get 1 CPU less and 10% RAM less than before.**

I close the subject, i hope one day it's will help someone.

**Very Recommended:**
https://httpd.apache.org/docs/current/mod/worker.html

**Comment by fevangelou** [comment]
@locksmithunit The values you have are just fine.

**Comment by locksmithunit** [comment]
256 server limit per thread? @fevangelou 
it's impossible...
I get much better results on default mpm_worker. ( server limit - 16 ).

**Comment by fevangelou** [comment]
The config I propose in the docs was actually tested since many years ago, using the prefork mpm. I see that the defaults are different on the worker or event mpms, but the logic is more or less the same. ServerLimit & MaxRequestWorkers are dependent on each other & given than you can't control any of the newer options for Thread*, keeping the rule I proposed is not far off.

Of course you can always consult with https://httpd.apache.org/docs/current/mod/mpm_common.html and adjust according to your needs.

Like I've mentioned elsewhere, if you use cPanel on small Google Cloud VMs, you're wasting resources really. I would recommend more generous setups at Contabo (the best price to specs ratio) or Linode, DigitalOcean, Vultr etc. And if you say that "clients demand so", well, not really. Clients are clueless most of the times. And a Google VM is just that, a VM. And as it's been known with AWS (and I assume GC, Azure etc.), their smaller VMs are usually crap or too throttled. Like mechanical SATA drive IOPS capable or crippled bandwidth. The point of using Google Cloud, AWS etc. is for the orchestration tools they offer for enterprise infrastructure or for startups that need to scale. Not for "monoliths" like cPanel on EL based OSes.
