### ISSUE TITLE
PHP-FPM 

### ISSUE THREAD

**Issue by xuhaibkhan1122** [engintron/engintron#1393]
What are recommended SYSTEM PHP-FPM SETTINGS !

**Comment by locksmithunit** [comment]
**I was keeping the default.**
I know you want (and think) need optimized cPanel, but its wrong,
especially if you use Engintron.

to rise PHP-FPM does not give you many benefits, opposite, you will crush your server.
**(PHP-FPM is the must strong software you have on your cPanel, its consume CPU and RAM in a level you cant imagine)**

My recommendation, keep the cPanel default, they already optimize the values...!

People don't know it, but PHP-FPM is not shipped with these values.
These values are unique and made by cPanel.
**Engintron fits them perfectly, trust me.**

Think about cPanel as "Windows" for Linux.
you do not adjust DOS on your computer... because Microsoft does it better than you.

The same thing cPanel. **(Engintron as well, use the default, it's already fully optimized)**
trust me, i know it sounds very limited but i go against the flow for 4 years.
in the end, i found myself using the defaults. (maybe a little adjustment but default cPanel, and Engintron as well)

I recommended you look here:
https://support.cpanel.net/hc/en-us

you can ask them whatever you want (except Engintron)
you have a search bar in this link you can put PHP-FPM you will see articles made by cPanel developers.

I recommended you follow it, it help me a lot.
good luck my friend, hope you listen to my advice.

**Comment by locksmithunit** [comment]
He said it before 2 years... i believe @fevangelou prefers you will stick to the default.
anyway, you can wait to his response.

**Comment by fevangelou** [comment]
@xuhaibkhan1122 The formula is up to date as it's part of the new docs for Engintron v2.

What you mention is just fine. I would even go with `Max Children: 4` and raise it to 6 only for the few sites that really need more resources, which you can easily figure out by looking at the aggregated bandwidth stats for each site in WHM.

**Comment by Yossifsolman** [comment]
Sorry i jump the topic, but if you have 2 CPU?
So i need to do 1 CPU process? Huh, don't know a little bit wired, no?  (I believe 2 will make it, but 1?)
I have machine 2cpu x 2ram on GCP.

Max Requests : 4000
Max Children: 1
Process Idle Timeout: 1s

Don't know if it will be good.
I check 2, but i think this little too.

**Comment by fevangelou** [comment]
2 whole CPUs for cPanel? You're brave...

The performance guide suggests some configuration options/ranges. It doesn't apply to such low specs though. Try 2 or 4 and see how things work out for you. If you're hosting a few sites it should work out just fine.

**Comment by Yossifsolman** [comment]
2 works wow...
Btw, cPanel recommended on those machines of GCP:
https://www.youtube.com/watch?v=oEj62B_Y8KY&t=55s

I already run for a year, 2 machines clustered to each other of e2 - 2x2 xenon intel.
Work amazing.

I did:
Max Requests : 2000
Max Children: 2
Process Idle Timeout: 1s

I think go up to 4000 actually better, but i still testing that.


Not only that, I am short on memory too… 2gb and after cPanel process it with the kernel it's 1878mb (1.8gb RAM)

But when the request come from PHP FPM to NGINX, it's very easy and the machine fly.
So... i think, much more request will make the server breath better. :)

**@fevangelou if you have another recommendation i be happy to hear (like 5000 6000 Max Requests)**
Nginx can handle 100K 200K EASY, but i don't know if this machine survives haha
