### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by Friends4U** [engintron/engintron#1395]
Hi,

Just installed Redis, but my Wordpress sites all look alike now :) It it true that the Redis is for one site only?

**Comment by Friends4U** [comment]
Bump? Anyone...

**Comment by fevangelou** [comment]
Your WP sites probably use the exact same hash keys in wp-config.php, so you get cache collision issues. In any case & since this is dependant on the plugin you use for Redis, this is not the place to ask for more info. The Redis installer provided is just that, an installer. It's not a door to support 3rd party software.
