### ISSUE TITLE
Please help me, how to configure Ngnix on Engintron to cache in Server Ram Memory.

### ISSUE THREAD

**Issue by RicardoPG3** [engintron/engintron#1406]
Hello friends, I need help, I have a server on Contabo with 10 cores and 64GB Ram memory, on this my server has 5 e-commerce sites on wordpress woocommerce, even installing engintron the CPU usage is still a little high, like me I have 64GB of RAM memory and the use of this memory on my server never exceeded 10GB I wanted to configure Engintron's Nginx so that all possible caching is done in my server's Ram memory, I believe that if you cache in Ram memory the sites should be very fast and relieve the use of this high CPU a little, am I right?
I want to make use of this memory that I have available and it's practically unused on my server, understand?

Please can someone help me and pass here where I should change and what should I change to make the Nginx cache fully in Ram memory?

**Comment by amanullahtanweer** [comment]
The default config should be okay for you it will proxy all the request and your server takes less load

**Comment by fevangelou** [comment]
@RicardoPG3 Since you mentioned Contabo, you could be affected by CPU steal issues. It's also usual for the package you're in. Check your Munin CPU graphs in cPanel for red colored regions. If they take more than 20-30% of the graph on average, you have a CPU steal problem.

**Comment by xuhaibkhan1122** [comment]
Here is how I am using ramcache for engintron cache

Since engintron is installed in nginx folder make a folder there so there wont be any permission issues.
mkdir -p /var/cache/nginx/ramcache
mount -t tmpfs -o size=8G tmpfs /var/cache/nginx/ramcache
nano /etc/fstab
tmpfs /var/cache/nginx/ramcache tmpfs defaults,size=8G 0 0

Edit nginx.conf and add the folder path /nginx/ache/ramcache/engntron_dynamic to make sysmlink 
systemctl stop nginx
ln -s /var/cache/nginx/ramcache/engintron_dynamic /var/cache/nginx/engintron_dynamic
ln -s /var/cache/nginx/ramcache/engintron_static /var/cache/nginx/engintron_static
systemctl start nginx

I have dedicated 8GB ram, and have assigned 4GB to dynamic and 2GB to static, and left 2GB as a free space fo dynamic cache can use without disk full issue.

Its workign fine for me, the only little issue is that engintron page(WHM) wont show the size of (engintron_dynamic and enginton_static) but it does show it in the disk attached so its kinda work for me. 
But @fevangelou can actually guide it way better then me if he could show us how to properly setup ramcache.
