### ISSUE TITLE
Build Engintron's Nginx to include mod_pagespeed

### ISSUE THREAD

**Issue by natedesigns** [engintron/engintron#142]
Apologies if this has been raised before, but I can find no record of it. 

I've just installed Engintron, and am seeing great speed benefits. I'm keen to get pagespeed module into the mix, and am aware I would need to recompile Nginx with the relevant flags and add the necessary attributes to the nginx.conf / default.conf
[https://developers.google.com/speed/pagespeed/module/build_ngx_pagespeed_from_source](https://developers.google.com/speed/pagespeed/module/build_ngx_pagespeed_from_source)

However, does anyone have experience of the pitfalls or things I should look out for when doing this? Any suggested configurations which are tried and tested? Is there a reason that this isn't an option when installing?

I'm on Centos 6.7, php7 (though only testing, I'm thinking about taking back to php56), Engintron latest.
It's a Magento site that i'm looking to increase speed on. Currently at pagespeed score of 88 for the front page and 85 for the product page. I think with mod_pagespeed it would take it into the 90's.

Thanks in advance

**Comment by fevangelou** [comment]
OK, first off. Pagespeed scores are a performance SUGGESTION. Not a god given rule to follow. Engintron will significantly speed up the server-side processing of delivering a website. It will also improve the client-side perfomance for a site by properly setting cache expiration headers. However if your site has huge/unoptimized images, a gazillion of CSS and JS files, Engintron can't help you with this. By using mod_pagespeed you could remedy the issue with concatenation, but that doesn't mean that things will actually work.

The easiest solution for you in order to keep the benefits of Engintron (e.g. with auto-updates of Nginx when CentOS updates etc.) is to just use CloudFlare. CloudFlare offers similar client-side performance tools and they are far easier to control in there than in mod_pagespeed. Give it a try.

**Comment by natedesigns** [comment]
HI @fevangelou and thanks for your reply. 

I completely agree, but you must understand that it's such an easy system to 'rank' your speed on, as such people high up in companies see this and want to improve it. I would far prefer to 'rank' via webpagespeedtest.org, as I find it has far more detail, but who can argue with Google + the masses.

We already use CloudFlare, but prior testing with nginx + mod_pagespeed + CloudFlare had yielded better results. In this I was removing whitespace, comments, converting images (I worry about cpu here) and combining css / js. Hence just wanting to try this experiment.

**Comment by masteranalyze** [comment]
@natedesigns  you said that : "It's a Magento site that i'm looking to increase speed on.  ",can you tell me more details about this?I mean on what kind of hosting your running Magento?On an shared hosting,vps,cloud,dedicated?What is the hardware configuration your having on your side?

**Comment by natedesigns** [comment]
@masteranalyze we have quite a decent setup with eukhost4u. First of all, it's Magento 1.9.2 and our hardware,If memory recalls, is:
2 x 16cpu core, 128gb with 4x 480gb SSD running on RAID 10 running Centos 6.7

The scores I'm getting are with it as a dev server, I'm currently doing load testing as it will become our production server.  

I'm finding, roughly speaking that with Ngintron alone I'm getting around the 4sec doc ready with 13sec full load with a 86 pagespeed rank. 
I did testing before installing Ngintron, when my setup was Nginx + mod_pagespeed, and the load was around the 3sec mark with a 7/8 sec full load time.
(load times are taken from webpagespeedtest.org on a 5 test average, quoting first load).

Thanks any help is appreciated and I understand without access to our site, it's hard to base a true opinion with so many factors.

**Comment by laurfx** [comment]
Hello,

You can install mod_pagespeed with easyapache 4 and it will work, you don't need to recompile NGINX for that.

https://github.com/pagespeed/cpanel

**Comment by masteranalyze** [comment]
@natedesigns i think laurfx,gaved you the solution.

Actually i could not find that configuration on the host that you mentioned,that configuration is more then good for Magento but power is nothing without control.

You have speed on 3 levels and each one depends on each one:
-speed on the server level
-speed on the networks level
-speed on the user level

Engintron acts only on the server level.
With the websites like gtmetrix or the ones you mentioned are testing tools witch are good,but they are just for this 1 second test,because if one route of one node is down ,from Florida to Frankfurt,or problems between networks,that is something you can`t control.
On user level,if that user is from Spain and with an poor 2g/3g mobile connection,again you can`t do nothing about that.

As @fevangelou mentioned page speed is basically an tool,for suggestion,the same way you can use yslow,gtmetrix,pingdom or any other related tools.

They might be good on some cases but bad in others cases,pagespeed was an service dropped down by google on 3 august 2015 they even take it off from their Google app Engine,on 1st december 2015 and this is their press release:"Today we are announcing that PageSpeed Service will be turned off on 3rd August 2015. Users must change their DNS to point away from the service by this time, or their sites will cease to function. We have created a migration page that includes assistance for changing DNS as well as information on other ways PageSpeed technology can be employed on websites. Please see https://developers.google.com/speed/pagespeed/service/Deprecation.

At the same time we are also announcing the deprecation of PageSpeed integration with Google App Engine. If you are using PageSpeed integration on Google App Engine, it will continue to function until 1st December 2015, after which PageSpeed optimizations will no-longer be applied to your app. No action is required on the part of App Engine users; after this date apps will continue to operate, except without the benefit of the PageSpeed optimisations. Users that wish to pre-emptively disable PageSpeed can follow the instructions at https://cloud.google.com/appengine/docs/adminconsole/pagespeed#disabling-pagespeed."

You should mention to the birocrats that hired you,that they don`t know nothing about technology,and come on bro :"Currently at pagespeed score of 88 for the front page and 85 for the product page. I think with mod_pagespeed it would take it into the 90's." are you joking me right???

So your driving on the highway with 185 km/h and you want just to get 190km/h ????
Will the birocrats pay you more if you show them an score of 90 instead of 85-88??? Or what is the point?
I would it understand the point,if your going with 185km/h and now you want to go with 220-230km/h,i could at least understand you.

Sometime those score can make actually your website to load slower,i saw website with that pagespeed score of 95 loading 5 seconds and with score 83 loading in 3 seconds,it depends on alot of factors,there is no general rule about speed and it does depend on alot of factors.

Your also mentioning that : " It's a Magento site that i'm looking to increase speed on. " so your looking to increase the speed and make your website faster or are you looking to show some birocrats instead of 88 an 90 page score ?!??Or you wish both?

Now if you wish speed on Magento,actually you should hire an Business Arhitech witch will basically come with an team and an least an Business Integrator,to integrate things out.

The business arhitech evaluates and understand all the business and afterwards with the business integrator implements what needs to be implemented,more exactly you need an expert on the fields of :Magento,Cpanel/Whm,Network Level,User Level,Business Level,Products Level,Inventory,Cashflow,etc.

On that magento site,it depends on how many products you have on it,pictures,images,text,everything matters,now if you want to concentrate on speed and not on some birocrats and showing them instead of 88 an 90 score here are a few tips for you:

-magento 1.9.2 is not made for php 7 ,you won`t see no performance increase as the software is not made for php 7,and is like having an car witch you can drive with 300km/h,but you don`t have an road,you have an country road.
-go and move right the way to magento 2 and you will see an 25% increase on performance.
-Use php 7.0.2–7.0.6 except for 7.0.5 (supported by Magento version 2.0.1 and later only)
-magento 2 with php7 process 135k more orders per hour
-Full-page caching built into the platform means pages load a lot faster,1-2 seconds compared to the 5-10 seconds for non-caching pages.It can also better handle many catalog pages without slowing down.This makes it scalable for large stores and able to grow with an online business.
-implement engintron
-as your website is an store with dynamic content,you can also implement in magento 2 as it`s out of the box dynamic cdn,notice that cloudflare can do more harm then good if setup incorectly,and cloudflare only works on the static file,it does not work dynamic for that in engintron you have an magic feature,that 1 second micro cache,that @fevangelou mentioned in other post,that helps alot.
-concentrate on the speed for real,not on some dumb numbers from tools that might not help you.

The page speed improvements with the release of HTTP 2.0 ,alot of them today,can do more harm then good.Browsers are now modern can handle multiple conections,things are moving faster nowdays,even if you just sit and watch.

There is a known PHP issue that affects Magento code compiler when using PHP 7.0.5.I recommend you not use PHP 7.0.5; instead, use PHP 7.0.2–7.0.4 or 7.0.6.

On the side of the speed,you can contact @fev i`m sure he can help you if you need commercially help.

p.s:Only if you do what i tolded you and use engintron,you might see an real increase of more then 50% on the speed level,if you do more then that the results might be even more amazing.
Concentrate on the SPEED not on what BIROCRATS says,because they are not up to date with the things,at least not on this field!

**Comment by natedesigns** [comment]
@laurfx thanks for this. This is actually what we did in the end, and should have reported back here for others to benefit. We're using it very lightly but it adds good benefit. I hope this link helps others as took me a while to find: https://www.webhostinghero.com/whm-mod-pagespeed-installation/

@masteranalyze thanks for the many suggestions, the time spent in this reply and the thought. I will take this onboard. However, I cannot help but feel both yourself and @fevangelou have taken my approach with slight offence and annoyance - perhaps rightly so, as I can see your point of view. 

Birocracy does not just come from those above us developers in the form of project managers, analysts, managers, business owners etc but those who are not technologically adept. Take a guy who's just paid for a website, he might not know relatively if it's any good. Pagespeed can offer a good way to gauge how good it is, and to an extent how good google thinks it is. 

I'm not saying that this is the ONLY measure of speed. That's too much to go into on a single thread (though I admit @masteranalyze you've given it a darn good going 👍 ). 

Our particular Magento install through modules and the theme itself has been modified and extended so much that for now, Magento 2 would be a massive undertaking, and quite possibly without reward (https://blog.amasty.com/magento-1-vs-magento-2-performance-comparison-speed-test-results/). Tools like Engintron have given us a massive benefit with control (thanks @fevangelou).

Yes, quite right with PHP7, tried and too many modules required upgrading. Though, the reason I wanted to try it was due to reading about a few people have good results (cannot find any citings for this). 

https://developers.google.com/speed/pagespeed/service/faq
Yes that's correct, i did read about this, but I'm not using google to host, just simply their mod_pagespeed (apache module - thanks again @laurfx) which allows you to remove whitespace / concatenate js css etc. YES, this is stuff which if done correctly in Magento, any CMS or static HTML page could be avoided, but it adds very good benefits if the time/cost to correct from source outweighs the financial gain.

We actually got as much out of the single server, as we felt possible, in the time for the project through (in a nutshell):
Request > Cloudflare > Engintron >  Redis (session caching) / mod_pagespeed > apache >> Magento with FPC by Mirasvit

However, after lots of siege testing we did not feel that the single server would offer us enough scalability for times when our traffic peaks - offers etc. 
Through work with our hosting company we've actually gone with 4 of the servers mentioned previously with a hardware firewall / load balancer as:
LB >> Server >> Nginx(Reverse Proxy - Engingtron) >> Apache (mod_Pagespeed) >> Apache >> 
PHP Opcache && Memcache >> ( OPcache is for accelerating code access. memcached is for accelerating data access. ) >> Magento FPC Mirasvit & Redis (Sessions) >> Application(PHP)

We are just in the final process of trying to see if varnish can help even more. It's such a pain to setup, but tests suggest it takes the homepage load from around 0.020 (cache hit) down to 0.014. but more.. takes a siege result of around 350 transactions per second up to around 450. The throughput and other indicators increased massively too. 

Hence, we are using Turpentine with Varnish, but it's causing a few errors at the moment. It's just getting the caching policy right. (https://github.com/nexcess/magento-turpentine)

We're getting there.

-----

nb. Must say, without lessening the advice and time @masteranalyze has spent I cannot help but state that parts of the reply I cannot help but feel belittled,

Be it my OCD wanting to get from 88-90, or this actually being a valuable measurable increase in speed, regardless of Pagespeed. It should be the job of those with more experience and ability to inform, not judge. In actual fact adding Pagespeed didn't really increase score at all, but measurably increase load-time in our case.

**Comment by masteranalyze** [comment]
" In actual fact adding Pagespeed didn't really increase score at all, but measurably increase load-time in our case."

You get the point,that is why you always should test,you seem to have an big development on your side,and big stores requires lots of work,testing and so on.

"Birocracy does not just come from those above us developers in the form of project managers, analysts, managers, business owners etc but those who are not technologically adept. Take a guy who's just paid for a website, he might not know relatively if it's any good. Pagespeed can offer a good way to gauge how good it is, and to an extent how good google thinks it is. "

Why do  you think google drop out that service?They dropped out,because actually things gone further,i fully agree with you that somebody who paid for an website does not know if it`s any good,some of them even don`t know what they want,but that is there problem,same way gtmetrix or pingdom or other tools like you mentioned is good for testing,if they don`t know things,educate them,show them,explain them that those tools are not used anymore not even by GOOGLE itself,explain to them Flash does not make sense in HTML5 era,you have to do that,don`t count on them to know this stuff.
And to give you an hand of help,ask them,when they go to an Dental Care office,with an medical person who studied 10-15 years to make your dents look nice and clean,do you teach the medical staff what they have to do ?Or do they teach you and explain you what you have in order things to go smoothly?

I guess this make sense to you.

In Web Services is practically the same.You have to educate them to explain them.

If the webstore is the like of Amazon or Ebay like or Alibaba,you need alot of people involved,you can`t do all by yourself,nobody can.

p.s: Magento 2 would be a massive undertaking, and quite possibly without reward  - do an separate cpanel,migrate stuff,i know migration can be an pain of the ass,but if they are so big,the migration might make alot of difference,and plan it,you don`t have to do it in 1 day,you plan it,develop,move stuff,and when is ready,just move on things to the FUTURE!
Maybe the reward won`t be immediately,but it will certainly be in the future,but if the store is big,it can indeed needs alot of work.

**Comment by fevangelou** [comment]
@natedesigns I can understand why you'd want mod_pagespeed with Nginx and I surely was not offended or anything. However I do have a simple rule for Engintron to be as easy as possible to work with. That means it should not modify the HTML output of any website. Should anyone want to include it with their cPanel build, I guess it's easier to follow @laurfx 's advise and install it on your own.

My point is that if you're gonna go the mod_pagespeed way, you might as well build a highly optimized server stack with Ubuntu Server and Varnish, Nginx & PHP5-FPM, without using cPanel. The optimization there would be much higher as you control many more things that cPanel prevents you from.

**Comment by masteranalyze** [comment]
We consider this solved as @laurfx already did provide solution for his case.

Always welcome @natedesigns to write back your tests and results and share,in order to improve stuff,but i can`t agree more with @fev ,things should be as simple as possible and stable.

And things like page speed witch is working and can be installed via EA4,we don`t need to reinvent the water,to take the benefits.

p.s:Some date 4 @natedesigns  I justed test one dev site i have done with Joomla,php 5.6 ,no cache,no engintron,no optimization done and no follow up of the rules of yslow or page speed,page size:2.18 mb,pagespeed E(56 %),yslow d (69%) ,first time testing 5.5 seconds.Follow the waterfall ,i noticed an delay of 3 seconds from stupid facebook external source,more exactly share facebook buttons and like button,witch was the single on that i did have there,i removed them,now it`s loading in 2.5 seconds with no cache no optimization no nothing,and it can improved to 2.0 seconds,as one font an png,is causing 0.5 seconds delay,now if i make and setup everything and optimize,certainly the score will be even more down,but i don`t care about yslow or pagespeed,i care if it`s loading or not fast,and you can measure that,and concentrate on speed and on what works on your side.It depends from case to case.
Just wanted to give you an example,that you can have an pretty fast website with very bad pagespeed or yslow score.

**Comment by fevangelou** [comment]
Closing as resolved.

**Comment by hubertus2017** [comment]
Hello,
just fyi if you are looking for the final solution: After 2 years of testing and speed optimising, including varnish and eningtron, we finally found the formula for Magento 2.3:

- **simply** get the fastest dedicated webserver available
- **simply** serve with apache 2.4
- mod_pagespeed

Thats it, 99/100 sitespeed in google. ...and the two running stores are heavily customized.

Varnish and eningtron did not help us and adds only unnecessary complexity.

hub

**Comment by fevangelou** [comment]
Getting a fast dedi probably made a difference for sure. But even so, it won't hold up to sudden traffic spikes. I can guarantee you that.

And for the record, Pagespeed measures client side performance, not server-side performance. It's the last part that's important in such scenarios.
