### ISSUE TITLE
Engintron breaking cPanel Wordpress Tools

### ISSUE THREAD

**Issue by neunotion** [engintron/engintron#1442]
Dear all,
We've been facing an issue recently where enabling engintron breaks Wordpress Tools when you login to cPanel via the url:
cpanel.domain.com.
If you login via the port "domain.com:2083", it works fine. Anyone faced this issue? We had to disable Engintron on our servers for the time being till the problem is resolved.
Thank you.

**Comment by arthur-lbchn** [comment]
hey, we're facing the same issue. could someone please review?

**Comment by fevangelou** [comment]
The issue is not with Engintron per se, but how the proxying is done internally by cPanel. Engintron simply passes the traffic to the backend server (cPanel), but that server was obviously not built to handle traffic from a proxy and as such some URLs may contain the proxied port, which breaks requests. This has been around for ages to be honest, but it's not something I can do to resolve as it's not an Engintron issue in the first place - it's just how the cPanel backend works when you use cpanel.*, whm.* etc. subdomains.
