### ISSUE TITLE
awstats, stats in general

### ISSUE THREAD

**Issue by Tragidy** [engintron/engintron#169]
Greetings,

I have found that your script has made no changes to any of the cpanel log parser such as awstats to have it show the visitors ip as opposed to displaying the servers ip as it does right now, is there any solution or modifications that can be made to the way awstats is handling the ips from nginx?

**Comment by whosjose** [comment]
#146 There's a fix there but @fevangelou stated that it's suppose to work out of the box.

**Comment by Tragidy** [comment]
Thanks @whosjose I also thought the notes states it was working across all of cpanel which is pretty much is for the most part but awstats certainly does have an issue, perhaps there is a logformat that can be used here?

**Comment by whosjose** [comment]
@Tragidy I don't think it has anything to do with the logformat.

**Comment by kuteninja** [comment]
Hello, I'm having the same issue, I've tried to install mod_remoteip manually with these instructions: https://documentation.cpanel.net/display/EA/Custom+Modules although it didn't changed the issue, the domlogs are still appearing with the server's IP address, despite the X-Real-IP header

I think that you should think of a way to disable Apache access_logs and override those with Nginx access logs using the same custom_format, so that AwStats takes the information from Nginx, and thus it will also count the 304, and cached pageviews instead of only the forwarded ones.

**Comment by fevangelou** [comment]
Engintron installs Nginx and patches Apache's log processing to allow mod_remoteip (also installed by Engintron) to pass the right IP from Nginx to Apache. As someone else has pointed though, this is not enough for AWStats and similar tools as they use their own configurations which is really beyond the scope of what I'm providing with Engintron. Beyond sysadmins, regular end users won't understand a thing if it's not Google Analytics ;)

If you wish to dig deeper and provide insights, I have no issue adjusting the installer to make the whole setup compatible with AWStats and the other stats programs used by cPanel.

**Comment by Xeexer** [comment]
Hello I have just installed this addon to test it out and while it seems good this was the first issue i encountered I attempted changing some settings including the log format to no avail, very strange issue. 

It appears in the post above the author stated here they have no intention of fixing this i assume which is totally fine its his/her addon to cpanel, but you could at least provide a new log location for the end users to make manual adjustments to log parsers to the nginx log file instead of the chip on shoulder attitude and so fourth.

Simple solution for me after attempting various changes to the logging systems

As a solution i suggest using nginxcp as it does work and has no issues with real ip or logging parser out of the box, sadly i would have liked to endorse this addon instead of the aforementioned one but it appears this one wont be fixed.

**Comment by fevangelou** [comment]
@Xeexer If it works for nginxcp (which does no beneficial proxying by the way) or you already have the solution, why not share it with the rest of us instead of making ironic remarks?

**Comment by Xeexer** [comment]
Hello @fevangelou I am sorry if you take this personal and that you feel you need to announce what a user know or not, thanks for this if this is the type support where you belittle the one reporting on problems in your very system.

I can't help that this somehow upset you and that you feel you need to attack me or the addon I simply mentioned no worries I simply wont use your product as you react poorly. Good luck with your project I certainly hope others dont get treated like they don't know what they are saying overall since you are god.

-
Steve

**Comment by fevangelou** [comment]
@Xeexer Right... Instead of writing short novels though, you could have provided a solution so far. But I guess I was spot on in the first place.

**Comment by kuteninja** [comment]
Sorry for reopening this issue, I don't mean to offend you nor to follow the previous drama; but, given the fact that you're the more idoneous person to modify the plugin, and my customers are in need of a free and simple analytics solution included with their hosting account (in this case AwStats), I'd like you to try and reconsider finding a solution or a workaround on the subject.

I'd really love to use Engintron on all our servers but I can't disable all our analytics software in exchange for that. I'm sure that it's not quite an easy thing to do, and you may choose not to since it's a free plugin after all but, again, please try to see if there would be any way to get this fixed on a future release.
