### ISSUE TITLE
First Byte/Wait time issue

### ISSUE THREAD

**Issue by mahipalsingh278** [engintron/engintron#172]
Hi,
Please let me know if engintron extension can help to reduce wait time issue on the server. The store (based on X-cart) is showing 600 to 900 MS wait time. 

Thanks
Mahipal

**Comment by fevangelou** [comment]
Make sure Apache is optimized - see here: https://github.com/engintron/engintron/wiki/09.-Beyond-Engintron:-Optimizing-Apache

Check again after that.

**Comment by mahipalsingh278** [comment]
Hi,

Thanks for the quick response. I have made the suggested changes in Apache configuration but the results are still same. On the server side we have Apache 2.4 with PHP 5.6 FastCGI mode and zend opcache enabled. You can check the results below

https://tools.pingdom.com/#!/eb5Eaz/http://www.angelicdiamonds.com/engagement-rings/9k-white-gold

Thanks
Mahipal

**Comment by fevangelou** [comment]
Did you restart both Apache and Nginx?

**Comment by mahipalsingh278** [comment]
Yes, I have restarted both.

**Comment by fevangelou** [comment]
OK. Although first byte load time isn't bad (it depends on networking, server's location etc.) what you can do is strip any cookies from the static files. To achieve this, edit the "proxy_params_static" file via Engintron's WHM app and at the end of the file add the following 2 lines:

```
proxy_hide_header			Set-Cookie;
proxy_set_header			Cookie "";
```

Restart both Apache & Nginx and run the speed test again. Make sure you select a location close to your server (Sweden, since it's closer to the UK where your server seems to be).

Let me know.

**Comment by mahipalsingh278** [comment]
I have made the suggested changes and restarted Apache and Nginx but the results are still same.

Thanks
Mahipal

**Comment by fevangelou** [comment]
Better have a look here: https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.angelicdiamonds.com%2Fengagement-rings%2F9k-white-gold&tab=desktop

Your site is pretty fast already.

If you're worried about the ~1 sec initial load time for the first byte, like I said, this is related to many factors which you don't necessarily have control over.

**Comment by mahipalsingh278** [comment]
Thanks, I will follow up further with X-cart support. I really appreciate your kind support on this issue.

Best Regards,
Mahipal

**Comment by masteranalyze** [comment]
Increasing Speed,Reducing Time to First Byte is one of reason to take care for elgg and It is a motive because elgg goes slow. Basically the advice is moving to a better/faster server that because time to first byte is the time it takes the server to start sending the data.
So we can think to reduce TTFB following these advices:
Move your website to a faster/better server
Use a CDN or something similar to reduce the load on the server (repeated requests to a server will increase the TTFB)
Reduce the time the server spends processing the request for information.

But a lot of us are not really prepared to move servers, and change the way our server worked and in any case a lot of us use a hosted server so no control on them.So what can we do?

Reduce System_Log: Find if your system_log table is too big and reducing it can be an advice. TTFB depends on how many big is our database so plugins like logrotate and garbagecollector can be very useful but they need a little more support to install and configure it. I saw the time to first byte on the first call on a simple index has gone from 1,2s or more to 600/800ms. It is still a lot time. A good site must have a TTFB around 250ms.

**Comment by mahipalsingh278** [comment]
Hi,

Thanks for the suggestions. The site is hosted on a dedicated box with Ukfast and having 32GB of RAM and Quadcore CPU (Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz). I have even tried to setup a new box with OVH same configuration with Nginx, PHP-FPM and PHP-FastCGI as suggested by X-Cart but the results were same.

Thanks
Mahipal

**Comment by fevangelou** [comment]
Then it's a matter of networking. Again, my personal opinion is that your site is very fast. If you'd like to speed it up a little more, you can always use CloudFlare ;)
