### ISSUE TITLE
' engintron_temp' reaching absurdly high sizes?

### ISSUE THREAD

**Issue by Sovjohn** [engintron/engintron#193]
Hello,

We are using engintron on a server with quite satisfying results for the past few months. Because this server has lately been used for development purposes, we have temporarily disabled engintron since about a week now.

However, today the developers alerted me about the server having disk space issues, and lo and behold, it appears that 'engintron_temp' had reached absurdly high filesizes in 1-2 instances. Namely, for a server whose entire /home/ directory is less than 15 GB in size, 'engintron_temp' reached over 400 GB for some reason. It has now dropped to approx. 105 GB which is still absurdly high, just somewhat less so.

I don't know what engintron_temp holds exactly, and ofcourse I don't know why it might ever reach such absurdly high sizes. I've checked in the configuration and I suppose I can set limits to this folder, like similar limits do exist for the dynamic and static folders.

That being said, what could have caused this? And with engintron disabled nonetheless! (To be fair, nginx was probably left running from what I saw, despite engintron reporting itself as disabled in the status page).

Thanks in advance for any info about this!

**Comment by fevangelou** [comment]
These are cache files which are regularly flushed by Nginx itself. The number you report is indeed very high, although limits to the cache already exist. So basically this shouldn't happen and I haven't seen this before. Maybe there are special circumstances which caused this but it's very difficult to troubleshoot without accessing your server.

For the record, when Engintron is disabled, Nginx switches to port 8080 and essentially sits idle doing nothing, consuming nearly zero resources. So my guess is that something else is wrong with your setup.

If you can shed any additional light, maybe you could help me troubleshoot this for you.

**Comment by Sovjohn** [comment]
Dear Fotis,

First of all, allow me to extend my kudos for both engintron and the support / clarity provided in documentation and github.

If this phenomenon is indeed unique as far as you know, then it might be beneficial to establish what exactly might have caused it. The server in question steadily reports 105GB in use by engintron_temp with nginx service stopped. I haven't flushed that yet because I'm quite curious on what caused it indeed. Previous numbers were 400 and (I believe) 250 or so GB with nginx service running.

I can arrange to send you a temporary password with su privileges which would allow you to investigate thoroughly; we just need to agree on a suitable timeframe for that. Should I e-mail you somewhere and leave this thread alone?

Thanks,

Yannis

**Comment by fevangelou** [comment]
You can send temp su credentials at engintron [at] gmail [dot] com.

**Comment by speegs** [comment]
I have a theory.  When Engintron is disabled mode seems to become an open proxy.  I disabled Engintron so a web developer could get speedy updates to javascripts and css.  He noticed they were not updating.

Two days later, I noticed the server load was massive and things like this in the access logs:

223.155.227.219 - - [09/Jul/2016:20:30:49 +1000] "POST http://cgi.find.qq.com/qqfind/buddy/search_v3 HTTP/1.1" 499 0 "http://cgi.find.qq.com/qqfind/buddy/search_v3" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0)"
222.186.12.35 - - [09/Jul/2016:20:30:50 +1000] "POST http://cgi.find.qq.com/qqfind/buddy/search_v3 HTTP/1.1" 499 0 "http://cgi.find.qq.com/qqfind/buddy/search_v3" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0)"
From best I get tell some bot has found Nginx and has decided to use it as an open proxy server.

I turned Engintron back on and it seems the load has dropped along with the massive amounts of network traffic.

The apache logs are delivering now heaps of 404s for urls that are still being attempted via whatever proxy clients are hitting up the server IP.

I'm thinking this is a big flaw if by default it turns on an open proxy when not in enabled mode.

**Comment by fevangelou** [comment]
@speegs it's not an open proxy in any case. Your server's IP was probably used by other domains in the past and DNS leftovers in these domains still point to your server. However because these domains are simply not defined in Apache, they silently fail to resolve. If you installed Engintron before Mar 22, simply upgrade it and you'll get a 7 day log rotation in Nginx, so your logs don't grow big.

**Comment by speegs** [comment]
Looks like I installed on Jun 25 2016 (date I downloaded the script).  So updating will be of no assistance.

![image](https://cloud.githubusercontent.com/assets/16222245/16722120/e6b06006-4787-11e6-9ea6-34874f4f91a2.png)

Maybe unrelated to the original problem here, but I saw some similar symptoms.  I turned engintron off at the request of a web designer. Huge spike in traffic, cpu and disk as well.  I got an email saying my data quota was being hammered (it was).  Turned engintron back on and fixed it, sending 404s to those proxy attackers.

Still seeing many thousands of errors in my apache log, if I firewall the IP address from connecting to port 8080.  They drop off future logs.

There is some kind of way I was exploited as an open proxy kind of way with Engintron is disable mode.  Very default install, pretty new Centos 6 cpanel server.

Currently 1 website, so I think there is a problem.  Cpanel was setup with an image from VPS company Vultr, I didn't do it by hand, but looks pretty standard.  Hope that helps someone, I'm 99.99% confident engintron caused the issue, because it's the only thing I did different to other websites I host.  It's a good program engintron with a sound idea, I just think I hit some kind of bug and I'm not smart enough to know exactly what yet.

Good news is turning engintron back on, seemed to instantly rectify the problem even though my server is most likely on some world wide open proxy list right now.  With engintron on it's just sending out 404s and hopefully they will give up.  With engintron in disabled mode looked to be an open proxy to me due to the traffic and cpu loads.

If you have any advice on what to check let me know.  I'm not keen to ever turn engintron off at least not for the moment as I'm at 85% of my data quota and I need to last the rest of the month.

Examples in Access Log with Engintron on, Bad request (there are thousands):

5.163.113.163 - - [11/Jul/2016:15:35:52 +1000] "GET http://static.sdstream.ru/452a4284c53b56d101068b2b556909d1 HTTP/1.0" 404 324 "-" "Opera/5.0 (Windows; Windows NT 7.2; en-US) like Gecko Chrome/35.6.297.036 Safari/643.69"

Examples in Access Log with Engintron on, Good request:

110.175.112.34 - - [11/Jul/2016:14:11:04 +1000] "GET / HTTP/1.1" 200 14263 "correct referrer hidden" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"

Stuff I'm seeing in the errorlog with Engintron on:

2016/07/11 04:46:11 [error] 2590#2590: *6900 connect() failed (111: Connection refused) while connecting to upstream, client: 185.25.151.159, server: localhost, request: "GET http://testp3.pospr.waw.pl/testproxy.php HTTP/1.1", upstream: "http://188.116.32.7:8080/testproxy.php", host: "testp3.pospr.waw.pl"

Sorry I might only be giving you about 80% of the information required to see the problem.  I'm brand new to Engintron and nginx so I'm a beginner at the moment.  I didn't get fancy, I just followed the instructions 01 - 11. as accurately as I could off the Engintron website.  Including those listed here:
https://github.com/engintron/engintron/wiki

Seemed like a good formula, but something went wrong (only when I used the option to disable engintron).  I went googling answers and ended up here.  Oh and mysql bombed, but the instructions told me that might happen, the instructions in the documentation on how to fix it worked thank you :)

**Comment by highacid** [comment]
I have the same issue, noticed it after upgrading to cpanel 58. not only that my access_log increased to 6 GB in few hours
my temp that until nowadays was always 0 today was taking all free space on server, almost killed my services...

**Comment by highacid** [comment]
And the funny thing is that I disabled engintron yet it continues to cache... 
Nginx Cache/Temp Disk Usage:
381M	/tmp/engintron_dynamic
23M	/tmp/engintron_static
440M	/tmp/engintron_temp

and growing...

**Comment by speegs** [comment]
a guess, but maybe an update caused the issue and another update corrected it..  I'm seeing a stable server now:

Nginx Cache/Temp Disk Usage:
17M	/tmp/engintron_dynamic
17M	/tmp/engintron_static
20K	/tmp/engintron_temp

With still people attempt proxy connections, I just block IPs of the bad ones seems crazy for someone to have 751 connections to my brand new website.  I also have ConfigServer Firewall.  Which makes it easy to block ips and set a time limit on them to unblock later.

    17 95.170.239.143
     75 82.25.207.0
    751 75.74.5.190
$ netstat -an | grep :80 | wc -l

883 total concurrent connections

**Comment by highacid** [comment]
Got it

**Comment by speegs** [comment]
netstat -anp | grep :80 | awk '{print $5}' | cut -d: -f1 | sort | uniq -c | sort -n

Or Current Connections in the panel on WHM

**Comment by speegs** [comment]
Decided to add a firewall rule blocking all access to 8080 except from the server itself.  Seems to have been the missing thing I needed that I didn't see on the documentation.  I hope that's the right thing to do :)

8 total concurrent connections after doing that.

It might not have been an open proxy,  The internet was trying to treat port 8080 as one and it was receiving over 500mbit+ of traffic at times when engintron was in disable mode.  Guess that could fill logs/disks quickly.

I'm surprised the server didn't crash and I hope it helps someone else, but please be careful if you add firewall rules you can always lock yourself out of your server if making a mistake.  So make sure you have console access.

![image](https://cloud.githubusercontent.com/assets/16222245/16811212/9da18504-496a-11e6-83f2-3553cf1e6320.png)

**Comment by highacid** [comment]
@speegs Can you tell me what rule you added and if it is in CSF LFD let me know steps to add same rule please.

**Comment by speegs** [comment]
Assuming y.y.y.y is your servers main IP.  Not sure if the allow is required, but figured it was safer to add it in :)

Add to csf.allow:

tcp|in|d=8080|s=y.y.y.y # Your Server IP
tcp|in|d=8080|s=127.0.0.1 # Loopback Address

Add to csf.deny:

tcp|in|d=8080|s=0.0.0.0/0 # Block all connections to port 8080 except those already allowed

That's what I did.  Didn't see it mentioned in the instructions.  Just seemed like a good idea after reading quite a lot of posts here to try that and watch the logs.

Happy to report the server is not fighting off millions of requests and the clearest evidence of victory is this:

$ netstat -an | grep :80 | wc -l
5 total concurrent connections

My cpanel server is pretty new so clearly that is what I'd expect with 1 website, also just launched so traffic building.  Not sure if the author is watching but might be something missing from the instructions I tried to follow closely (I hope I didn't miss that in the instructions).

**Comment by highacid** [comment]
@speegs thanks for your inputs

**Comment by fevangelou** [comment]
@speegs Glad you sorted this out. What really occurred as you can understand is leftover traffic on port 8080 hitting your server, so using CSF to restrict access only internally was the only way to resolve this. I hope you don't mind if I make this an article in the wiki :)

**Comment by fevangelou** [comment]
@speegs Forgot to mention that your server cannot be turned to an open proxy. You're confusing it with incoming traffic from leftovers sources in both ports 80 and 8080. The server was overloaded when you had Engintron off, as Apache responded on port 80 - very reasonable, that's why I made Engintron in the first place. Nginx on the other hand was switched to port 8080 and active but all it did was respond to traffic sent to port 8080. Nothing suspicious here. When you turned Engintron back on, Nginx would handle traffic on port 80 (thus reducing overall load as most traffic was sent there) and Apache would switch to port 8080, but obviously still receive the traffic sent to that port, as Nginx did when Engintron was disabled.

The explanation is simple really. The IP you got could have been used for some free/open service in the past, that's why it was pinged so much. But that doesn't mean your server is now an open proxy. And the fact that you have Nginx in front of Apache only made things better, not worse. Depending on the amount of traffic you had, it may have been normal to have Nginx cache sizes reaching the predefined limits of around 1GB.

So of course the right thing for you would be to just set a CSF rule and confine access to 8080 from localhost only.
