### ISSUE TITLE
Site Visitors Logging Fails After engintron Install....

### ISSUE THREAD

**Issue by genesteinberg** [engintron/engintron#236]
Since installing version 1.7 of engintron, AWStats' daily logging of site visitors has essentially stopped. Instead of seeing numbers in the five figures on our largest sites, it's down to just a handful.

I used a previous nginix plugin, cpnginx (definitely not recommended) for a brief trial, and ran into the same problem. They blamed CloudFlare, but you say it has noting to do with it.

It is a cause and effect matter, however. Installation of one of these plugins cripples the user counting (page views appear to work properly). Removal restores normal operation.

My cPanel server has PHP-FPM, EasyApache 4, PHP 7.0.9, etc.

Peace,
Gene

**Comment by fevangelou** [comment]
In one of your site behind CloudFlare, create a simple php file called ip.php and paste this in:
```
<?php echo $_SERVER["REMOTE_ADDR"]; ?>
```

Now visit that file, e.g. at domain.tld/ip.php and note down the IP.

Now visit: https://ifconfig.co

Do the IPs match for you?

**Comment by genesteinberg** [comment]
Both correctly show my IP address when I go online.

But what does that have to do with AW Stats failing?

Peace,
Gene

**Comment by genesteinberg** [comment]
From the admin:

Hello Gene,

The required mod_remoteip module is already enabled on the server but the domain access logs are still showing server IP address instead on client visitor IP address.

root@server [/home/theparac/access-logs]# httpd -M | grep remote
remoteip_module (shared)

Please discuss this issue with this plugin provider.

**Comment by genesteinberg** [comment]
To confirm, my admin wrote that they followed all the steps in the following with no success:

https://github.com/engintron/engintron/issues/216#issuecomment-240327126%3E

Ideas?

Peace,
Gene

**Comment by genesteinberg** [comment]
One more thing: A little online sleuthing indicates this is a common problem. So why are the solutions so hit and miss?

Peace,
Gene

**Comment by fevangelou** [comment]
The problem seems to be with AWStats specifically when trying to log visitor data passed from a proxy to Apache. I recommend reverting the changes in your httpd.conf file.

Until I debug how AWStats can be adapted to work with proxies (again, not an issue specific to Nginx/Apache only), you have 2 options. Either uninstall Engintron (or disable it) to restore AWstats logging (stats that make little sense to users, more to developers) or keep Engintron and enjoy the benefits of a better performing server and faster site loading times.

**Comment by genesteinberg** [comment]
This appears to be a common and known issue. 

I'll reinstall when you devise a workable solution. 

Thanks. 

Gene

**Comment by fevangelou** [comment]
Common issue for AWStats you mean...

**Comment by edibarboza** [comment]
I have the same problem with Awstats, then I installed Engintron. I still keep using Engintron because it is an excellent plugin, but the owner should create a solution, to work with Awstats, rather than criticize. It would be of an absolute magnitude, if @fevangelou would look at itself and create this solution, because Engintron is already the best, but it can evolve.
