### ISSUE TITLE
Cookies or sessions disaster...

### ISSUE THREAD

**Issue by reficul** [engintron/engintron#237]
I really love this plugin for cpanel, installation is easy, the panel is really good and all going well but after some hours many users of my forums (IPB) tell me that on every page load they log automatically with other user names, practically I do not know what was going on but the user x became y. This clearly caused serious problems and with absolute regret that I had to disable and then uninstall engintron ... I hope to be able to reuse it in the future.

**Comment by fevangelou** [comment]
There is a 1 sec micro-cache, that's why some users could have seen another cached page. It doesn't stick though. But if you have a lot of user this can indeed be an issue that freaks out users.

What you can do is apply some IPB specific rules to switch off this micro-cache for logged in users.

Googling around I found that IPB sets a cookie called "member_id" with a positive value for logged in users. If you want to test it out, re-install/re-enable Engintron and update the file proxy_params_dynamic with the contents of this:

https://gist.github.com/fevangelou/764f49cabccc9e32c601690abdf1dc18

Then restart Apache & Nginx.

You can fine-tune that even more by applying exclusions e.g. for the login page your members use to sign in. But for me to help you on that you'll have to provide an actual URL.

**Comment by reficul** [comment]
Thanks for the help. 
I can't try anymore on my live forum, this is dangerous.
I try to setup a fresh new forum on other server to make this test.

Can you suggest me How can I try to replicate this issue in a empty forum?

**Comment by fevangelou** [comment]
As long as there's one user (you) you can test out if it works.

**Comment by reficul** [comment]
ok, but I think that the cookie "member_id" value is not a false/true value, but the id of the member logged.

**Comment by fevangelou** [comment]
If you read closely you'll see it's a regular expression matching any
number above zero, aka a logged in user.

**Comment by irwanwan** [comment]
@fevangelou i've done testing with your dev. code for proxy_params_dynamic and it's works for me. No longer user's switch.
But for proxy_params_static i still have to commenting out proxy_set_head line for my logged out problem.
Overall engintron works like charms, really love it. Thanks again for your hardwork here.

**Comment by fevangelou** [comment]
Which lines exactly do you still comment in proxy_params_static?

**Comment by irwanwan** [comment]
@fevangelou in proxy_params_static
This last line
#proxy_set_head   cookie" ";

Thanks

**Comment by fevangelou** [comment]
I think I'll remove that in v1.7.2 because I've only seen issues with it...

**Comment by irwanwan** [comment]
great, looking forward to it
this is OOT but I think engintron shouldn't use with mod_pagespeed, deactivated it would decreasing server and CPU load. IMHO with engintron installed you don't need mod_pagespeed anymore.
Thanks

**Comment by fevangelou** [comment]
@irwanwan there is no plan in adding mod_pagespeed support when you consider the benefits you get from a proper Nginx setup via Engintron. mod_pagespeed is not really needed :)
