### ISSUE TITLE
Unsecure CF-Connecting-IP

### ISSUE THREAD

**Issue by voron** [engintron/engintron#248]
It seems You use CF-Connecting-IP header as X-Real-IP without verification request came from CloudFlare IPs. This can be easily exploited. What do You think about checking like following instead of `if ($http_cf_connecting_ip) ` ?
```bash
geo $cloudflare {
    default 0;
    103.21.244.0/22 1;
    103.22.200.0/22 1;
    #all other IPs from https://www.cloudflare.com/ips-v4 and https://www.cloudflare.com/ips-v6
}
map $cloudflare $X_REAL_IP {
    1           $http_cf_connecting_ip;
    default     $remote_addr;
}
```

**Comment by fevangelou** [comment]
I doubt it's a security issue. Unless you fear a site on your server will
want to hack itself. If a domain does not already propagate to your server,
it will never reach Engintron's Nginx.

On Aug 27, 2016 23:47, "Alex Vorona" <notifications@github.com> wrote:

It seems You use CF-Connecting-IP header as X-Real-IP without verification
request came from CloudFlare IPs. This can be easily exploited. What do You
think about checking like following instead of if ($http_cf_connecting_ip) ?

geo $cloudflare {
    default 0;
    103.21.244.0/22 1;
    103.22.200.0/22 1;
    #all other IPs from https://www.cloudflare.com/ips-v4 and
https://www.cloudflare.com/ips-v6
}
map $cloudflare $X_REAL_IP {
    1           $http_cf_connecting_ip;
    default     $remote_addr;
}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/engintron/engintron/issues/248>, or mute the thread

**Comment by voron** [comment]
> I doubt it's a security issue. 
As I understand, You will use mod_rpaf/mod_realip2/etc  on Apache side and it will convert forged X-Real-IP into REMOTE_ADDR, which is used by IP ACLs.

**Comment by voron** [comment]
Why do You think nginx has set_real_ip_from directive? I do not see any set_real_ip_from in Engintron's source. You are just using CF-Connecting-IP header as X-Real-IP which in its turn transforms into Apache REMOTE_ADDR by mod_rpaf/mode_realip2/etc. It can be forged for example by `curl -HHost:example.com -HCF-Connecting-IP:1.2.3.4 http://server.ip.add.ress/admin.php` to get http://example.com/admin.php and Apache will see request came from IP 1.2.3.4 instead of attacker's IP.

**Comment by fevangelou** [comment]
Just tested what you said and I can't verify it works. I get a 400 error for bad request from Nginx and the IP recorded from the curl command is the actual IP and not the spoofed one. Additionally, since a 400 error is returned, Apache doesn't even see the request, let alone log it.

**Comment by fevangelou** [comment]
I take it back, it works, I had a typo in the Host header I used.

**Comment by fevangelou** [comment]
The only problem is that the geoip module is not included by default in Nginx's repo build and the approach I've followed for Engintron overall is to use the main repo and not build Nginx from source in order to be always up to date.

The only solution I can think of now is to disable the if statement that changes the "X-Real-IP" header to the value of "CF-Connecting-IP".

**Comment by fevangelou** [comment]
@voron It looks like the Nginx builds after 1.9.x now include the http_realip module which can be used to protect from this issue. I have updated Engintron to v1.7.2 with the new changes and you can test it out as well.

Thank you for reporting this problem and please accept my sincere apologies for not giving it the proper attention in the first place.

**Comment by voron** [comment]
Looks like now this problem should be resolved. Thank you.
