### ISSUE TITLE
Serve static content directly from nginx

### ISSUE THREAD

**Issue by beneddict** [engintron/engintron#255]
Hi, great cpanel plugin.
I have a question. Is it possible to serve static content directly from nginx without proxying back to apaache?

**Comment by fevangelou** [comment]
That's what Engintron does, but with a twist. In order to serve directly any file with Nginx, you need to define the system root path where Nginx will try to look for it. Since Nginx works like a blackbox in Engintron's scenario, essentially isolated from Apache, what it does is that it fetches static files from Apache (thus envoking Apache, but only once) and stores the files in its own cache, for 1 min. You can adjust this time of course (in proxy_params_static) if you want Nginx to cache static files and serve them directly without invoking Apache at all.

It's a tradeoff because otherwise Nginx would have to have detailed mappings of all domains and their paths on the disk, which basically kills the whole concept of Engintron for ease of use and no vhost synchronization between Nginx & Apache (which is the pain of ANY other Nginx plugin for cPanel)...

**Comment by beneddict** [comment]
Yeah, I see what you mean, thanks for your reply. 
So, I suppose I cann't put an exception for just one domain in the custom rules file to map the root folder, right?

**Comment by fevangelou** [comment]
You can but it's beyond the scope of the (free) support I provide here.

**Comment by beneddict** [comment]
Ok, thanks.
