### ISSUE TITLE
Real IP user

### ISSUE THREAD

**Issue by lucianozanita** [engintron/engintron#260]
Hello, I'm having trouble capturing the user's real IP through the $ _SERVER command and also by getenv.
On some sites not working in any way and this passing the server IP instead of the actual user ip.
How posos do to solve the problem?

**Comment by fevangelou** [comment]
It doesn't work on SOME sites but it works for others?

---

Regards,

Fotis Evangelou

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by lucianozanita** [comment]
yet all sites appears the server IP instead of the user .

**Comment by fevangelou** [comment]
Re-install Engintron and check again. You can re-install from within Engintron's WHM app.

**Comment by SashRaven** [comment]
There is an issue because of engintron changes apache log format.
As example, accessing site.com/realip.php returns correct cleint's ip, and access logs to apache domlog in this format:
servers.ip clients.ip access_request
Default format is:
clients.ip access_request
What the problem? Problem is in WHM, in web statistic application. "last visitors" look in apache log and take FIRST ip in it and show it as visitor. As result in our statistic ALL request were made from server's IP. But, I repeat, in web site we see correct IP.
Engintron shouldn't change apache log format.

**Comment by lucianozanita** [comment]
Thanks, resolved!
