### ISSUE TITLE
engintron nginx not detect mobile version

### ISSUE THREAD

**Issue by iLinux85** [engintron/engintron#267]
Hello

after installing Engintron nginx on centos cpanel server trying to check mobile friendly test tool in google showing the mobile interface same as desktop interface

this is the php code i use in my website to detect mobile or desktop version

```
if($_COOKIE['detect_mobiles'] == 1)
{
    $settings['template'] = 'smartphone';

}elseif($_COOKIE['detect_mobiles'] == 2)
{

}else{

if(preg_match("/(android|avantgo|blackberry|bolt|boost|cricket|docomo|fone|hiptop|mini|mobi|palm|phone|pie|tablet|up\.browser|up\.link|webos|wos)/i", $_SERVER["HTTP_USER_AGENT"])){
               $settings['template'] = 'smartphone';


        setcookie('detect_mobiles','1',time()+(60200),'/');
        setcookie('detect_mobiles2','3',time()+(60200),'/');

    }else
    {

        setcookie('detect_mobiles','2',time()+(60200),'/');

    }
}
```

after disable Engintron nginx i got mobile interface works normally. What settings in Engintron nginx deny me from open this website mobile version?

**Comment by brinsleyparagao** [comment]
Try disable 1 second microcache ! if persists its necessary adjust another config.

**Comment by fevangelou** [comment]
@iLinux85 As @brinsleyparagao mentioned, comment out the inclusion of proxy_params_dynamic in default.conf to remove the 1s micro-cache and then restart Apache/Nginx.

As a sidenote, it's best to do browser detection client-side and not server-side (as you do with PHP) to avoid such issues. That's because when a cache copy is created on the server for a page, subsequent requests for that given page will not re-request the page from Apache. If you do the detection client-side, you can bypass such issues. You would face this issue if you tried Varnish or any other reverse caching proxy as well.

**Comment by fevangelou** [comment]
Since v1.7.3, caching has changed to also detect mobile browsers.
