### ISSUE TITLE
Engintron memory cache?

### ISSUE THREAD

**Issue by laurfx** [engintron/engintron#272]
Hello,

How i can improve the size of cache or gzip just for a site (vhost) or is there any way to put the cache in RAM memory?

Also, you will add the my.cnf for MariaDB? Now the MariaDB have a /my.cnf.d/ folder where have multiple .cnf for every block.

Thanks.

**Comment by revcomllc** [comment]
I am also wondering the same thing for MariaDB

**Comment by brinsleyparagao** [comment]
Hello, in mariadb 10.1 i use this mycnf to max peform and minumum cosum

```
[mysqld]
local-infile=0
max_connections = 512
max_user_connections=64
key_buffer_size = 512M
myisam_sort_buffer_size = 64M
read_buffer_size = 1M
table_open_cache = 5000
thread_cache_size = 256
wait_timeout = 30
connect_timeout = 15
tmp_table_size = 64M
max_heap_table_size = 128M
max_allowed_packet = 64M
net_buffer_length = 16384
max_connect_errors = 16
concurrent_insert = 2
read_rnd_buffer_size = 16M
bulk_insert_buffer_size = 8M
query_cache_limit = 4M
query_cache_size = 512M
query_cache_type = 1
query_prealloc_size = 262144
query_alloc_block_size = 65535
transaction_alloc_block_size = 8192
transaction_prealloc_size = 4096
max_write_lock_count = 8
slow_query_log
log-error
external-locking=FALSE
open_files_limit=32768

[mysqld_safe]

[mysqldump]
quick
max_allowed_packet = 16M

[isamchk]
key_buffer = 384M
sort_buffer = 384M
read_buffer = 256M
write_buffer = 256M

[myisamchk]
key_buffer = 384M
sort_buffer = 384M
read_buffer = 256M
write_buffer = 256M

#### Per connection configuration ####
sort_buffer_size = 1M
join_buffer_size = 1M
thread_stack = 192K
```

**Comment by fevangelou** [comment]
It doesn't matter that MariaDB can use multiple configuration files. It's important that the main my.cnf calls these files. The configuration I provide does not call any additional files and it supports both MySQL and MariaSQL.

@brinsleyparagao your my.cnf has many, many problems which can kill a server. Additionally, there is no support for InnoDB. The configuration I provide was built with the help of Percona (the no.1 DB experts) and has been tested in very high-traffic environments and improved since 2010.
