### ISSUE TITLE
about using varnish with engintron

### ISSUE THREAD

**Issue by elbashaxyz** [engintron/engintron#276]
hello

first I am happy for using engintron its great easy plugin

but I want to ask i install engintron then install varnish as cache

but what the order is best engintron > varnish > apache
OR
Varnish > engintron > apache

my goal is engintron work as reserve proxy and varnish work as cache to get the best performance

thanks

**Comment by fevangelou** [comment]
Engintron's Nginx already provides you with caching. In fact, Nginx can do 1 sec caching which Varnish is not recommended for. This allows you to skip issues that would otherwise occur with sites with dynamic content and user generated content (forums, eshops etc.). Unless you have 1 site only, in which case, you can simply bump the caching time in Nginx (look at proxy_params_dynamic, change 1s instances to 1m or more) and it will behave as if you had Varnish installed.

**Comment by elbashaxyz** [comment]
hello

thanks alot for your response 

in this case "Unless you have 1 site only, in which case, you can simply bump the caching time in Nginx (look at proxy_params_dynamic, change 1s instances to 1m or more) and it will behave as if you had Varnish installed"

whats the order will be engintron > varnish or varnish > engintron?

thanks

**Comment by fevangelou** [comment]
Varnish in front of everything, Nginx follows and finally Apache.
