### ISSUE TITLE
Is there a EA4 profile, corresponding to engintron.dtd?   

### ISSUE THREAD

**Issue by hbarumba** [engintron/engintron#277]
New user of WHM and Engintron.
In the Engintron Wiki, on this page https://github.com/engintron/engintron/wiki/Beyond-Engintron:-cPanel-WHM-initial-optimal-setup to be precise, there's a file engintron.dtd recommended to be used.  
However,  afaik the .dtd file only works with Easy Apache 3 and earlier, and I only have EA4. 
Is there a corresponding EA 4 profile to use? If not, what would you recommend to do?

**Comment by gfxdesigner** [comment]
Hello,  
 Thank you for contacting me. I am out of the office and will be returning on Monday, September 26th. If I am unable to respond to your email during this time period, I will respond when I return to the office. Otherwise, if you need immediate assistance, then please open a support ticket by sending an email to support@gfxservices.com.

Russ Miller
GFX 
916.965.0450 Sales / Support
877.842.3369 Toll Free Fax   

Quick Links: Website  |  Support

**Comment by fevangelou** [comment]
The EA3 profile (I'll soon upload an EA4 version as well) is just to speed things up setting up Apache with PHP as a FastCGI module and selecting basic Apache & PHP modules required (no bloat). At this point, with the improvements at Engintron, anything besides mod_php (for PHP) will perform better for your server. Make sure you read the other optimization guides (beyond Engintron) which are the ones that do make a difference, performance-wise.
