### ISSUE TITLE
Slow on first load...

### ISSUE THREAD

**Issue by Friends4U** [engintron/engintron#294]
When I enable Engintron, the first time I visit a site it takes quite long before the site is shown... the second time it goes fast, but when I wait an hour it's slow again (unless just crawled by Google orso).

How come?

**Comment by windsofchange** [comment]
@Friends4U 
Sounds you have a low traffic site which you want to speed up with engintron. Since the default settings of microcache is 1 sec, each time when the response is slow it's generating cache. 

So maybe you can increase microcache time, but if you do frequent changes this could cause other issues.

**Comment by JorgeMarcelino-HS** [comment]
@windsofchange How to increase the microcache? whats the way? I have the same problem here.

**Comment by fevangelou** [comment]
You should first look at optimizing your server's Apache, MySQL & PHP options. Nginx is not the bottleneck here. See the related guides in the Engintron Wiki.
