### ISSUE TITLE
Custom rules

### ISSUE THREAD

**Issue by GeorgeD12** [engintron/engintron#300]
Does anyone know how I can add custom rules in engintron that won`t be removed on update, something like 

> "set $EXPIRES_FOR_DYNAMIC "5m"; 

adding this into custom_rules doesn`t override the settings in proxy_params_dynamic. Thanks.

**Comment by fevangelou** [comment]
For 99,999% of Engintron users, overriding the above value would result in a mess with any sites with user generated content like forums or eshops. That's why it's deliberately left out of "custom rules". Plus, properly adjusting this value actually requires adjusting 2 lines in proxy_params_dynamic.

That being said, it's in my plans to allow for different cache times for different domains. This will come in the next few months and will probably offer you a permanent solution.
