### ISSUE TITLE
[1.7.3] can't access the domain unless I remove the try_files directive from location /

### ISSUE THREAD

**Issue by kingofsevens** [engintron/engintron#325]
Blank server with new setup. Well, I removed another plugin and installed this one.
Added domain. I can access it through example.com:8080 but can't access via example.com. Tried everything. Only thing that worked is that I removed the try_files directive and instead put include directives in the location and it worked. 

Also nginx reload does not work from plugin but it works from command line. That lost me some time as well. I have set it up to work with openresty instead of default nginx but this shouldn't cause problem.

**Comment by fevangelou** [comment]
"Well, I removed another plugin and installed this one." That's the problem. You're probably using rules from the old plugin. Completely remove the /etc/nginx directory and re-install Engintron.

Since you mention OpenResty, I haven't tested it with the Engintron installer, so I have no idea what sort of issues may come up.
