### ISSUE TITLE
URL Canicolization with Egintron

### ISSUE THREAD

**Issue by WebSavvyGuy** [engintron/engintron#329]
Hi

I recently moved from NginxAdmin and have run into several issues but i will create tickets for each issue im facing.

With regards to url canonicalization, we want to redirect users from http://mydomain.com to http://www.mydomain.com

So non-www to www.

Is there any way to add it on the Nginx end?   The only way I have been able to figure this out is putting a rule in the .htaccess file as follows:

# BEGIN Canonical Redirect
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTP_HOST} !^www\.mydomain\.com$ [NC] ## will match any domain that's not our main domain
RewriteRule ^(.*)$ http://www.mydomain.com/$1 [R=301,L]
</IfModule>

However, i do remember before we could do that on the VHOST settings in our previous plugin.

Any ideas what to do here?

**Comment by fevangelou** [comment]
That is correct - Apache rules are the solution. That's because Nginx operates in proxy mode and for everything to be automated, it does not apply any redirect rules. Of course, for specific domains, you can edit your "custom rules" file through WHM and add anything you want, e.g. in your case:

```
if ($host = 'mydomain.com' ){
    rewrite ^/(.*)$ $scheme://www.mydomain.com/$1 permanent;
}
```

But only you, the admin of the server, can control that.

**Comment by WebSavvyGuy** [comment]
Any advantages with running it through the "custom rules" file vs. running it through the .htaccess file?

**Comment by fevangelou** [comment]
None. I just responded to your question "Is there any way to add it on the Nginx end?".
