### ISSUE TITLE
Unable to connect to port 8080 on 127.0.0.1: Connection refused: Died 

### ISSUE THREAD

**Issue by theret** [engintron/engintron#367]
Hey, 

After installing and running Nginx and Apache I keep getting httpd down errors with : 

Unable to connect to port 8080 on 127.0.0.1: Connection refused: Died  

Followed by:

[Fri Jan 13 10:15:52.002227 2017] [suexec:notice] [pid 86722] AH01232: suEXEC mechanism enabled (wrapper: /usr/local/apache/bin/suexec) 
[Fri Jan 13 10:12:48.006246 2017] [core:notice] [pid 86003] AH00094: Command line: '/usr/local/apache/bin/httpd' 
[Fri Jan 13 10:12:48.006204 2017] [mpm_prefork:notice] [pid 86003] AH00163: Apache/2.4.25 (Unix) OpenSSL/1.0.2h mod_bwlimited/1.4 mod_fcgid/2.3.9 configured -- resuming normal operations 
[Fri Jan 13 10:12:47.001747 2017] [:notice] [pid 86002] ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/) configured. 
[Fri Jan 13 10:12:47.001676 2017] [suexec:notice] [pid 86002] AH01232: suEXEC mechanism enabled (wrapper: /usr/local/apache/bin/suexec) 
[Fri Jan 13 10:12:44.006068 2017] [core:notice] [pid 85968] AH00094: Command line: '/usr/local/apache/bin/httpd' 
[Fri Jan 13 10:12:44.006007 2017] [mpm_prefork:notice] [pid 85968] AH00163: Apache/2.4.25 (Unix) OpenSSL/1.0.2h mod_bwlimited/1.4 mod_fcgid/2.3.9 configured -- resuming normal operations 
[Fri Jan 13 10:12:43.001698 2017] [:notice] [pid 85967] ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/) configured. 
[Fri Jan 13 10:12:43.001632 2017] [suexec:notice] [pid 85967] AH01232: suEXEC mechanism enabled (wrapper: /usr/local/apache/bin/suexec) 
[Fri Jan 13 10:12:40.005823 2017] [core:notice] [pid 85937] AH00094: Command line: '/usr/local/apache/bin/httpd' 
[Fri Jan 13 10:12:40.005767 2017] [mpm_prefork:notice] [pid 85937] AH00163: Apache/2.4.25 (Unix) OpenSSL/1.0.2h mod_bwlimited/1.4 mod_fcgid/2.3.9 configured -- resuming normal operations 

Then after a while httpd is recovered and it happens again every few minutes. In the time httpd is down I get a 502 bad gateway on all the sites. 

Ideas?

Thanks

**Comment by fevangelou** [comment]
Make sure port 8080 is allowed in your firewall.

**Comment by zstergios** [comment]
@fevangelou I have same issue.
It works all day nicely and sundenly nginx stops, and cpanel monitoring can't start it again because of error
Unable to connect to port 80 on 127.0.0.1: Connection refused: Died

Use HTTP2 module


Mar 28 06:46:10 "hostname" systemd[1]: Starting nginx - high performance web server...
Mar 28 06:46:10 "hostname" nginx[10737]: nginx: [emerg] invalid value "2.0" in /etc/nginx/proxy_params_common:13
Mar 28 06:46:10 "hostname" nginx[10737]: nginx: configuration file /etc/nginx/nginx.conf test failed
Mar 28 06:46:10 "hostname" systemd[1]: nginx.service: control process exited, code=exited status=1
Mar 28 06:46:10 "hostname" systemd[1]: Failed to start nginx - high performance web server.
Mar 28 06:46:10 "hostname" systemd[1]: Unit nginx.service entered failed state.
Mar 28 06:46:10 "hostname" systemd[1]: nginx.service failed.
