### ISSUE TITLE
Engintron and Nginx HTTP/2 support 

### ISSUE THREAD

**Issue by tux-tn** [engintron/engintron#368]
This is not an actual issue, 

I heard that Engintron 1.8.0 is coming soon (Good news :100:  )  and will bring HTTPS caching and HTTP/2 support to Cpanel

Considering the fact that Chrome/Chromium has droppen support for NPN HTTP/2 negociation in favor of ALPN and also that the version of OpenSSL shipped with Cpanel/Centos 6/Centos 7 does not yet support ALPN, how do you plan to bring HTTP/2 support to Chrome users?

**Comment by tux-tn** [comment]
The only obvious answer i found was to compile nginx using a custom version of OpenSSL (1.0.2j)

**Comment by ExoUNX** [comment]
There are a couple ways to approach this. Provide the re-compiled nginx RPMs and state it does not rely on the system's OpenSSL, or have the user download the source of OpenSSL 1.0.2 (or 1.1.0) and compile the packages (this would require a large amount of dependencies.) Either way Engintron first needs to support TLS before this can be successfully implemented. I'm not sure about the internal policies of the Engintron developers but I'd be more than glad to compile and host a mirror for Engintron's nginx rpms.

**Comment by tux-tn** [comment]
Folks from [CodeIT](https://codeit.guru/en_US/) are already hosting a repo for both mainline and stable branches with compiled with both OpenSSL 1.0.2 and Brotli compression
[Centos6](https://repo.codeit.guru/codeit.mainline.el6.repo)
[Centos7](https://repo.codeit.guru/codeit.mainline.el7.repo)
I don't know if Engintron developers will maintain a similar repo or ask to compile a custom version of OpenSSL but according to their [Twitter account ](https://twitter.com/engintron_sh/status/819878983529562112) we will know in a couple of days

**Comment by fevangelou** [comment]
@tux-tn Thanks for the links

**Comment by ubidzz** [comment]
Thank you @tux-tn it works grate and now my sites are using http2.

**Comment by Nirjonadda** [comment]
@ubidzz , How you to enabled http2?

**Comment by ubidzz** [comment]
i ran the command that is found here
https://codeit.guru/en_US/
Then when to WHM -> Software -> System Update "Include kernel packages"
After that finish restart your server
Then reinstall Engintron

**Comment by ubidzz** [comment]
OK i had to unstalled my nginx and and cant get it reinstalled with CodeIT can someone tell how i can run CodeIT repo so it update my stuff.

**Comment by webhost247** [comment]
@ubidzz it looks like CodeIT's repo is messed up I get this error when trying to install the mainline repo

> Connecting to repo.codeit.guru (repo.codeit.guru)|2a01:4f8:141:3350::2|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-03-01 03:33:35 ERROR 404: Not Found.

**Comment by ubidzz** [comment]
I do not get that error with CodeIT repo on my server.

**Comment by ubidzz** [comment]
@fevangelou should really add CodeIT repo to get the nginx service so it compiles a newer version of OpenSSL for it and not use CentOS released version of OpenSSL for the nginx server. This also helps fix a few bugs and gives better Security for using the nginx server. This would also change the protocol from http 1.1 to h2 and will also use NPN and ALPN but i am still having some issues with OCSP stapling not always being used. I am not sure why OCSP stapling is not working every time and only works 50% of the time on one of my domains. I think CodeIT updated their compiled OpenSSL because now i am using 1.1.0e that was released feb 16 2017 well apache is still using 1.0.1e that was released feb 11 2013

**Comment by fevangelou** [comment]
@ubidzz I can add a switch in the Engintron WHM app to disable OCSP Stapling (if it's unstable as a feature for your server due to overall network issues). However I don't plan on adding 3rd party repos. They could inject crap or malware one way or another. Nginx is a company with names and addresses. WhoTF is CodeIT?

Besides, cPanel have responded on Twitter that updating OpenSSL is back on the board for them, exactly because of this HTTP/2 issue.

If this is not done in a timely manner, compiling Nginx from source is the only alternative. But this can be part of a commercial alternative to Engintron, as it will take more time to develop.

**Comment by ubidzz** [comment]
No i am not worried about the OCSP Stapling problem that i am having. I would not hold my breath with cPanel it been asked for so many times and been so long to get cPanel to update OpenSSL. They worry more about the cosmetic of cPanel/WHM then adding updated service versions. I don't have no problems using CodeIT repo to build the nginx server and compile the newer OpenSSL with it.

**Comment by ExoUNX** [comment]
@ubidzz It's not practical for cPanel to add their own updated OpenSSL package unless they installed it in /opt. CentOS currently relies on RHEL/CentOS OpenSSL 1.0.1 package. So you'll either need to rely on CodeIT/Other or compile your own sources. I do believe they plan to add OpenSSL 1.0.2 to CentOS 7.4 as an extra package option though. 

https://bugzilla.redhat.com/show_bug.cgi?id=1276310

**Comment by fevangelou** [comment]
@ExoUNX As I mentioned above, depending on how cPanel resolves this matter the coming months (or not), I may offer a premium version with the option to build Nginx on demand. Not how others have done this before but in a way the redefines the entire product, as I did with Engintron.

**Comment by ExoUNX** [comment]
I haven't tested Engintron yet, but shouldn't this issue now be resolved both by CentOS and Nginx (Official Nginx packages are now compile on CentOS 7.4/OpenSSL1.0.2k.)
