### ISSUE TITLE
502 Bad Gateway after restart

### ISSUE THREAD

**Issue by theret** [engintron/engintron#372]
Hey 

Every time I restart Apache through Engintron it wouldn't start and I get a 502 on all my sites. 

I have to restart Apache through WHM for sites to work again... 

Ideas?

Thanks

**Comment by fevangelou** [comment]
The cPanel restart for Apache performs various checks than simply doing "service httpd restart". My guess is that there is some misconfiguration in Apache which breaks the latter. Do this manually in terminal and check the output. Does Apache restart or not?

**Comment by Cavain** [comment]
@theret I got that same issue on my server after Upgrading the Engintron . The solution of this problem is simple once you upgraded purge all cache files and then Disable the Engintron then re-enable it then it will starts working. That process works for me. I hope it will works for you also.
Have a great day!

**Comment by fevangelou** [comment]
I guess it's resolved.
