### ISSUE TITLE
WordPress Contact Form shows server IP instead of visitor IP

### ISSUE THREAD

**Issue by ichadi** [engintron/engintron#381]
Only happens with this module enabled.

I have this in the custom rules file in WHM

```
if ($host ~ "domain1.com") {
    set $PROXY_DOMAIN_OR_IP "xxx.xxx.34.6";
}

if ($host ~ "domain2.com") {
    set $PROXY_DOMAIN_OR_IP "xxx.xxx.34.4";
}
```
The IP that shows up in the form is 34.2 (main server IP).

How can I fix this?

**Comment by timeassistant** [comment]
you need to make sure your wordpress site or your WAF is set to use the correct method of retrieving IP addresses. The default method will not work when you are using a reverse proxy. 

For example if you use wordfence they have the option to tell the site how to get the IP address. choose different options until you get your correct IP showing. 

Check that your server logs itself (or mod security) report visitors real IP's otherwise you may need to consult this issue: https://github.com/engintron/engintron/issues/168

**Comment by fevangelou** [comment]
I would also recommend to simply re-install Engintron (from its WHM app) as the Apache configuration may have killed a rule placed to allow Apache to retrieve the correct user IP from Nginx. For more, have a look here please: https://github.com/engintron/engintron/wiki/Check-if-visitor-IPs-are-properly-logged-in-Apache-after-installing-Engintron
