### ISSUE TITLE
SSL Chain issues with Engintron 1.8.0

### ISSUE THREAD

**Issue by tux-tn** [engintron/engintron#394]
Hello,

Actually Engintron 1.8.0 is using Apache's `SSLCertificateFile` directive as `ssl_certificate` but it can create problems if the intermediate certificate used to sign the domain crt is not known by the browser, see [SSL certificate chains](https://nginx.org/en/docs/http/configuring_https_servers.html#chains)

Apache is solving this problem by using `SSLCACertificateFile` and sending out the CA chain with the certificate but Engintron 1.8.0 is not implementing any equivalent (i think the only equivalent is to create a fullchain.pem file containing both certificate and CA chain) and is only sending the certificate.

SSL Labs grade is capped to B because of this problem
![](https://i.imgur.com/dDUODGd.png)

**Comment by fevangelou** [comment]
Run the test for your server's hostname and you'll get a grade A. But if
you look closely, beyond the chain issue (which doesn't seem to cause any
issues in actual usage), the percentage for each of the 4 scores is
identical.

The solution to this of course is to create full chain files on the fly.
And I can do that of course in subsequent updates.

In the meantime, it works.

**Comment by ubidzz** [comment]
the only way to fix this chain issue is to add the domain.crt and domain.caboundle in to 1 file. I had the same issue for my script i am making in till i found out about both crt files have to be in 1 file this is why in my script it copy the info from the httpd.conf file and put them in to the ssl folder in nginx. So that the nginx server don't use the paths from httpd.conf file and use it own paths/files for caboundle, crt, key and domain.conf files. So no matter what cPanel or the user in cPanel installs SSL it added to the nginx server.

**Comment by Citizen-K** [comment]
Getting connection not trusted warnings, particularly on mobile browsers

**Comment by fevangelou** [comment]
URL please?

**Comment by Citizen-K** [comment]
https://airgunsports.org.za/

**Comment by Citizen-K** [comment]
Thank you Fotis, the latest update fixed the problem 100% for me.

**Comment by tux-tn** [comment]
Fixed in https://github.com/engintron/engintron/commit/e7ff7664324372ccfeb0999d17ad87291b1074eb 
Good job @fevangelou

**Comment by fevangelou** [comment]
@tux-tn You're welcome.
