### ISSUE TITLE
502 Bad Gateway - testing before DNS change

### ISSUE THREAD

**Issue by KristijanL** [engintron/engintron#396]
Hi,

i want to try engintron on a different server than the domain is pointed, but i can't test it because nginx is using external IP, obtain i guess over dns? 
I have the domain in /etc/hosts without success. Any pointers?

Kristijan

**Comment by fevangelou** [comment]
Look at the Engintron wiki. The solution is there (you edit your custom
rules and add a domain exception).

On Feb 17, 2017 23:37, "Kristijan Lečnik" <notifications@github.com> wrote:

Hi,

i want to try engintron on a different server than the domain is pointed,
but i can't test it because nginx is using external IP, obtain i guess over
dns?
I have the domain in /etc/hosts without success. Any pointers?

Kristijan

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/engintron/engintron/issues/396>, or mute the thread

**Comment by KristijanL** [comment]
yeah true!
sorry for the false issue :)
