### ISSUE TITLE
Why are you adding google analytics in WHM

### ISSUE THREAD

**Issue by ubidzz** [engintron/engintron#399]
Hello @fevangelou
Can i ask you why are you adding your google analytics in to the WHM/Engintron theme page?
For me that not cool to be tracking my server.

**Comment by fevangelou** [comment]
Tracking basic usage only. It was the fastest way for me at the moment implemented.

Since the gathered info is not all that great though, this will be swapped with a more tailored solution to anonymously report system environment & Engintron version. Something like I already do for getk2.org (another project of mine). You can see the metrics gathered here: https://metrics.getk2.org

Something like that will be developed for Engintron for v2.0.0.

**Comment by fevangelou** [comment]
BTW if you have a better solution for anonymous tracking (so I can swap GA before v2.0.0), feel free to share.

**Comment by fevangelou** [comment]
Closing for now.
