### ISSUE TITLE
[Idea] ModSecurity Integration

### ISSUE THREAD

**Issue by nem-c** [engintron/engintron#424]
Hi guys,

First, I like to say AWESOME JOB with Engintron.

Next, as thought, or idea... Even with Engintron, if you have mod_security installed, apache takes the hit on L7 filtering.

Maybe it will be good thing to have option to enable existing mod_security rules in whm integrate into Engintron.

Yes, I'm aware there can be some issues with logs and stuff, but lose some to get some I guess.
I never did benchmark tests with it, but I will try in upcoming months.

It would be great to see how much you can scale Engintron to actually protect and serve your server, not just serve as it is now.

Cheers!

**Comment by fevangelou** [comment]
Unfortunately, Engintron's no.1 rule is to use Nginx repos for security, stability & features updates that are painless and transparent. In order to bring ModSecurity to Nginx, the latter would have to be built from source, which kills rule no.1.

If mod_security on the Apache side is properly configured, at least you know you're covered.
