### ISSUE TITLE
forwarding domain  on different port?!

### ISSUE THREAD

**Issue by systemroot** [engintron/engintron#426]
hello! 

First thank you for this project! is very helpful and powerful! 

i have 1-2 month using it and is running very well without problems just nginx fail to start on boot :/ i need to start it manually, i already i add with chkconfig , but doesn't work, anyway no problem i set up a cronjob which turn on nginx on boot. 

so now i'm running ghost blog with nodejs in the same server where engintron is installed and my domain pointed but ghost blog need a different dedicated port to run! and now i want to do a port forward with nginx, i tried to put proxy pass into custom rules file but that isn't allowed, 

Anyone can help how can i do this just for one domain?! ex my ghost blog is running on **127.0.0.1:6699**
where can i set up a proxy pass config on engintron for domain **example.com**, as i was reading files, engintron doesn't create a vhost file for every domain so maybe this isn't possible or i tried on wrong file!

Thanks. and sorry if is a duplicate!

**Comment by tux-tn** [comment]
You can set the proxy domain and port in your `custom_rules` file:

```nginx
if ($host ~ "example.com") {
        set $PROXY_DOMAIN_OR_IP "127.0.0.1";
        set $PROXY_TO_PORT 3000;
}
```

assuming that node is listening on 127.0.0.1:3000
Is your domain using ssl/tls? You will have issues because nginx will proxy requests to https://127.0.0.1:3000 but you can also change this behavior

**Comment by systemroot** [comment]
yes i have problems with ssl now, i tried to host domain on cpanel which get cpanel ssl, then to forward it with nginx but that didn't work :confused:

**Comment by tux-tn** [comment]
The issue is that engintron will proxy requests using the same protocol used for the initial request.
You have two sollutions:
1/ Use ssl in your nodejs backend : easiest way
2/ Modify engintron configuration using a workaround, 

Add a variable $prot (don't use $protocol because it's a reserverd nginx variable, but you can name it anything) in your default.conf file

```nginx
    set $CACHE_BYPASS_FOR_DYNAMIC 0;
    set $CACHE_BYPASS_FOR_STATIC 0;
    set $PROXY_DOMAIN_OR_IP $host;
    set $PROXY_TO_PORT 8080;
    set $SITE_URI "$host$request_uri";
    set $prot "http";
``` 

Do the same for `common_https.conf` file, not available from engintron webui so use ssh to edit the file, it's located inside `/etc/nginx`

```nginx
set $CACHE_BYPASS_FOR_DYNAMIC 0;
set $CACHE_BYPASS_FOR_STATIC 0;
set $PROXY_DOMAIN_OR_IP $host;
set $PROXY_TO_PORT 8443;
set $SITE_URI "$host$request_uri";
set $prot "https";
```

Now edit `proxy_params_commons` file and change this line from:
```nginx
proxy_pass          $scheme://$PROXY_DOMAIN_OR_IP:$PROXY_TO_PORT;
```

to
```nginx
proxy_pass          $prot://$PROXY_DOMAIN_OR_IP:$PROXY_TO_PORT;
```

Now in custom_rules edit the block for your new redirect
```nginx
if ($host ~ "example.com") {
        set $PROXY_DOMAIN_OR_IP "127.0.0.1";
        set $PROXY_TO_PORT 3000;
        set $prot "http";
}
```

Waiting for your feedback, good luck

**Comment by systemroot** [comment]
the first way
```
if ($host ~ "example.com") {
        set $PROXY_DOMAIN_OR_IP "127.0.0.1";
        set $PROXY_TO_PORT 3000;
}
```
worked, just if manually i put https:// that will redirect me some where else..
the bad news are that ghost blog doesn't have a option to put ssl on it even in tutoriales they explain to put ssl on nginx http://support.ghost.org/setup-ssl-self-hosted-ghost/ but anyway at this time my blog is good without ssl

thank you very much for your help! last question what if i create a vhost file just for my domain and i put SSL on it and other stuff will that cause any problem for engintron?!

**Comment by tux-tn** [comment]
You can of course create a new server block for your custom domain, i suggest you to append it to `default.conf` since `default_https.conf` is generated dynamically, you will only need to replace every line with `include proxy_params_common` with your custom proxy_params file.

I think the solution with new variable will be much easier than creating a custom vhost and custom proxy_params

**Comment by systemroot** [comment]
okay i'll try to set up and make tests in another server i won't crash anything, thank you :slightly_smiling_face:

**Comment by tux-tn** [comment]
You are welcome, good luck!
