### ISSUE TITLE
How To enable Nginx with SPDY

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#435]
I need Enable SPDY on Your Origin Server. Please let me know the steps in Nginx.

**Comment by ubidzz** [comment]
SPDY is a different type of protocol that is used to connect to a website. SPDY is a old protocol and it better to use http/2 and it based on your browser because different browsers connect using different protocols between SPDY and http/2.

Here is a few examples from SSL labs
Firefox 31.3.0 ESR / Win 7	RSA 2048 (SHA256)  	TLS 1.2
Firefox 47 / Win 7  R	RSA 2048 (SHA256)  	TLS 1.2 > h2
Android 6.0	RSA 2048 (SHA256)  	TLS 1.2 > http/1.1

You will see TLS 1.2, TLS 1.2 > h2 and TLS 1.2 > http/1.1 this is the type of connection that is being use.

If i am correct that SPDY is just the normal TLS protocols from TLS 1.0 to SSL 3 and if you look you will see this TLS 1.2 > h2 that is using TLS 1.2 with http2.

In nginx this module ngx_http_spdy_module is not built by default and was superseded by the ngx_http_v2_module module in 1.9.5

To change the type of protocol to use for SSL you will have to edit the Engintron plugin file from using http2 to SPDY in the /etc/nginx/utilities/https_vhosts.php file. But this will set all your SSL sites to use SPDY.

**Comment by Nirjonadda** [comment]
@ubidzz but Engintron are not Enabled http2 support? Issue here : [https://github.com/engintron/engintron/issues/437](url)

**Comment by tux-tn** [comment]
The issue is related to CentOS OpenSSL version
I proposed a solution here: https://github.com/engintron/engintron/issues/368
