### ISSUE TITLE
How to domain Redirects without www

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#436]
How to domain Redirects without www ? My domain Redirects no more working with engintron.

mysite.com > 502 Bad Gateway nginx , Without adding www are not Redirects.

**Comment by ubidzz** [comment]
The domains should be both www and non-www that is in the default_https.conf to look for both and both load the same settings. It matter whats the end user adds in the address URL but all domains are registered to work with www and non-www. The domain registrar will add www to the domain DNS because it stands for "Wold Wide Web" and if your site is not loading with www that a problem with your server or domain DNS in your server that it is missing the www DNS record. In your domain DNS records there should be a www CNAME pointing to your domain. The nginx default_https.conf file is coped from your httpd.conf file and info and is put in to the default_https.conf

**Comment by Nirjonadda** [comment]
@ubidzz No, My DNS record are OK. This issue only happened with Engintron Enable.
