### ISSUE TITLE
Nginx config for SSL site

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#446]
Please let me know that where i can find out Nginx config for SSL site? Nginx config files location?

I want change this line:

````
listen 443 ssl;
````
To

````
listen 443 ssl spdy;
````

**Comment by ubidzz** [comment]
You can change it in the /etc/nginx/utilities/https_vhosts.php file
find this line
`listen '.NGINX_HTTPS_PORT.' ssl http2 default_server;`
to
`listen '.NGINX_HTTPS_PORT.' ssl spdy default_server;`

Then go to /etc/nginx/conf.d folder and delete this file default_https.conf file so that it can be rebuilt with spdy.

Then run /etc/nginx/utilities/https_vhosts.php

**Comment by Nirjonadda** [comment]
@ubidzz If this then how to Enable ALPN ?

**Comment by tux-tn** [comment]
@Nirjonadda why do you need spdy support? 
spdy was removed from the latest versions of Google chrome and moreover nginx's spdy module was superseded by http2 one (if you replace http2 with spdy in your config file, you will get an error)
http2 is a better alternative, which contains all the benefits of spdy and more important is a web standard.

For ALPN support please see #368

**Comment by fevangelou** [comment]
Off-topic.
