### ISSUE TITLE
IPv6 and Engintron

### ISSUE THREAD

**Issue by Friends4U** [engintron/engintron#473]
Hi,

https://www.ssllabs.com/ssltest/analyze.html?d=www.cb-s.nl&latest

My host says Engintron blocks the IPv6 or are they incorrect?

**Comment by fevangelou** [comment]
Why would Engintron block IPv6 traffic? Ask them for more proof.

**Comment by Friends4U** [comment]
Ok,

My host says:

It's because the nginx installation supplied with Engintron is not listening op port 80 and 443 on IPv6. http://[2a02:40c0:1000:2000::154]:8080 does work. This is because of the nginx config that's being generated by Engintron.

**Comment by fevangelou** [comment]
If you have a closer look you'll notice that Nginx configurations define ports only. This makes them interoperable with both IPv4 and IPv6.

However, Nginx DNS resolvers are set to use IPv4 by default, otherwise it would explode on 99% of cPanel servers. Edit your nginx.conf file and locate where DNS resolvers are defined. You should see comments on how to enable IPv6 resolvers there.

Let me know.

**Comment by Friends4U** [comment]
I did that already and activated the resolvers for IPv4 and 6, but that does not work

**Comment by fevangelou** [comment]
Try adding `listen [::]:80 ipv6only=on;` below the main "listen..." directive in default.conf and so the same with HTTPS traffic by adding `listen [::]:443 ipv6only=on;`.

The problem is that I can't leave these settings enabled in Nginx by default as they cause Nginx to break when IPv6 is not supported.

I'll make a note to add a switch to enable on demand IPv6 support in v1.9.0.

**Comment by Friends4U** [comment]
It looks like that's working yes.

https://[2a02:40c0:1000:2000::154] gives a strange result, but that's something on my server I think.

Tnx!

**Comment by Friends4U** [comment]
OOPS... lol... normal https sites do not work anymore after this fix :)

**Comment by fevangelou** [comment]
@Friends4U Perhaps it boils down to other factors. First check that Apache create's vhost entries for your IPv6 addresses too. If it does, then check that your domain(s) resolve to both IPv4 and IPv6 IPs. Clean Nginx's cache/temp files and verify.

**Comment by Friends4U** [comment]
Sorry, it's becoming to complex for me and I don't want to mess things up...
I'll leave the IPv6 for now.

Thanks!

**Comment by fevangelou** [comment]
Added commented IPv6 listen lines in v1.8.3 just released.
