### ISSUE TITLE
ssl cert not updated

### ISSUE THREAD

**Issue by FlokiNET** [engintron/engintron#529]
We face the problem that with ssl, new installed cert only shows up after nginx has been disabled.
Otherwise it will still serve an old cert.

Any suggestion on that?

Update: specified

**Comment by naja7host** [comment]
your issue is similar to this one
https://github.com/engintron/engintron/issues/527

**Comment by fevangelou** [comment]
Try purging Nginx's cache/temp files only. Open the site afterwards with a private browser window because your normal browser session may have cached pointers to the old certificate.

Let me know.

**Comment by windsofchange** [comment]
Thanks for merging the issue threads. Here is some more feedback on issue which may help
`Hello,

Thank you for your patience as I reviewed the situation.

I have found that this issue is happening because NGINX does not have the necessary configurations to allow the AutoSSL DCV checks to complete.

When a request is made for the AutoSSL DCV file, NGINX blocks the request with a 401 Unauthorized error.

As you've noticed with the webmail subdomain, once you manually add the subdomain to cPanel, NGINX generates the appropriate configuration files it needs to be able to serve content on that subdomain, and therefore allows the DCV check to complete.

I have tested this on a testing server with Enginetron installed as well to confirm that this behavior is consistent outside of your specific environment.

Because Enginetron and NGINX are not products provided by cPanel or within the bundled software that comes with cPanel, we would not be able to make the changes to the NGINX configuration or Enginetron package to allow AutoSSL to complete the DCV checks by default.

If you would like for this functionality to work by default, it would be advisable to reach out to the developers of Enginetron and make a request to update the configuration of Enginetron to be compatible with the AutoSSL DCV checks for Proxy Subdomains. The installation of SSL certificates via AutoSSL for Proxy Subdomains is brand new as of cPanel 64, so it is likely that the developers of Enginetron may not yet know that their package is blocking the DCV requests made by AutoSSL.

In the meantime, until Enginetron has had a chance to update this, there are two workarounds that you may consider for installing the SSL certificates on your proxy subdomains via AutoSSL.

Workaround 1:
- Disable Enginetron temporarily ( Home » Plugins » Engintron for cPanel/WHM >> Disable Engintron )
- Run AutoSSL for all users /usr/local/cpanel/bin/autossl_check --all
- Allow AutoSSL to complete, and then enable Enginetron again

Workaround 2:
Manually create the subdomains for each proxy subdomain that you would like SSL to work for via the Subdomains icon in cPanel

Please let me know if you have any further questions or concerns.



Regards,

--
Austin Lowery
Technical Analyst
cPanel, Inc
`

**Comment by fevangelou** [comment]
Well, some additional info would help me fix this issue. I know LetsEncrypt creates .well-known directories at the root of each site for verification purposes and this is not blocked in any way by Engintron. Engintron only blocks files starting with ".ht". Could it be that Comodo certificates use such a naming pattern?

Really, it's not rocket science. :)

**Comment by windsofchange** [comment]
Yes, here is a typical log of the error generated

8:22:13 AM WARN The domain “cpanel.domain.com” failed domain control validation: The system queried for a temporary file at “<a href="http://cpanel.domain.com/8F010574112CAC2F8A4A7F3BC629D201.txt">http://cpanel.domain.com/8F010574112CAC2F8A4A7F3BC629D201.txt</a>”, but the web server responded with the following error: 401 (Access Denied). A <abbr title="Domain Name System">DNS</abbr> or web server misconfiguration may exist.

**Comment by windsofchange** [comment]
Other such proxy subdomains are

webmail.domain.com
webdisk.domain.com
whm.domain.com
autodiscover.domain.com

**Comment by fevangelou** [comment]
Serving .txt files is not an issue. However calling whm.domain.com probably doesn't work for you when Engintron is enabled, right?

**Comment by windsofchange** [comment]
http://whm.domain.com works fine with Engintron. As this is an authentication page we need https.  https://whm.domain.com throws up SSL certificate error. When we not try to deploy an SSL certificate via AutoSSL (Comodo) on url, we get error when domain validation is attempted.

**Comment by fevangelou** [comment]
Comodo would probably verify the domain over HTTP, not HTTPS. Check "Tweak Settings" for any unusual settings for these special subdomains. Nginx does not block anything. The redirect may not work as expected though.

**Comment by windsofchange** [comment]
All good in tweak settings

**Comment by fritolays** [comment]
Any progress or suggestions beyond turning it off and on again.

This 401 error occurs with Let's Encrypt and Comodo AutoSSL providers.
Attempting to visit one of these 401 pages produces a popup login box that accepts root login.
There is also a 111 (connection refused) error in the nginx error log.

Keep in mind this is only with the proxied subdomains: whm, cpanel, webmail, webdisk, and autodiscover.
Hostname, and domains autossl function just fine.

**Comment by linetpavol** [comment]
The workaround is to disable engitron before autoSSL starts. You can modify the autoSSL cronjob. If you have CentOS 7 go to /etc/cron.d and open cpanel_autossl file. In this file just delete the text after user name root and add: `/engitron.sh disable && /usr/local/cpanel/bin/autossl_check --all && /engitron.sh enable && /bin/systemctl restart nginx.service && /bin/systemctl restart httpd.service`. Save the file and its done.
The cronjob job will now every day disable engitron, check the certificates, enable engitron and restart the nginx and apache server. The restart is not neccessery but it good to run it. If you have enabled the "Use a Global DCV rewrite exclude instead of .htaccess modification" disable it. After the cronjob is done you can check the autoSSL log in "Manage AutoSSL". For me its workking.

**Comment by jhawkins002** [comment]
Also on CentOS 7 here. While using @linetpavol's approach above we've encountered a number of errors which intermittently led to NGINX and Apache not properly restarting. After inspecting the Cron log, we discovered the following errors consistently cropping up:

```
TERM environment variable not set.
/engintron.sh: line 19: httpd: command not found
/engintron.sh: line 460: service: command not found
/engintron.sh: line 780: service: command not found
```

Long story short, at least for us, is that you need to make sure to add shell/path directives to the top of the Cron - which the default cPanel file did not include. We also updated hard-coded Apache/NGINX service restarts in favor of the Engintron 'res' command which restarts Apache/NGINX. You may want to use 'purgecache' which will flush the NGINX cache of old data and then perform the service restart:

```
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

37      0       *       *       *       root    /engintron.sh disable && /usr/local/cpanel/bin/autossl_check --all && /engintron.sh enable && /engintron.sh res
```

To clear the 'TERM environment variable not set' error we have to add the following to the actual /engintron.sh file:

`export TERM=${TERM:-dumb}`

Basically Cron cannot run scripts using environment variables the same way a user can through a regular terminal session, and the 'export TERM' adjusts for that. It is not entirely clear to us that this error actually results in engintron.sh not operating correctly via Cron... but we have consistently recorded NET::ERR_CERT_COMMON_NAME_INVALID errors on SSL sites when we do not use it.

FYI to @fevangelou since the Cron patch outlined on https://github.com/engintron/engintron/wiki/Cron-job-to-purge-Nginx-cache-&-temp-files may well be touched by some of these came concerns.

**Comment by abkrim** [comment]
I use tip of @linetpavol but nothing. On some servers, cache not clean, and after run autossl, several sites break SSL certificates, using teh hostname certificate instead owned FreeSSL certificate.

A seriuos issue for production server. 

```
 /engitron.sh disable && /usr/local/cpanel/bin/autossl_check --all && /engitron.sh enable && /bin/systemctl restart nginx.service && /bin/systemctl restart httpd.service
/engintron.sh purgecache >> /dev/null 2>&1
```
Not work, Only work sometimes, manual 

```
cd /; rm -f engintron.sh; wget --no-check-certificate https://raw.githubusercontent.com/engintron/engintron/master/engintron.sh; bash engintron.sh install
```

**Comment by jhawkins002** [comment]
@abkrim As a thought, I would suggest not piping the Cron output to null so that you get an email with the some debugging information when it runs. This may help you troubleshoot why the script is not working - as in our case we had to make a number of slight modifications for the Cron to properly operate. 

Also, be sure to note @linetpavol accidentally spelled engintron.sh as engitron.sh in the original script. Just noticed that in your pasted text :)

**Comment by abkrim** [comment]
I see issue with `engitron.sh``
Even so, I not put yet the redirect towards null. 
My cron output now is with MAILTO = myemail @ mydomain

Tomorrow I'll see log...

I also saw the message late, and this morning I had breakfast again, the problem.

Well I've disabled engintron (everything works fine) and I've re-enabled it manually, and everything works fine.

**Comment by kvillios** [comment]
Hello to everyone,

I have the same issue on our servers with cPanel, CloudLinux 7.3, Engintron 1.8.3 and I have solve it temporary with one trick.
I just reload the nginx some times with cron on every day and all it's ok with the ssl certificates. For example the following cron:

`0 0,2,8,10,12,14,16,18,20,22 * * * /bin/systemctl reload nginx.service`

**Comment by jhawkins002** [comment]
Just to check back in. It appears, at least on our hosts, we spoke too soon regarding a Cron fix being an effective patch for this error. 

I arrived at the office today to numerous reports that SSL sites on our production host were serving NET::ERR_CERT_COMMON_NAME_INVALID errors on HTTPS. A quick NGINX restart fixed the issue, but the problem seems to have presented itself after the Cron run last night.

I have now conducted a series of additional tests today and approximately out 1 out of 10 NGINX restarts will cause NET::ERR_CERT_COMMON_NAME_INVALID errors to manifest. To be clear, that is to say disabling Engintron, re-enabling, and restarting NGINX/Apache has a 1:10 chance to cause this error to happen on domains where the issue was not previously occurring.

Im simply at a loss at this point.

**Comment by Shadowized** [comment]
@jhawkins002 I think I figured this out, what I needed to do is actually invoke the ssl config generator script from engintron `(/etc/nginx/utilities/https_vhosts.php)` to make it work, I'm pretty sure its some weird race condition between the default engintron cronjob on generating ssl vhosts since it isn't automatic and nothing is really tethered so half the time it'll fire off correctly and others it will serve the incorrect ssl certs (either the system-wide self-signed default, or the old expired cert on a domain) so instead of having a very long/awkward one liner I just made it a shell script.

```
#!/bin/bash

# disable engintron, run autossl, and re-enable engintron
/engintron.sh disable
/usr/local/cpanel/bin/autossl_check --all
/engintron.sh enable

# generate ssl configs for nginx and than restart apache/nginx
php /etc/nginx/utilities/https_vhosts.php
service httpd restart
service nginx restart
```

it works for me, YMMV but at least it can give you an idea on why its serving incorrect certs.

**Comment by jhawkins002** [comment]
@Shadowized Great share! This makes sense and we may play around with your approach in the coming week.

**Comment by abkrim** [comment]
@Shadowized  Not work for me... some (only a fews) sites, show hostname certificate instead fdqn certificate...
mode hilarious activate....
**"Why is Engintron a better solution compared to other Nginx installers for cPanel"**
Because some  issues, are permanent and has not solution.....
mode hilarious deactiavte....

**Comment by fevangelou** [comment]
@abkrim Did you ever think that perhaps the cron job is not running? Open up the file /etc/crontab via the Engintron WHM app and just save it. Purge Nginx's cache/temp files and check again.
