### ISSUE TITLE
nginx 502 error after changing PHP version in one account (EasyApache 4)

### ISSUE THREAD

**Issue by botonakis** [engintron/engintron#560]
So if the server uses EasyApache 4 then there is the option for MultiPHP per account.
The server works perfect and I go to "any" cpanel account and change the php version.
After 5 seconds the whole server shows 502 error.

I open Engintron, I click on Restart Apache & nginx and everything back to normal.

Any solutions, thoughts!?

**Comment by fevangelou** [comment]
Are you referring to HTTP or HTTPS traffic specifically or both?

**Comment by botonakis** [comment]
Both.

**Comment by fevangelou** [comment]
I don't see how changing PHP could affect site paths or domains in Apache. Check with a private window in case the response is simply cached for some reason by Nginx and/or Apache.

**Comment by fevangelou** [comment]
@botonakis I think I know what it is. Switching PHP versions and more importantly, switching to using PHP-FPM results in the latter not being able to read the .htaccess file inside your public_html folder (usually under root permissions). cPanel uses that file to write special comments for the PHP engine. If it can't access this file because it belongs to root, things will simply fail.

Execute `/engintron.sh fixownerperms` in the terminal to restore file ownership.

This is definitely a bug in cPanel and I'll make sure to notify them.
