### ISSUE TITLE
cPanel Comodo SSL adding or renew needs manually to clear nginx cache files to work

### ISSUE THREAD

**Issue by qlpqlp** [engintron/engintron#566]
Hello,

On cPanel Comodo SSL adding or renew needs manually to clear nginx cache files to work

can you add a solution for this, maybe on the cron?

/etc/nginx/utilities/https_vhosts.sh

Thanks in advance :)

**Comment by rapidcloubr** [comment]
Hello,

We have the same problem here.

**Comment by ramphy** [comment]
Hi @qlpqlp and @rapidcloubr - The disadvantage is that, to delete the cache is necessary to restart the nginx but, does not give the correct effect.

I have added an issue so that in the documentation do not just quit:
0 2 * * * root "/engintron.sh purgecache" >> / dev / null 2> & 1

Otherwise the nginx will also restart.

https://github.com/engintron/engintron/issues/570

Solution: Purge cache and restart nginx: service nginx restart

**Comment by JorgeMarcelino-HS** [comment]
There was an update at this time: #Engintron v1.8.4 released! Improves AWStats logging & fixes issue with new / renewed certificates & Nginx's caching:

Someone upgraded, is everything okay now?

**Comment by qlpqlp** [comment]
Hello,

We have upgraded 2 days ago and everithing semas OK :)

**Comment by JorgeMarcelino-HS** [comment]
AWStats continues not working!

**Comment by fevangelou** [comment]
Resolved.

**Comment by faca5** [comment]
Hello.

Problem again detected and reported #1455  on latest version of Engintron  v2.1.
