### ISSUE TITLE
ipv6 - will it still work?

### ISSUE THREAD

**Issue by BionicClick** [engintron/engintron#573]
Team,

I have fully enabled IPV6 on my cPanel server. I use a dedicated IP for each cPanel account. I note here: https://github.com/engintron/engintron/wiki/Engintron-&-(under-development)-domains-that-don't-yet-resolve-(point)-to-your-cPanel-server

that the Enginetron team notes*** that for dedicated IP's there is a bit more work to do... however I do not see where you can enter the dedicated IPV6 IP alongside the IPV4 IP in the exclusion scenario.

please help. need answered prior to installing for first time user.

**Comment by fevangelou** [comment]
To enable IPv6 in Nginx you need to install it first then comment out a few lines of configuration, as Nginx cannot use both protocols if both are not already configured (will throw errors when restarting). After you do this, you don't need to configure anything else. You only need to specify dedicated IPs is the custom rules file ONLY if you use CloudFlare for these domains and that's because CloudFlare is already a reverse caching proxy.

**Comment by fevangelou** [comment]
Update to the latest build and: https://github.com/engintron/engintron/wiki/Enable-IPv6-support-in-Nginx

**Comment by fevangelou** [comment]
Just pushed v1.11.0 making Engintron IPv6 capable by default. Please upgrade and let me know if you see any issues.
