### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by rahulnagpal1989** [engintron/engintron#593]
1) First if i disable nginx via Engintron and again enable it, so that /etc/nginx/conf/default_https.conf file should recompile though /etc/apache2/conf/httpd.conf file.
2) Then it take certificate from host5.tcyonline.com and shows privacy warning.
3) Then i disable 2 lines from default_https.conf file i.e.
ssl_certificate /var/cpanel/ssl/cpanel/mycpanel.pem;
ssl_certificate_key /var/cpanel/ssl/cpanel/mycpanel.pem;
and restart nginx after that, site stop responding because of comment these lines.
4) Then i uncomment these lines and restart again nginx and its work fine, now it takes tcyonline.com ssl certificate without any issue.

I want permanent resolution of this issue.

**Comment by rafaelppaulucci** [comment]
Same here.
Following your steps the problem was solved.

**Comment by fevangelou** [comment]
@rahulnagpal1989 SSL certificates are cached in the browser as well. That was your issue. Not Engintron. In the future, you should probably consider requesting help for a free open source project in a more polite way than:
> I want permanent resolution of this issue.

**Comment by rahulnagpal1989** [comment]
Ok Sorry @fevangelou but at that time i am very frustrating by adopting Engintron SSL certificate issue is coming again n again and no proper documentation is there for this issue and our users complaining this again n again.

**Comment by rafaelppaulucci** [comment]
@fevangelou I figured out what's going on. Technicaly is not a issue.
The file /etc/nginx/conf/default_https.conf takes more time to be writen because its has a lot of entries and the nginx starts previously the finish of file write.
If you wait and confirm the file was writen, and do a restart in nginx, everything ill work fine!
Is there any way to do a delayed start of nginx or confirm a restart after the file was properly writed?

Regards !

**Comment by fevangelou** [comment]
If it takes more than 10 seconds fir you, I'll have to figure out a way to
disable any additional operations until the process is finished.
