### ISSUE TITLE
Nginx : SSL_CTX_use_PrivateKey_file (..) failed

### ISSUE THREAD

**Issue by kotsias** [engintron/engintron#642]
Hi, My cpanel just updated to version  v66.0.22 and nginx stop working!! When i try to restart it i see the error "Nginx : SSL_CTX_use_PrivateKey_file (..) failed" . I just remove engintron until a fix for this issue released. Is any other solution to fix this wihtout remove the engintron? Thanks a lot.

**Comment by fevangelou** [comment]
You have to provide the entire error message reported by Nginx, otherwise it's impossible to know WHERE the problem occurred in the first place. I assume you tried flushing Nginx's cache/temp files first...

**Comment by kotsias** [comment]
Hi. First i have to say that just reinstall engintron 3 times and clear all caches and update cron tab with no success. In last time when reinstalling engintron the problem solved but i cant understand the reason. The entire log from nginx restart command is "[emerg] SSL_CTX_use_PrivateKey_file("/var/cpanel/ssl/installed/keys/acdae_61a39_0bae4914c02d31c61f512cd5e6dc72aa.key") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/cpanel/ssl/installed/keys/acdae_61a39_0bae4914c02d31c61f512cd5e6dc72aa.key','r') error:20074002:BIO routines:FILE_CTRL:system lib error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib)"

**Comment by kotsias** [comment]
I' trying to find out where nginx check for this key and why the key is not in this folder? The only action from me it to update the cpanel to lasterst version 66.0.22 and nothing more! I try to rebuild the ssl.db from cpanel etc but all this things didn't work for me. Although, now is OK, but i lose my conf.d folder with .configurations files from my customers. Is any automate action that build this conf files again? Thanks a lot. And sorry for the inconvience.

**Comment by fevangelou** [comment]
Nginx will always reflect what's in Apache's httpd.conf file. This reference (to the .key file) was obviously a leftover, either from a failed domain removal or a failed SSL cert generation (I honestly don't know - you should probably raise this issue to cPanel support). Since the file was referenced there but did not exist, Nginx failed to generate its own config files.

I'll issue an update to verify that each file loaded into Nginx is valid. However on servers with hundreds to thousands of domains this may be an issue if Engintron's PHP code has to check from a few hundred to a few thousand files every time the HTTPS vhosts for Nginx are created. I wish I could measure this but I honestly don't have a server with so many accounts at my disposal.

Perhaps the best thing to do is probably add a control in Engintron's WHM app to reload Nginx HTTPS vhosts on-demand while checking that all certificates referenced actually exist. This will resolve issues with httpd.conf having leftover references to non-existent certificates.

**Comment by kotsias** [comment]
Mmm. Very helpful answer! Thanks. One last question. Is any problem with my conf.d folder and files from my domains? After reintall the engintron all files are gone. I check my domains with https with curl -I command and all it's ok. (served from nginx etc.) How i can re-generate the conf.d folder and configuratios for all my domains? It's neccessery? ** I could'r disable the engintron beacuse i couldn't login to my whm after this issue and i have to remove it via ssh terminal. However, it's ok now. Thanks

**Comment by kotsias** [comment]
After reinstall it again all it's fine but without cond.d files.. :(

**Comment by fevangelou** [comment]
cPanel will generate a large httpd.conf file with all Apache vhost definitions in it. This is what Nginx checks. I have no idea about the conf.d folder you mention. That's not a problem for Engintron. If you have a custom situation with how Apache's httpd.conf is generated, then that's a different story. By re-installing Engintron, you simply had it re-check the httpd.conf file which obviously at some point was regenerated and fixed the obsolete certificate file reference. As an intermediate step, do this if you get the same issue again and until I have an update issued: simply go to Apache's configuration options in cPanel (where you setup MaxClients, Timeout etc.) and just hit save without changing anything. This should regenerate httpd.conf and perhaps remove any broken references to certificate files that don't exist.

**Comment by kotsias** [comment]
Nice. Thanks a lot. Have a nice day!
