### ISSUE TITLE
Nginx become down frequently

### ISSUE THREAD

**Issue by greenwebbd** [engintron/engintron#646]
The service “nginx” appears to be down.

Service Check Method

The system failed to connect to this service’s TCP/IP port.

Reason

Service check failed to complete
Unable to connect to port 80 on 127.0.0.1: Connection refused: Died

Number of Restart Attempts
1

Startup Log

Sep 21 08:00:52 servertest systemd[1]: Starting nginx - high performance web server...
Sep 21 08:01:01 servertest nginx[929896]: nginx: [emerg] SSL_CTX_use_PrivateKey_file("/var/cpanel/ssl/installed/keys/cbb47_828a9_decfc21022905814ccbb8f09fab08679.key") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/cpanel/ssl/installed/keys/cbb47_828a9_decfc21022905814ccbb8f09fab08679.key','r') error:20074002:BIO routines:FILE_CTRL:system lib error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib)
Sep 21 08:01:01 servertest nginx[929896]: nginx: configuration file /etc/nginx/nginx.conf test failed
Sep 21 08:01:01 servertest systemd[1]: nginx.service: control process exited, code=exited status=1
Sep 21 08:01:01 servertest systemd[1]: Failed to start nginx - high performance web server.
Sep 21 08:01:01 servertest systemd[1]: Unit nginx.service entered failed state.
Sep 21 08:01:01 servertest systemd[1]: nginx.service failed.

i 've faced this problem twice this week. i also got this error last month. i have to disable engintron and enable again. it works only after then.

**Comment by Experthost** [comment]
@greenwebbd: consider yourself lucky. In our case disabling and enabling it didn't do the trick nor reinstalling it from interface. Later, I will uninstall and do a fresh install and post the result.
 What's weird, is that on other servers using same build version (1.8.5/20170831 and 1.12.1 for nginx) as well as same apache config (EA3), same kernel, same Cloudlinux and same cPanel (66.0.23) such issue didn't appear (yet).
Log:

`2017/09/22 07:42:20 [emerg] 47077#47077: "if" directive is not allowed here in /etc/nginx/domain_exclusions.conf:28
2017/09/22 07:47:26 [emerg] 50498#50498: SSL_CTX_use_PrivateKey_file("/var/cpanel/ssl/installed/keys/cac7d_9c11f_a4470bbaf6fb0d9b6307a2c84deabeb8.key") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/cpanel/ssl/installed/keys/cac7d_9c11f_a4470bbaf6fb0d9b6307a2c84deabeb8.key','r') error:20074002:BIO routines:FILE_CTRL:system lib error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib)`

**Comment by ErrEvil** [comment]
I can also confirm the same issue with same error exists on some of my servers as well.
Unfortunately, in these cases Nginx goes down out of nothing.

Specs:

cPanel 66
EA4
Engintron 1.8.5

It seems it is a global issue because multiple bug reports regarding it already exists:

https://github.com/engintron/engintron/issues/550
https://github.com/engintron/engintron/issues/583
https://github.com/engintron/engintron/issues/561

Some of the users found a work around scripts but they are completely pointless.

The issue should be fixed globally!

**Comment by fevangelou** [comment]
@Experthost First off, your error indicates a syntax problem in a file called /etc/nginx/domain_exclusions.conf - that file is not part of Engintron. Either you modified Engintron to include this file or someone else did it for you. That's not Engintron's fault.

@greenwebbd Your issue is pretty clear. Nginx is trying to include a certificate file (/var/cpanel/ssl/installed/keys/cbb47_828a9_decfc21022905814ccbb8f09fab08679.key) which it READS from Apache's configuration. This is a leftover from some deleted domain or certificate and it should not be in Apache's configuration. Nginx simply reflects Apache's configuration which is entirely controlled by cPanel. Since this issue has occurred in several users, my guess is there's some bug in AutoSSL which does not cleanup Apache's configuration or there's a delay in that process. My plan for the coming update of Engintron is to increase the time that Nginx checks Apache's config file from 10 seconds to 20 seconds (in case an update in Apache's config is taking long) and also add checks for each file that is included in Nginx's configuration when mirroring Apache's config, so when Nginx reloads its new configuration it does not end up with the error you see.

@ErrEvil That's because the issue doesn't really come from Engintron. Read above.

**Comment by Experthost** [comment]
@fevangelou the domain_exclusion.conf was required in order to skip the manual adding custom rules for newly created account/addon domains on server and is part of wiki hints (thanks for all of that!). By the time we've started using Engintron, if no changes were made to custom rules, the customers did got the 'this is the default webpage ... after changing DNS records' and as soon as the directive were added, instantly worked. 
 Since the cPanel update, Engintron was one of the best thing happened in past years related to webserver improvements and we still vote for it so don't get me wrong on it.
 If it ever can be helpful, after uninstalling Engintron, some users belonging to a reseller, had assigned mainserver IP instead reseller's shared IP so we had to modify every record in order to mach old IP and get rid of same DNS change webpage displayed for them.
 If I'd knew about this issue before, I wouldn't let cPanel do the automatic updates just to keep your software enabled.
 Cheers!

**Comment by fevangelou** [comment]
@Experthost I wasn't offended or anything. I simply stated the facts. In your case, unless you're using CloudFlare, you don't need to assign custom rules for domains except only when you want to add caching exclusions. That's what I'd do. Alternatively, you could also disable Engintron access to resellers.

**Comment by Experthost** [comment]
@fevangelou After 1st time install (about 2 yrs ago), after creating a new account the content didn't load for several days unless these changes were made (and no, it wasn't related to DNS propagation view that after client complains, we did the modification and everything worked after restarting nginx & httpd). Probably it was fixed later but at that time, it was the only way to fix it and yes, we do provide Cloudflare services to customers and some of them use it.

**Comment by greenwebbd** [comment]
@fevangelou  thanks for clearing the fact. i'm no longer getting this error since i have changed cpanel update setting "release" to "stable" and reissue ssl. yes i agree with you i got this due to invalid ssl, i have changed the ssl now it's not giving me that error anymore.
