### ISSUE TITLE
Upgrade from 1.7.2 to 1.8.5

### ISSUE THREAD

**Issue by ciscospirit** [engintron/engintron#651]
Hello,

we updated to latest cPanel 66 LTS and  also want to upgrade Engintron from 1.7.2 to the latest 1.8.5 release.
But we are a little bit afraid of, cause in your changelog you wrote about some troubles, so we first want to proove if there could be a problem with our config.

* We use AutoSSL with Comodo. Is this still a problem if we upgrade to 1.8.5? => https://github.com/engintron/engintron/wiki/SSL-certificate-considerations-with-cPanel's-AutoSSL

* Not all of our cPanel accounts have AutoSSL enabled. Is this a problem? You wrote something like this in releaselog 1.8.0 => "It's important that domains already have an issued TLS/SSL certificate via cPanel"

* We use Cloudlinux 7 and cPanel 66 and have "open_basedir" enabled for all accounts. You wrote in your requirements that this has to be disabled. What would be the alternative for open_basedir? Also what did you mean with "right builde mode for PHP?" => https://github.com/engintron/engintron/wiki/Requirements

it would be very nice if you could answer my questions. So i can update the plugin without any harm.
Thank you.

**Comment by gfxdesigner** [comment]
Hello,  
 Thank you for contacting me. I am out of the office and will be returning on Monday, October 2nd. If I am unable to respond to your email during this time period, I will respond when I return to the office. Otherwise, if you need immediate assistance, then please open a support ticket by sending an email to support@gfxservices.com.

Russ Miller
GFX 
916.965.0450 Sales / Support
877.842.3369 Toll Free Fax   

Quick Links: Website  |  Support

**Comment by fevangelou** [comment]
It's safe to upgrade. In fact, you should as the performance and overall stability is much better.

Replying to your questions:
a) Yes, these certificates have proven to cause issues. Since these are the free ones, swapping to LetsEncrypt is pretty easy and the latter have proven to be very reliable so far. I'd recommend switching to LE certificates first and then upgrading Engintron for a smooth transition.
b) Not at all. The only problematic certificates so far are Comodo's free ones. If you have any domain without a certificate, Nginx will continue to serve it just fine.
c) cPanel sent me a tip which I've incorporated in the last release on how to execute cPanel's PHP for Engintron without such issues. But I haven't tested it with "open_basedir" enabled. The latter comment is for those using EasyApache 3 only. I'll update the wiki.

**Comment by ciscospirit** [comment]
Hello,

thanks for your answer:

a.) i switched to LetsEncrypt right now, but my current certificates are still at Comodo, but i think the problem would just with the validation process or not?
b.) okay thanks.
c.) is it possibel that you test this maybe before i upgrade?

thanks
