### ISSUE TITLE
Problem AutoSSL

### ISSUE THREAD

**Issue by gfrares** [engintron/engintron#652]
Hello,

I have a problem with the AutoSSL, see: https://hastebin.com/eyexelijuc.sql

The problem is caused by engintron, without engintron all ssl's are generated successfully, how to solve this problem?

I see this words can be the problem: Size of response body exceeds the maximum allowed of 16384

**Comment by djprmf** [comment]
That error is related with the cPanel tring to create the SSL to webmail and cpanel subdomains, that are not valid... The error in size is because the page loaded is the error page from the server.
So, isn't a problem from engintron...

You cannot use AutoSSL to create certificates to that domains.
Try search here: https://forums.cpanel.net/

**Comment by bobalo2** [comment]
cPanel says it's Engintron's fault, and Engintron says it's cPanel's fault. Wonderful.
I also have this issue btw.

**Comment by djprmf** [comment]
@bobalo2 , no, they confirm this: https://forums.cpanel.net/threads/autossl-for-proxy-subdomains-such-as-whm-cpanel-and-webmail.583612/

:)

**Comment by fevangelou** [comment]
@djprmf Thank you for the clarifications Pedro.

**Comment by bobalo2** [comment]
@djprmf from what I can read there , it seems they have fixed that issue. The issue is with the "Size of response body exceeds the maximum allowed of 16384" which does not issue certificates for cpanel. subdomain(s). cPanel guys say we should report this error here...

**Comment by gfrares** [comment]
Hello,

yes, without the engintron the problem not occours

**Comment by djprmf** [comment]
I have servers without even engintron installed that have the same issue...
Check if this helps: https://forums.cpanel.net/threads/the-domain-failed-domain-control-validation.605123/#post-2458327

Also, Verify the following options are enabled under the "Domains" tab in "WHM >> Tweak Settings":
Proxy subdomains
Proxy subdomain creation

I think the "Size of response body exceeds the maximum allowed of XXXX" is because something is being loaded instead of the confirmation code from Let's encrypt.... For instance, a error page.
If the user domain have some kind of redirection (or the DNS records don't exist, the htaccess file redirect subdomains, etc), that could cause issues...

**Comment by gfrares** [comment]
@djprmf Thanks for your reply.

Yes, this options are enabled on the configuration of the cPanel...

For tests i have configured a new account but the problem remain, have other suggestion?

**Comment by jhawkins002** [comment]
@gfrares This is a shot in the dark, but do you have ModSecurity enabled? If so, check its logs to see if it is the culprit. ModSec can enable response body limits, and it would definitely produce an HTTP 403 error.

I believe the specific ModSecurity directive that would be invoked is "SecResponseBodyLimit" - and it typically lives in the modsec user.conf files - not in rulesets.

**Comment by bobalo2** [comment]
@gfrares have you checked this?

**Comment by apocas** [comment]
https://github.com/engintron/engintron/issues/675#issuecomment-361378960
