### ISSUE TITLE
mod_pagespeed recomendation

### ISSUE THREAD

**Issue by spopadiin** [engintron/engintron#655]
Hello,
Would you recommend adding ngx_pagespeed to ngintron? Or it should be left to apache?

10x

**Comment by fevangelou** [comment]
I think it's probably best to use the Apache module, since ngx_pagespeed is not yet distributed as a dynamic Nginx module (which would allow including far more easily in Nginx). Besides, mod_pagespeed can do the various optimizations once (e.g. image manipulation, HTML output optimization etc.) and the Engintron's Nginx will serve the generated content optimally (as always).
