### ISSUE TITLE
SSL stops working when disabling and enabling Engintron...

### ISSUE THREAD

**Issue by Friends4U** [engintron/engintron#664]
I really need to reboot my server to get SSL working again :(
This was never the case until now.

**Comment by Friends4U** [comment]
Hmmm... restarting Nginx and Apache also works, but it must be done...

**Comment by tiagomreis** [comment]
There is a Internal BUG about that: CPANEL-15961

This is happening because the Nginx plugin changes the Apache's default port when it is enabled, and then changes it back when it is disabled. With the switch, the userdata for the account gets thrown off its dedicated IP address and gets moved back to the main shared IP address.

I'm pretty sure that that's happening because you have a website not running on main shared IP.

Since Apache's config gets rebuilt when Nginx is disabled (because of port switch), it ends to get the main IP. 

To fix this, you need to rewrite the userdata file with the correct IP, rebuild and restart the Apache.

**Comment by Friends4U** [comment]
All my sites run on main ip...

**Comment by tiagomreis** [comment]
If you pretend, activate the Engintron again two check the response of :443 on https://cb-s.nl

**Comment by Friends4U** [comment]
That changes nothing... it still gives an invalid cert until I restart Nginx and Apache.

**Comment by djprmf** [comment]
Reinstall the SSL on the sites afected...

**Comment by fevangelou** [comment]
@tiagomreis Wow... (on CPANEL-15961)...

**Comment by bosen** [comment]
[https://forums.cpanel.net/threads/when-you-change-port-host-accounts-lose-their-ip.610819/](url)
