### ISSUE TITLE
Cannot login to wp-admin after uncommenting Set-Cookie

### ISSUE THREAD

**Issue by chaoswithcontrol** [engintron/engintron#668]
In proxy_params_dynamic;

expires               $EXPIRES_FOR_DYNAMIC;
proxy_hide_header     Cache-Control;
proxy_hide_header     Expires;
proxy_hide_header     Pragma;
#proxy_hide_header     Set-Cookie;
proxy_hide_header     Vary;

with the set-cookie uncommented i cannot login to wordpress admin.
When i try to login it just redirects back to the wp-login.php
I can login if i comment it out, However shit seems so much fast without set-cookie lol.

Site is behind cloudflare.
Doesnt have any wordpress related security plugins installed.

**Comment by fevangelou** [comment]
The line you commented out actually HIDES Set-Cookie. So it's essentially what you want.

**Comment by fevangelou** [comment]
As you can see in that file, /wp-login.php is excluded from caching altogether. "Set-Cookie" is set to be ignored through the "proxy_ignore_headers" setting before the lines you mention.

Your issue is caused from `expires $EXPIRES_FOR_DYNAMIC;` which translates to a forced client-side 1m caching.

Read the file in its entirety please.
