### ISSUE TITLE
cPanel web statistics show's proxy traffic with servers IP address

### ISSUE THREAD

**Issue by joekuzma** [engintron/engintron#678]
I just installed Engintron on my WHM, and after running for a while - I started to notice the web stats in cPanel show a huge volume of incoming hits coming from my server's IP address.

I realized that it must be the nginx proxy'ing traffic to apache.

What can I do to resolve this, so that nginx passes the original information to apache?

**Comment by Friends4U** [comment]
https://github.com/engintron/engintron/wiki/Check-if-visitor-IPs-are-properly-logged-in-Apache-after-installing-Engintron

**Comment by elchaka** [comment]
Hello joekuzma,
unfortunaly i have the same issue. The said script from "friends4u" works for us an shows "Verdict: YES" but apache only logs the server ip so that all stats (awstats etc.) shows the server als the visitor... so you see always Xvisits etc. from only this one ip-adresse.

This is a big issue for nearly all of our customers and it would be very nice if someone had an idea whats is going wrong.

We are using EA3
