### ISSUE TITLE
Question: The real benefit for small sites?

### ISSUE THREAD

**Issue by eminos** [engintron/engintron#68]
I'm sorry for using "Issues" for my question, but I didn't find any other way to simply get an answer. I hope it's OK, you can always close it :)

Reading the wiki here you state this as how Engintron works:

> First, Nginx will enforce Cache-Control/Expires headers for such static files

And then:

> Second, Nginx will apply a soft 1 minute internal cache for static files, so that it doesn't re-request these files from Apache, whenever new traffic comes in. Since Nginx is built to handle static asset delivery way better than Apache, you'll notice a drop in resource usage (CPU & RAM) on your server.

I read this as Engintron doesn't really benefit sites that:
1. Uses Cache-Control/Expires headers anyway. Caches static files on the client.
2. Small websites that never have big bursts of requests, so never actually uses the 1 minute internal cache.

Most static files use the Cache-Control/Expires headers anyway, so after the first load (which would internally use Apache even with Engintron), those static files are client cached anyway.

Am I right in this, or am I missing something? Some other benefit that I'm not understanding?

**Comment by fevangelou** [comment]
First off, you're in the right place. I'm intentionally using GitHub's issues so i can monitor all aspects of support issues at the moment, not just any potential bug reports.

Replying...
1. Your statements are valid to some level but it's because you are assuming that ALL sites on your cPanel server are properly configured to control headers, right? In reality, that's never the case and admins or site owners usually add .htaccess files per site to control that. Some sites may have them, so not. Nginx can "normalize" and better control this behaviour as you the server admin controls that sitewide and even for file types that your site owners would never think of caching (e.g. web fonts). Additionally, Nginx can cache static assets up to 1 min (in order not to cause noticeable issues to changed CSS, JS files etc.) and therefore speed up delivery without having Apache open a single thread while the content is cached. So it's not just client-side caching, it's also internal caching within Nginx.

You say that "most static files use Cache-Control/Expires headers anyway". Well, no they don't. cPanel does not enforce any caching behaviour in Apache's config by default. Neither Apache (by default) last time I checked.

2. Again you are assuming that sites won't have traffic. Valid point, but what if you have the hardware to add more sites on? If you have 200 small sites on cPanel this costs in resources to the server because of the large number of open files and threads. Nginx can minimize that load so you can use your resources elsewhere.

Again, your points are valid but they are based on assumptions which are beyond your control. I highly recommend you install Engintron and test your site's performance using public tools like Pingdom Tools or GTmetrix. I'm pretty sure all tests will score higher than if you used just Apache. And I'm not talking about benchmark tests, these are basic "content delivery & optimization" tests.

**Comment by eminos** [comment]
Thank you for the elaborate answer!

I think Engintron seems great and I'm probably going to try it out (once the CloudLinux compatibility is confirmed), but I also want to understand how it really works.

I understand that Nginx is faster than Apache, but since the first request is going to use Apache (through Nginx) anyway, and only cache the result for 1 minute. I'm still not seeing where the benefit is for most really small sites comes from.

Example 1:
- Small website.
- No client-side caching.
- One request every 60+ seconds in average.
- All those requests are hitting Apache (through Nginx) anyway.
- Benefits ONLY for the second request in a less the 60 seconds timeframe, since that second request is getting the cached result directly from Nginx.

Example 2:
- A bit bigger website.
- Uses client-side caching.
- All the static files are cached client-side anyway, so no requests are using the static files cache anyway. Nginx is using Apache for all non static content.

So if I use Pingdom, and set it up to measure a websites speed every 5 minutes or so. If the website is anything like those two examples (few requests, or already using client-side caching), I understand that Engintron isn't actually doing anything and there can't be any difference in speed.

The biggest benefit seems to be that Engintron is setting the Cache-Control/Expires headers for you. Is there a way to control/override that per website/user?

Once again, I'm really not trying to make it seem as Engintron is less valuable. And I understand what you are saying about many sites on a server and that it's hard to manually control all of them (client-side caching and stuff), and that's there Engintron helps.

**Comment by fevangelou** [comment]
Engintron has already had hundreds of deployments the past few days after I announced v1.5 on Twitter. Reports from users confirm that CloudLinux version 6 & 7 are 100% compatible with Engintron.

So your best bet is to install Engintron and see for yourself. Measure the actual benefit in speed by using private windows in your browser, before Engintron and after Engintron.

And by the way, Nginx does way more things than caching (client or server side). Things that are pretty un-optimized by default in Apache, like connection timeouts or keepalive settings.

Since you seem hard to convince, I can only suggest you try Engintron out.

**Comment by drjjw** [comment]
@eminos - Can I makea suggestion? Just install it. Running this on complex (but relatively low traffic sites) has provided huge performance advantages. Measured advantages.
