### ISSUE TITLE
Intermittent 502 Bad Gateway error

### ISSUE THREAD

**Issue by PaddyBee70** [engintron/engintron#688]
Hello!

This error occurs multiple times every day, but oddly enough it's only after I haven't visited the site for some hours, or with a fresh browser window. Or so it seems anyway.
When I refresh the page immediately afterwards, everything works fine again.
I doubt it's a browser issue (Chrome), as I have already cleared all cache. And I hear from friends that they have the same issue on my site.
It would be great to get this solved, so any suggestions are welcome.
Thank you :)

**Comment by PaddyBee70** [comment]
Update: in the Nginx error log I see 'could not be resolved (2: Server failure)' and 'unexpected response' for the domain.
I tried increasing the buffers and timeout, but it made no difference.
Also, the site gets automatically redirected to SSL via an .htaccess. But I guess that should not be causing the problem?

**Comment by brixly** [comment]
We still get intermittent 502 errors.

I can only assume this is to do with the Apache restart that takes place when SSL certificates are installed as part of the purgecache function

**Comment by brixly** [comment]
So, I noticed that this happened far more during the night, so I trawled through our logs to see what was going on.

We do run AutoSSL - when this runs, an SSL certificate is installed, then apache restarted (by cPanel, not Engintron).

Shortly following this, the https_vhosts.sh script checks and notices a difference in the nginx configuration and the apache config - as such, it then comes along and runs...

engintron.sh purgecache

This essentially clears down the caches, then restarts the httpd service, shortly followed by an nginx restart.

Whilst this is fine in servers running a few sites, when your working on a larger scale server you have the following scenario...

AutoSSL - "yes, installed a certificate, cPanel restarts httpd"
httpd_vhosts.sh - "found a difference between apache and nginx, lets restart httpd and nginx"

The problem is the above - its clashing.

Also, I am not entirely sure why the nginx restart is needed as this actually causes downtime on larger servers (whereby nginx takes slightly longer to restart the workers, similar to httpd)

I altered the engintron.sh purgecache script to remove the httpd restart entirely, and have changed the nginx restart for an 'nginx reload'

I have been monitoring the logs, and all is looking perfect.

I have an AutoSSL job running on over 1200 sites, so theres a good few httpd restarts happening with the cPanel tool - still not one sign of a 502 error, or a connection timed out error.

If all is well, I will post the suggestion to the developer for his comments.
