### ISSUE TITLE
Running apache on 127.0.0.1:8080

### ISSUE THREAD

**Issue by MoHD20** [engintron/engintron#695]
I want to run apache on 127.0.0.1:8080 and want nginx to proxify requests from 0.0.0.0:80

When i set that i no longer can connect to websites.

This question was asked before on #598. and answered  by:

> Apache, as set by cPanel does not listen to 127.0.0.1, but only on specific IP addresses. In other words, you can't do what you want.

I asked if that's possible on [cpanel forums](https://forums.cpanel.net/threads/is-it-possible-to-run-make-apache-listen-on-loopback-127-0-0-1.616135/)  and according to them it _is_ possible. so what exactly is the problem?

**Comment by theraw** [comment]
The problem comes when you want to use cloudflare and you enable
```bash
set $PROXY_DOMAIN_OR_IP "XXX.XXX.XXX.XXX";
```
this means that Engintron will forward traffic based on your static ip XX.XX.XX.XX:8080
and that fails. because you are running apache just for LAN and Engintron is trying to access it from your static ip.

if you have not set `$PROXY_DOMAIN_OR_IP` and Engintron fails to access apache that menas your configurations somehow are wrong.
