### ISSUE TITLE
CORS header with CDN - double access-control-allow-origin

### ISSUE THREAD

**Issue by codep0et** [engintron/engintron#700]
Having engintron enable on the server and max CDN configured, I have CORS issues on Chrome console with fonts.

If I run a curl -I file_url

I see double access  access-control-allow-origin: *

I have no setting in my htaccess, I was wondering how can I turn the access-control-allow-origin off in engintron. I went threw the settings and commented out the sections that have the add_header but its still showing up. When I disable engintron I only have one access-control-allow-origin.

I understand this is not necessarily a bug because its a good thing to have the * for fonts. But in the event that someone uses a CDN  and they seem to add it also is problematic for Chrome. If I can just know how to disable it server side it would be perfect.

Thanks

**Comment by rvencu** [comment]
This happens for me as well without CDN. I can see two headers and Chrome browser refuses to load fonts claiming that "*, *" is invalid setting for access-control-allow-origin

Without Engintron all is well. Commenting add_header lines also does not remove the double headers

**Comment by rvencu** [comment]
I solved the situation like this:
edit `commons_https.conf`
Insert a new line before line (105 in my config file) 
`add_header Access-Control-Allow-Origin *;`
with this content: 
`proxy_hide_header Access-Control-Allow-Origin;`

This line removed the CORS headers that might be present and served by Apache. When Nginx will add its new ones there will be no more too much headers to break browsers functionality.

I know this is not the best place to make config changes because they will be overwrited at updates/reinstalls. Maybe this can be added to the default installation @fevangelou ?

**Comment by fevangelou** [comment]
@zhangcunxin Or just upgrade to the latest release of Engintron :)
