### ISSUE TITLE
Is HTTP2 ALPN still not working out of the box?

### ISSUE THREAD

**Issue by joebordo** [engintron/engintron#705]
I had a website running on apache with http2 alpn. I wanted to make it faster so i installed engintron. Now there is no http2 and its same speed as before... it's like nginx "compensated" the lack of http2...

What are my options?

**Comment by Technopope** [comment]
HTTP/2 ALPN is not yet supported by Engintron because it uses Nginx from the source and they haven't provided it for the older versions.

However there is a custom build of Nginx Made by CodeIT you can use. 
Located here - https://codeit.guru/en_US/

Run this as root - 
cd /etc/yum.repos.d && wget https://repo.codeit.guru/codeit.el`rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release)`.repo

Login to WHM >> Engintron >> Reinstall Engintron

You should have HTTP/2 ALPN enabled on your website now.

**Comment by fevangelou** [comment]
This is actually wrong. Nginx as installed by Engintron is now fully
compatible with and serves by default HTTP/2 in CentOS 7 latest.

**Comment by Technopope** [comment]
@fevangelou 
Apologies, I've corrected the above mini-tutorial for CentOS 6 only.
CentOS 7 has latest versions of Nginx and supports HTTP/2 ALPN completely. 

Above guide can be used on CentOS 6 to enable HTTP2 ALPN.

**Comment by fevangelou** [comment]
@Technopope Thanks, adding it to the wiki.
