### ISSUE TITLE
Brotli with Engintron Nginx

### ISSUE THREAD

**Issue by koryfi** [engintron/engintron#712]
Hi !

How I can add Brotli compress support to Nginx with Engintron ? Thanks

**Comment by theraw** [comment]
you can compile the module as dynamic and add it to nginx

**Comment by koryfi** [comment]
Any kind of how can I do it? :D Thanks !

**Comment by theraw** [comment]
to build a dynamic module you first need to know the version of nginx which you are currently using so

`nginx -v`

then download the same nginx version from here `http://nginx.org/download/`

then something like this

```bash
mkdir -p /opt/nginx/source; cd /opt/nginx/source; nginx -v
# nginx version: nginx/1.13.4 (nginx-plus-r13)
wget http://nginx.org/download/nginx-1.13.4.tar.gz
tar xf nginx-1.13.4.tar.gz; rm -Rf nginx-1.13.4.tar.gz; mv nginx* nginx

mkdir -p /opt/nginx/mods/; cd /opt/nginx/mods/
git clone https://github.com/google/ngx_brotli.git; clear; cd /opt/nginx/source/nginx
cd /opt/nginx/mods/ngx_brotli && git submodule update --init && cd /opt/nginx/source/nginx

./configure \
--with-compat \
--add-dynamic-module=/opt/nginx/mods/ngx_brotli

make modules; clear; ls objs
mkdir -p /etc/nginx/mods
cp /opt/nginx/source/nginx/objs/ngx_http_brotli_filter_module.so /etc/nginx/mods/
cp /opt/nginx/source/nginx/objs/ngx_http_brotli_static_module.so /etc/nginx/mods/
```

Now open `nginx.conf` and put `.so`  file which is needed as for their explaination

>ngx_brotli filter module - used to compress responses on-the-fly,
>ngx_brotli static module - used to serve pre-compressed files.

ex
```
load_module mods/ngx_http_brotli_filter_module.so;
```

**Comment by koryfi** [comment]
Ooooh thanks !!

This replace the ningx that previously installed engintron? if is yes,  there no compatibility problem?

And in other articles I read that it is a good idea to copy the modules that are already used in engintron nginx -V, and add them in the line ./configure --add-dynamic-module =... , is it correct?

thanks thanks 💃

**Comment by theraw** [comment]
> there no compatibility problem?

No. i'm already using alot of modules no problems. It's just nginx with optimized configs and called Engintron. And there is no reason that Engintron can make problems. (without including cache/proxy modules!) You just should be careful with what you do because there is just one `default.conf` and one `default_https.conf` for all domains hosted in your server. if you activate something and add rules to `default.conf` it means that will be enabled for everyone not just for you.

>And in other articles I read that it is a good idea to copy the modules that are already used in engintron nginx -V, and add them in the line ./configure --add-dynamic-module =... , is it correct?

I don't think so. If there is a problem with them then just it will fail to compile or `nginx -t` will fail. this is the point to of "dynamic modules" you don't have why to compile whole nginx from the begin while you can just build what modules you want.. Also Engintron does not install any kind of module but just a pure nginx from official repo of nginx, and so modules can be build all in one or one by one as you did with brotli.
https://github.com/engintron/engintron/blob/master/engintron.sh#L251-L362
https://www.nginx.com/blog/compiling-dynamic-modules-nginx-plus/#build-module

Openssl may can be a problem for somethings but in that case it will fail directly in build not like after you build and start using you will get errors. 

So if you know what you're doing you can use whatever you want. Also keep in mind that i'm talking just from my experience and i'm not someone from Nginx staff or engintron developers. :v:
