### ISSUE TITLE
nginx: [emerg] too long parameter "# Definiti..." - Nginx hangs after too long parameters

### ISSUE THREAD

**Issue by influenist** [engintron/engintron#713]
So initially I fixed this error by removing the line questions on both my servers, hence it seems an automated cron regenerated my configs overnight.

nginx: [emerg] too long parameter "# Definiti..." started in /etc/nginx/conf.d/default_https.conf

As it seems Engintron loads up all the vhosts in a commented line, which creates a massive string.

Please advise how to avoid to solve this as I am unable to overwrite the default_https.conf and remove those strings.

**Comment by fevangelou** [comment]
Nginx nagging for a comment?

**Comment by influenist** [comment]
Have searched around. This is the commented part which is the origination of this error:
# Definition block for domain(s): www.xxx.tld xxx.xxx.tld ... www.zzz.tld zzz.zzz.tld

It's the number of vhosts which are placed into this comments which creates the error and causes Ngingx not to start up. The line which I removed contained at least 100 vhosts.

Can I comment somewhere this line out so it is not being added to the configuration files?

**Comment by influenist** [comment]
Arlight, I have manually updated line 125 in /etc/nginx/utilities/https_vhosts.php

I guess that would do the job for now.

**Comment by savaticus** [comment]
This should get fixed, a comment should not be created that is longer than the character limit for that type. Or at least not have it all on one really long line. I just ran into this myself and fixed it, then came here to see if there was already a bug report.

**Comment by savaticus** [comment]
I just did a bit of research.

In the NGINX config reader's source we find that it uses a 4096 byte buffer. to read lines. If any line is longer than that it says that it is too long.
[https://github.com/nginx/nginx/blob/master/src/core/ngx_conf_file.c](https://github.com/nginx/nginx/blob/master/src/core/ngx_conf_file.c)

Since the line already has several printed characters, as well as SOL and EOL characters and whitespace all we have to do is use substr to limit the characters that are emitted from the variable, this is simple considering each character is 1 byte.

Here is a diff of the fix.
`--- https_vhosts.old	2018-02-22 16:23:59.070988131 -0500
+++ https_vhosts.php	2018-02-22 16:37:05.568987966 -0500
@@ -122,7 +122,7 @@
                 }

                 $output .= '
-# Definition block for domain(s): '.$vhostDomains.' #
+# Definition block for domain(s): '.substr($vhostDomains,0,4058).' #
 server {
     listen '.NGINX_HTTPS_PORT.' ssl http2;
     #listen [::]:'.NGINX_HTTPS_PORT.' ssl http2;`

The script altered is /etc/nginx/utilities/https_vhosts.php

**Comment by savaticus** [comment]
That diff did not survive the simple markup, 
[https_vhosts.php.txt](https://github.com/engintron/engintron/files/1749667/https_vhosts.php.txt)

I have attached the patch file. 

It may be worth considering checking the length of the $vhostDomains variable and breaking it into smaller chunks if it is too long, and then writing separate alias blocks for each chunk.

I am presently working on another project, but if time allows ion the near future I will write this myself and submit a pull request.

**Comment by fevangelou** [comment]
@savaticus Noted. I'll implement this in the next update. Thanks.
