### ISSUE TITLE
apache_conf_distiller --update is not supported for EasyApache 4

### ISSUE THREAD

**Issue by shakaran** [engintron/engintron#759]
In the installer process with CloudLinux and EasyApache4 it appears:

```
=== Distill changes in Apache's configuration and restart Apache ===
warn [apache_conf_distiller] apache_conf_distiller --update is not supported for EasyApache 4. Please edit config files as detailed in the EasyApache 4 documentation: https://go.cpanel.net/EA4AdvApacheConf
Built /etc/apache2/conf/httpd.conf OK
```

**Comment by fevangelou** [comment]
Thanks, I'm already aware of that. In EA4, it's now simpler to change Apache's config - the line you see is effectively for older versions of cPanel and will be removed at some point in the future. That's why you get a "warning" message and not an "error" message which would subsequently cause the entire process to fail.
