### ISSUE TITLE
Engintron Plugin open in new tab

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#795]
Please can you let me know that How to stop Engintron Plugin open in new tab? cPanel default Plugin are not open in new tab. So why need Engintron Plugin open in new tab?

**Comment by ChristianGabs** [comment]
Underdevelopment 

https://prnt.sc/ja0jjv

This will take time. Moving to CGI(PERL) from PHP.

**Comment by fevangelou** [comment]
@ChristianGabs Still PHP :)

**Comment by ChristianGabs** [comment]
Sorry to but I'm working on Perl because PHP doesn't offer support. It's up to you if will be pulled into this project but I will set as public in Perl in my side.

The reason I merge to Perl and remake all this because of PHP include Cpanel Lib.
```
require_once('/usr/local/cpanel/php/WHM.php');
WHM::header('Engintron for cPanel/WHM',1,1);
```

If you look there're there missing few bits like the menu is not save on tab close/opened and there're too many missing headers.

The second issue I found with PHP the library generates a temporary header which they do not provide any support. 

It's up to you what you will do but if someone like to use with a menu we should provide support for that example I NEED THAT.

**Comment by fevangelou** [comment]
@ChristianGabs The menu and the header/footer includes being cached and all that are cPanel issues. They are not related to the Engintron UI's use of PHP. PHP, like Perl and any other language is just a tool for the job. However in the case of WHM's PHP API, it's still under development from the cPanel team.

@Nirjonadda The latest version opens up in the main WHM window.
