### ISSUE TITLE
Cleanup cache & temp files automatically?

### ISSUE THREAD

**Issue by grabacontroller** [engintron/engintron#80]
Anyway to do this? Thank you.

**Comment by fevangelou** [comment]
You don't need to do that. Unlike other plugins for Nginx on cPanel,
Engintron is carefully tuned so that Nginx's cache does not keep content
more than 1 minute. Expired cache entries will simply be removed by Nginx
automatically as new cache entries are created. The reason Engintron offers
a way to clean Nginx's cache is simple: if you're developing a website and
you wish to purge any cache for static files (CSS, JS etc.) you have a way
to do this without having to wait a full minute.

I recommend you let it run for a few days and you'll see no issues are
raised by the way Nginx handles its cache. In busy servers with many sites,
the total size of cache & temp entries will hardly pass 100 MBs, which is
far less than your typical /tmp allocated space.

**Comment by grabacontroller** [comment]
Ok. Awesome. Good job. Thank you.
