### ISSUE TITLE
mod_remoteip crashes httpd/apache (process wont start)

### ISSUE THREAD

**Issue by bdtech** [engintron/engintron#824]
Starting today apache wouldn't start following some routine UPCP package updates. 

A core dump revealed mod_remoteip causing the crash. I commented out loading this mod in /etc/apache2/conf.modules.d/370_mod_remoteip.conf and started Apache which allowed apache to restart. It was super tricky because there was nothing useful in the apache logs or elsewhere.

Is engintron's implementation of mod_remoteip reliable?

May 14 13:11:19 srv6 restartsrv_httpd: /usr/sbin/apachectl: line 119: 16087 Segmentation fault      $HTTPD $OPTIONS -k $ARGV
May 14 13:11:19 srv6 systemd: httpd.service: control process exited, code=exited status=139
May 14 13:11:19 srv6 systemd: Unit httpd.service entered failed state.
May 14 13:11:19 srv6 systemd: httpd.service failed.

**Comment by AnoopAlias** [comment]
Do you see this issue in CloudLinux or CentOS?

Because I just came across a similar issue and it was caused by updates from the cloudlinux package

```
# grep ea-apache24-mod_remoteip-2.4.33-5.el7 /var/log/yum.log
Apr 23 20:37:25 Updated: 1:ea-apache24-mod_remoteip-2.4.33-5.el7.cloudlinux.x86_64
May 04 01:18:24 Updated: 1:ea-apache24-mod_remoteip-2.4.33-5.el7.cloudlinux.1.x86_64
May 14 17:57:26 Updated: 1:ea-apache24-mod_remoteip-2.4.33-5.el7.cloudlinux.4.x86_64
```
Just FYI , engintron would be simply adding configuration for the module. the actual apache module bianry is compiled and provided by cPanel or CloudLinux

**Comment by bdtech** [comment]
Correct CloudLinux. I did see the engintron script had a function so typically it works as intended but didn't dive too deep. There could be a compatibility issue there.

[2018-05-14 11:55:53 -0400] [/usr/local/cpanel/scripts/rpmup] ---> Package ea-apache24-mod_remoteip.x86_64 1:2.4.33-5.el7.cloudlinux.1 will be updated

[2018-05-14 11:55:53 -0400] [/usr/local/cpanel/scripts/rpmup] ---> Package ea-apache24-mod_remoteip.x86_64 1:2.4.33-5.el7.cloudlinux.4 will be an update

**Comment by AnoopAlias** [comment]
@bdtech -- I have had a similar issue reported on a server using the .4 exact package. This server does not run engintron but another nginx plugin. Since all the third party plugins reply on mod_remote_ip the issue, unfortunately, will affect all. Unless CL provides a timely patch. I am in touch with CL support at the moment and will update here if I get any updates from them.

**Comment by bdtech** [comment]
Same here. I've provided CL support info to debug as well.

**Comment by AnoopAlias** [comment]
seems like they are aware of the issue

	
Alex Zavhorodnii (CloudLinux)

May 14, 21:01 EEST

Hello, thank you for your report, we are already aware about this, fixed packages is ready and should be available in our repos within one hour.

**Comment by bdtech** [comment]
Bug appears to be fixed. I am closing this at not Engintron related but may help others.

May 14 14:07:16 Updated: 1:ea-apache24-mod_remoteip-2.4.33-5.el7.cloudlinux.5.x86_64
