### ISSUE TITLE
Purge particular files from nginx cache

### ISSUE THREAD

**Issue by kuteninja** [engintron/engintron#843]
It would be nice to have a way to refresh the cache for a particular file, without having to clear the entire cache.

For example: 
- You open somesite.com/scripts.js, it gets cached
- You change the file scripts.js but you don't want to clear the entire cache for the website
- You then open somesite.com/scripts.js with the header refresh-cache=1 (or some other header)
- The cache should be bypassed using proxy_cache_bypass so it's refreshed but it should **not** be disabled by proxy_no_cache (currently they both happen simultaneously when $CACHE_BYPASS_FOR_X is set)

It could be a good idea to only allow this method for localhost (127.0.0.1) or the server's local IP addresses, so that it can be done automatically by scripts, but not manually by random folks, but I'd consider this a v2.0

**Comment by gmariani** [comment]
Yeah i was just working on a small project today and had to disable nginx because it kept sending an old cached version even if i did a hard refresh in the browser.

**Comment by fevangelou** [comment]
See the wiki please. Either use cache busting or bypass static file caching for that domain only in custom rules.

**Comment by kuteninja** [comment]
I always wonder if you use your software with any website, to see why the issues I report to you are useful.

We ARE using file caching, the issue is that nginx caches files close to forever, and many customers need to change A file on their website. There's no point in clearing/purging the entire cache when you only changed a SINGLE file. 

Cloudflare have the skill to do this, most cache plugins on Wordpress and some other scripts allow a way to clear a single file / route on their internal cache... and you reply to me "read the wiki". That's not very helpful.

**Comment by fevangelou** [comment]
> I always wonder if you use your software with any website, to see why the issues I report to you are useful.

Google my name to see who I am and what work I do beyond Engintron smart-ass...

Nginx's "static cache" refers to a 1 minute caching for static files from Apache to Nginx. In other words, Nginx copies the file from Apache and serves it directly for up to 1 minute. This is "server-side" caching performed from Nginx.

Your issue is different though. You say "nginx caches files close to forever" which is not true. Nginx simply sends long cache-control headers (up to 60 days for some filetypes). In other words, it's the user's browser that caches the file and NOT Nginx. Nginx instructs the browser to do that because that's the right thing to do performance wise. So you either use cache busting to trick browsers OR tell your customers that when they edit files, they should either refresh a page with Ctrl/Cmd + Shift + R or simply disable caching in the browser though the browser's dev tools.

The above apply to CloudFlare and any other CDN as well. Plugins that you reference issue an API request to CloudFlare. But what if you're not using CloudFlare.

Of course what I wrote above is already in the wiki, but hey, who has time for boring stuff, right?

**Comment by kuteninja** [comment]
I opened the wiki, lookup "cache" and nothing is related to my issue, you should be more precise when you're going the RTFM way.

I've checked the source config files and it's setup at 1m indeed so perhaps there's something wrong on my setup which causes files not be deleted, if you had said that before it would have been clearer.
