### ISSUE TITLE
Using PHP-FPM within Nginx

### ISSUE THREAD

**Issue by Nexxed** [engintron/engintron#856]
Hello, I've developed a browser check that sits in front of a website using Nginx as a reverse proxy.
Within cPanel, the option to use a PHP-FPM socket is simply not there. I've tried contacting cPanel themselves to see how to get a socket created so I can use it within the vHost configuration on Engintron to serve these browser check files but to only being told that it's not their issue and that I should contact the Engintron support team (even though it is their issue as there's no available socket for the root user to use)

Any ideas? I'm also willing to share this browser check with you to help protect against Layer 7 DDoS Attacks, it works pretty well on my test server.

**Comment by fevangelou** [comment]
PHP-FPM does use sockets in cPanel but the paths are of this form: /opt/cpanel/ea-phpXX/root/usr/var/run/php-fpm/b750726ae933b2761da6ce49a41f693d84fc8d23.sock

I assume "b750726ae933b2761da6ce49a41f693d84fc8d23" is a hash of the domain name or username - I assume the domain because the PHP-FPM pool file is referenced by domain name, e.g. /opt/cpanel/ea-phpXX/root/pool.d/domain.tld.conf

However, since the socket file is referenced in /opt/cpanel/ea-phpXX/root/pool.d/domain.tld.conf you can simply get these files, grep the socket and build you Nginx vhosts. It's a little overkill for me though - if you wanna go there, you can just use a barebones solution, not necessarily cPanel...

Alternatively, try https://github.com/AnoopAlias/XtendWeb by @AnoopAlias - I believe it does exactly what you want.
