### ISSUE TITLE
phpBB login issues

### ISSUE THREAD

**Issue by C20NE** [engintron/engintron#857]
Hello,

I'm having trouble with a phpbb when users login or are logged in the forum sometimes they appear as another user.

I've disabled the microcaching and I'm still facing this problem.

**Comment by C20NE** [comment]
> GMTtx commented 18 hours ago • 
> I am having the same problem with vBulletin. I thought it was another caching tool but it turned out to be nginx. When I disable nginx the problem stops. The problem happens randomly and was difficult to isolate to nginx.

For me was a bit easy. It just started after installing the plugin.

I found some forum topics about people editing the session.php, I've done that and still facing the problem.

Lets hope someone has a good idea about this.

**Comment by Friends4U** [comment]
I had this problem too, the microcache was the solution.

Custom rules:

if ($SITE_URI ~* "domain.com") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
}

**Comment by C20NE** [comment]
> Friends4U commented 17 hours ago
> I had this problem too, the microcache was the solution.
> 
> Custom rules:
> 
> if ($SITE_URI ~* "domain.com") {
> set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
> }

I did this to disable it:

`location @backend {`
`    include proxy_params_common;`
`    # === MICRO CACHING ===`
`    # Comment the following line to disable 1 second micro-caching for dynamic HTML content`
`    #include proxy_params_dynamic;`
`}`

And still had problems with users

**Comment by predator95** [comment]
a solution for this problem?

**Comment by fevangelou** [comment]
@C20NE You're doing it wrong. Do as @Friends4U said in your "custom rules" file and make sure to replace "domain.com" with the correct domain name.

@predator95 Unfortunately both phpBB and vBulletin use session cookies for everyone, even guests, so micro-caching cannot work out of the box (aka without using a plugin or additional code in each forum app) because it's impossible for Nginx to distinguish between logged in and non-logged in users in order to shut off its caching. Your best solution is to simply bypass micro-caching as @Friends4U mentioned above for the domain or forum path. See the wiki for more info as well as the comments in the "custom rules" file.

**Comment by C20NE** [comment]
Hello.

It worked. Thanks.

**Comment by fevangelou** [comment]
Closing as resolved.
