### ISSUE TITLE
AutoSSL update / Apache restart collision 

### ISSUE THREAD

**Issue by jhawkins002** [engintron/engintron#878]
I almost hesitate to call this a bug... its just something that happens and I thought it appropriate to report. 

During our nightly AutoSSL updates we have noticed that occasionally the last 1/3 or so of domains will fail DCV validation due to the connection being blocked. After investigating typical culprits (firewall, modsecurity, etc.) we discovered that the timestamps for the blocks match a restart timestamp for apache/nginx.

Here's what we believe happens. AutoSSL begins its nightly update and starts installing certificates. Engintron sees the updated SSL configs for the initial domains, updates its data, and then restarts Apache/Nginx to apply the changes. During the few seconds (milliseconds?) that the domains are offline during this restart cycle, AutoSSL can no longer validate the DCV files on the remaining domains in its queue and thus logs a 'connection refused' error. 

Like I said, I think it's difficult to really call this an Engintron bug, and I frankly have no clue how one would work around the issue. Maybe polling get_autossl_pending_queue via the cPanel API? However, I think that would only get you the domains that have already succeeded the DCV check and are awaiting SSL provision. 

Anyway, we hope this report is helpful in some fashion and feel free to promptly close if you deem appropriate.

**Comment by fevangelou** [comment]
Can you can try modifying the portions of the code that restart the services and instead "reload" them? This should be faster for sure, but you also need to test that by "reload" Nginx actually "sees" the new certificates (cause in my checks it had failed - that's why I configured the process to restart the services). Alternatively, you can adjust a longer interval in the https_vhosts.sh file in /etc/nginx/utilities/ - simply change `INTERVAL="15"` to INTERVAL="30"` or more but not beyond a minute.

**Comment by jhawkins002** [comment]
@fevangelou Thank you for the note! Yes, our tests confirm yours - an actual restart is typically needed so that NGINX sees the new/updated certificate data. 

We have already increased the interval directive to address an earlier issue - so that option is not available.

This is probably not a huge issue, given that over consecutive nightly AutoSSL runs the domain(s) in question almost always get picked up. Its just an interesting quirk!
