### ISSUE TITLE
EasyApache 4 (EA4) support in Engintron (coming soon)

### ISSUE THREAD

**Issue by highacid** [engintron/engintron#88]
root@panel [/]# bash engintron.sh install
EasyApache3 is not available when EasyApache4 is in effect.

***************************************************

 ENGINTRON ERROR:
 This server has EasyApache version 4 (beta)
 installed and Engintron is currently only compatible
 with EasyApache version 3 only!
 EasyApache version 4 will be supported
 in Engintron version 1.6.

 --- Installation aborted ---

***************************************************

root@panel [/]#

**Comment by fevangelou** [comment]
If cPanel doesn't fix their bug with EasyApache 4 within the next 2-3 
weeks, I'll issue version 1.7 to address that by building Nginx from source.

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by JPerkster** [comment]
Hi!
Sorry for commenting on a closed post, but I wanted to let you know we're sprinting this case right now, and should have a fix within the next week or two our publicly. Sorry for the delay!

**Comment by fevangelou** [comment]
Awesomazing Jacob! Engintron has gotten huge traction the past few weeks
from large hosting companies & even from the great folks at Nginx.

Can I use the email address you had given me for a couple more things I've
noticed overall? They are not bugs in cPanel or anything, but things that
with your (official) support could help further improve the process of
setting up Engintron to the benefit of the platform obviously (e.g. missing
httpd-devel or limited API calls to retrieve system IPs etc.).

Thanks for taking the time to respond back :)

Much appreciated!

F.

**Comment by JPerkster** [comment]
Hi, sorry for the delay, yes, please feel free to send me that info over!

As an additional note, we've gotten this webserver conflict removed from our latest MASTER branches:

`Dependencies Resolved

====================================================================================================================================================================
 Package                                            Arch                             Version                                   Repository                      Size
====================================================================================================================================================================
Installing:
 nginx                                              x86_64                           1.0.15-12.el6                             epel                           404 k
Installing for dependencies:
 GeoIP                                              x86_64                           1.6.5-1.el6                               epel                           113 k
 GeoIP-GeoLite-data                                 noarch                           2015.12-1.el6                             epel                           363 k
 GeoIP-GeoLite-data-extra                           noarch                           2015.12-1.el6                             epel                            23 M
 geoipupdate                                        x86_64                           2.2.1-2.el6                               epel                            28 k
 nginx-filesystem                                   noarch                           1.0.15-12.el6                             epel                           8.1 k

Transaction Summary
====================================================================================================================================================================
Install       6 Package(s)

Total download size: 24 M
Installed size: 49 M
Is this ok [y/N]:`

If you want to test this out before it goes public, set this in your EA4.repo file (changing ARCH / OS where appropriate):
baseurl=http://ea4testing.cpanel.net/CentOS/6/EA4/x86_64/

This will pull from our ea4testing public repo, which we use for testing packages publicly before sending them out. I've synced it this morning to our MASTER branches, and you can test the latest there right now.

Thanks!

**Comment by fevangelou** [comment]
Thank you, I'll test it out within the weekend.

When are you pushing this update on official channels?

**Comment by JPerkster** [comment]
We've gotten really good with consistent updates that happen the same day as our EA3 releases. PHP just dropped an update this week, so we're getting our sources updated, and we usually have these releases out mid-day the following Tuesday. I'm hoping to have this update out for both EA3 & EA4 on the 8th of March.

**Comment by fevangelou** [comment]
Great! The w/e will be more than enough then for testing.

Thanks again :)

**Comment by JPerkster** [comment]
Good morning,

We've released fixes for the webserver conflict in our EA release yesterday. You should be able to do a $(yum install nginx) now with EA4. Please let me know if you come across any other problems.

Thanks!

**Comment by JPerkster** [comment]
Also, we're looking at adding pre/post hooks for the ea3_to_ea4 migration script that will allow Plugin developers such as yourself to have your plugin upgraded during the migration to EA4. Is this something you might find useful? If so, would you mind reaching out and emailing me? I'd like to get you in touch with the Product Owner who's looking at adding those so we can ensure our customers have a great experience during the EasyApache migration.

Thanks again!

**Comment by iStampa** [comment]
Does this mean that running engintron on ea4 has been fixed?

**Comment by fevangelou** [comment]
There is currently a check which stops installation if Engintron detects
EA4. You can either remove this check manually or wait until next week for
an update.

I still need to test EA4 & Engintron.

**Comment by iStampa** [comment]
I don't know much about server so it's  probably smarter to wait. 

Thank you for creating this. Very promising.

**Comment by fevangelou** [comment]
You're welcome :)

I'll update this post again in a couple of days when I finish my tests.

**Comment by jackiellowery** [comment]
just checking in on this issue.  i'd love to be able to update to EA4, PHP7, and Nginx.  thanks!

**Comment by fevangelou** [comment]
I'm looking to launch v1.7.0 by the weekend, so EA4 support will be in 
if my tests conclude positively :)

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by highacid** [comment]
Any changes?

**Comment by burnsyboo** [comment]
No changes yet ? )-:

**Comment by BomBom123** [comment]
Any updates?

**Comment by fevangelou** [comment]
Sorry for the delay folks. Just today I got 2 dev licenses from cPanel, so I'll finish testing within the week.

If you wanna assist in any way, you can do so by removing the EasyApache check on engintron.sh at line 429. So essentially change this line:

    GET_EA3_VERSION=$(/scripts/easyapache --version | grep "Easy Apache v3")

to this

    GET_EA3_VERSION=1

This will trick Engintron to proceed with the installation without check for EasyApache version.

Since there are essentially no installer changes that would affect Engintron's installation when EA4 is present, by removing this check you can install Engintron on your cPanel server with EA4 enabled.

I will be testing EA4 on CentOS 6 & 7, so if you can contribute your own tests, I would greatly appreciate so - especially if you can try this on CloudLinux too.

**Comment by BomBom123** [comment]
Not currently using EA4 but if i convert any time soon then i'll run some tests.

**Comment by highacid** [comment]
I am running cloudlinux, will do the tests tonight and inform you

**Comment by highacid** [comment]
I tried without Cloudlinux on centos 7 with changing the code as you directed. This is what I got:

https://gist.github.com/highacid/ade83fe73cfbfe77a6aaddbdc79a3d51

**Comment by highacid** [comment]
It worked fine after removing nginx.repo and recreating it.

**Comment by fevangelou** [comment]
@highacid Thank you for your installation log :) Upon re-installation/update Nginx will be setup again, so I doubt this was a problem. However I did spot that mod_remoteip was not properly re-installed, as it seems the "apxs" tool required for building Apache modules has changed path in EA4 (it's under /etc/ now and not under /usr/local/). I will add EA version checks to resolve this.

**Comment by highacid** [comment]
Any ETA for next release?

**Comment by escherlat** [comment]
@fevangelou You need to install the ea-apache24-devel package to have the proper version of apxs for EA4. That RPM installs apxs into /usr/bin. If you are finding it in /etc that's probably a bug.

**Comment by johnknock** [comment]
@fevangelou Roadmap looks amazing, how far are we away from another release?  Also, when do you think you will be including the optimisations you mention in your roadmap timewise?

Thanks.

**Comment by fevangelou** [comment]
@escherlat You're the man Kenneth. Thanks once more. I'll implement the update for v1.7.0 coming up next week with EA4 support :)

@johnknock Next week it's v1.7.0 with EA4 support, Nginx mainline & stable releases (present in 1.6.x dev right now - it's what you install already) and some other goodies. The roadmap is open, meaning it's a set of ideas to implement in future releases. This can change at any time with new additions or subtractions. In any case, I'll do my best to implement most in a timely manner. What's important is stability for sure and ease of use. I don't want to break these 2 simple rules.

**Comment by masteranalyze** [comment]
Is good that  we sorted this,and this will be in engintron 1.7,anyhow in last whm update,witch is the current version 56,EA4 is still in beta,and will remain like that until whm cpanel v58,when it will become default,and as they want to become,i guess on that time EasyApache 4 will be out of beta.

I think we should concentrate to add the features from roadmap,basically optmization first ,and things that depends on 3rd party,later on,as they become possible,or when they are complectly out of beta,else it can still be troubles.

I certainly agree with @fevangelou that this should be stable first of all,and second of all,easy to use,but in order to be able to be easy to use,i think optimization should go first and things that depend on 3rd party as soon as possible or when they become available,so we can get to ver2.0,to be easy usable like in the plan of the roadmap.

**Comment by highacid** [comment]
Any news about 1.7 ETA release?

**Comment by laurfx** [comment]
Up!

Please release it for EA4!

**Comment by masteranalyze** [comment]
@fevangelou you can release 1.7 for the boys for EA4,with the mention to leave this open,until ea4 becomes default in cpanel and out of beta,actually Cool Zero and Spider Pigs teams are working on fixing things out on EA4 but until september at least i don`t think EA4 will be out of beta even if it`s working good and only PECL /PERL problem remains to be solved,as it`s still in beta,all kinds of things or error might happen,so everybody if any problems after the release,post them here,in order to be solved.

@fevangelou did the guys from joomla merged your p.r,in order in joomla 3.6 to work out of the box engintron with joomla 3.6? And did you gaved them also the code for /administrator part?

We should concentrate on gui and things that are actually not in beta,and can be done,in order to get to 2.0.

**Comment by fevangelou** [comment]
Hey guys. An update on EA4 support for Engintron. I had to put development on hold for a while but I've done my work already on EA4 for CentOS 6 and what's left is tweaking and testing for EA4 on CentOS 7.

I'll do my best to push v1.7.0 within the month.

As you may have noticed, smaller incremental updates that are stable are always pushed live. And as you can see for example, Nginx stable & mainline are already supported if you just upgrade to the latest 1.6.1 build.

I'm also testing LetsEncrypt at the same time so I can sort the SSL proxying as well by v1.8.0. This will make a huge difference as you can understand, as all web traffic will be passing through Nginx - not to mention the zero cost for having SSL certificates :)

So development is progressing, albeit a little slower, but the new features are coming.

**Comment by laurfx** [comment]
That it will be awesome!

Btw, Engintron works on EA4 if you installed when you had EA3 but you can't update it.

**Comment by masteranalyze** [comment]
Hey @fevangelou in 1.7 any guis implementation from the planned list?Did the guys from joomla included your code,so it can work out of the box with joomla 3.6 ?!

We should concentrate on Engintron to work out of box with Joomla,WP,Magento,Open Cart,Presta Shop,Piwik,Owncloud,Vtiger crm and any other software.

On the side of let`s encrypt,what did you decide for v.1.8 to use cpanel plugin done by team Cobra,or handle it the things from Engintron?

By the way from version 1.9.5 in nginx  we have http2 :https://www.nginx.com/blog/nginx-1-9-5/ ,this is working right now out of the box with engintron or needs mods activated?
As http2 is an major improvement,can see from this image: https://blog.cloudflare.com/content/images/2015/12/image_1.png ,only 1 tcp conection instead of 3.

**Comment by fevangelou** [comment]
@masteranalyze As you may have already read in the other issue we both commented on, I think LetsEncrypt will not be difficult to integrate using EFFs Certbot client for LetsEncrypt. And as for Joomla, yes, they accepted my patch so Joomla v3.6+ will be able to have separate caching rules like WordPress, for even better performance. As for the other CMSs you mention, I'd love it if any users of these CMSs contribute back their knowledge so we can integrate additional caching options for them as well.

**Comment by masteranalyze** [comment]
+1 for the joomla integration,did you sended them the pr for administration too,and will work out of the box with 3.6+ and further ?As that will be great news...

Let`s encrypt will certainly be an very nice feature,i will comment back about this on that issue.

Between 1.7 to 1.8 it will be nice if we can have some of the gui that are available.

**Comment by virtuali1151** [comment]
The latest install is not working after make the change to allow it to bypass the easy4 check.  It completes the install, but no nginx.

nginx: unrecognized service.

**Comment by fevangelou** [comment]
@virtuali1151 Engintron is not yet EA4 compatible.

**Comment by virtuali1151** [comment]
Does it still do the check even if EA4 is not the one enabled? I have it installed, but 3 is the active one in Cpanel WHM.

**Comment by masteranalyze** [comment]
hey guys maybe you can give an hand of help to fev if you have Centos 7,as he said : "what's left is tweaking and testing for EA4 on CentOS 7."

@fevangelou please let know the guys what you needs in terms of testing or tweaks,folks on centos 7 will help and we save some time,and afterwards you can release the 1.7 in order to solve this problem.

Btw all should know,that EA4 is still in beta by cpanel,not by engintron,ea4 will be out of beta when whm/cpanel release v58,so even engintron is released with 1.7 working on EA4,until Ea4 is stable and out of beta,report here the problems if any.

**Comment by highacid** [comment]
Any ETA for 1.7?

**Comment by marcelodelta** [comment]
waiting anxiously.

**Comment by bakkus** [comment]
I suppose they're waiting for EA4 to go out of beta status, which cPanel/WHM says will happen with the release of their v58: https://blog.cpanel.com/big-changes-in-cpanel-whm-version-58/

**Comment by masteranalyze** [comment]
@highacid i suppose you have cl 7 or centos 7 on your side?

@fevangelou if that is the case ,tell what test needs to run,on it,maybe highacid can do those tests to save some time,and you can concentrate after the release on the 1.8 with let`s encrypt and we have an double release more sooner.

Yes ea4 is still in beta,they still can be problems,once released 1.7 with support for ea4,post here if any problems.Most likely whm/cpanel 58 will come around September.

**Comment by highacid** [comment]
@masteranalyze Yes I am on centos 7, correct. I agree that a beta release should be in place and tested with current running cpanel version.

**Comment by masteranalyze** [comment]
@fevangelou tell to @highacid what test should he run or what do you need to save time for 1.7 release.

Most likely next week,whm v58 with ea4 as default and stable and out of beta,will be the current release,seems they done it more faster this time,but i don`t know if they integrated on it everything they said like sub-account and let`s encrypt,we will soon find out.

**Comment by colinmcdermott** [comment]
Just tried to install - looking forward to EA4 support!

**Comment by Josephvb10** [comment]
Any updates? @fevangelou

**Comment by highacid** [comment]
Failed at step EXEC spawning /etc/init.d/nginx: No such file or directory

**Comment by highacid** [comment]
Cpanel 58 RC is out there, it's a pitty that no release from engintron yet.

**Comment by Josephvb10** [comment]
What I think is wrong is that the Engintron developer bugged the CPanel development team a lot to fix the issue that prevented EA4 compatibility. They fixed, and now the developer of Engintron doesn't do anything. While I understand that we all have our own situations and this is a free project, the developer provided multiple release dates that failed to follow. Engintron is a great project, but at least an update like "I'm working on it" or "Sorry guys, i'm having problems implementing X thing" would be appreciated.

**Comment by jcmdln** [comment]
@Josephvb10 
> What I think is wrong is that the Engintron developer bugged the CPanel development team a lot to fix the issue that prevented EA4 compatibility. They fixed, and now the developer of Engintron doesn't do anything. While I understand that we all have our own situations and this is a free project, the developer provided multiple release dates that failed to follow. Engintron is a great project, but at least an update like "I'm working on it" or "Sorry guys, i'm having problems implementing X thing" would be appreciated.
How very understanding of you. Where are your commits to resolve this issue? How much have you donated to have this issue resolved? Be as upset as you want but as you stated, this is a free project. He's not been contracted by cPanel to have a specific release date. They could have ignored his requests of compatibility if they wanted, as they had no obligation to him.

There's no need for this sort of vitriolic drivel, either wait for change or be the change.

**Comment by fevangelou** [comment]
From my understanding, EA4 is still in beta: https://confluence2.cpanel.net/display/EA4/Current+Status+of+EasyApache+4

By the way, the bug that cPanel fixed was preventing a generic installation of Nginx from its official repos. This would probably prevent other webservers or proxies to be installed as well. So it was a bug fixed, they didn't do anyone a favour. I was just the first to have noticed it.

Engintron is actively developed and 100% stable. If you wish to risk your hosting offer by including a beta feature (EA4), be my guest.

**Comment by virtuali1151** [comment]
Just putting in my 2c's.. thanks for all your work on this Fotis.. truly an awesome job... tks mate:)

**Comment by JPerkster** [comment]
Hi,

That page is a bit outdated, my apologies. We're getting it updated now. EA4 is officially stable as of v58, and it's now the default stack in v58 systems.

I hope this helps!

**Comment by fevangelou** [comment]
@JPerkster Thanks for the heads up Jacob. :)

**Comment by coldplug** [comment]
Hi, I think that people are impatient because you said, on March 17, quoting you: "I'm looking to launch v1.7.0 by the weekend". So, people expected release in few days, and now there are 4 months from that statment. If you didn't stated that prediction probably noone would post such complaints. As always, keep great work!

**Comment by highacid** [comment]
@coldplug I am waiting for the launch since February 🎯

**Comment by drgang21** [comment]
When will the 1.7 be available?

**Comment by fevangelou** [comment]
Be patient.

**Comment by revcomllc** [comment]
We would love to see 1.7 released as soon as possible as well. We too are using EasyApache4 and are getting the check errors upon installation and are stuck.

**Comment by genesteinberg** [comment]
No late beta?

Peace,
Gene

**Comment by genesteinberg** [comment]
Time's a wastin'

From cPanel:

ssuming the rollout to EDGE and CURRENT goes well, this is the version we're hoping to roll out to RELEASE next week. 

benny Vasquez
cpanel.com
@cpaneldev

On Jul 28, 2016, at 7:38 PM, edge-users@cpanel.net wrote:

The EDGE tier has been updated to 11.58.0.11.

The 58 change log has been updated: https://documentation.cpanel.net/display/CL/58+Change+Log
It is also included at the end of this mail.

Regards,
The cPanel & WHM Release Team

**Comment by fevangelou** [comment]
@genesteinberg It's my top priority if you be so kind and wait a while.

**Comment by genesteinberg** [comment]
I don't intend to rush you and force you to release a buggy product. I expect lots of users will be pressuring you now that v 58 has entered the RELEASE branch. Best of luck.

Peace,
Gene

**Comment by TheMongooseBytes** [comment]
@fevangelou 

What to do in the mean time ? disable engintron or is there a beta solution I can try ?

**Comment by genesteinberg** [comment]
Do you have a beta solution?

**Comment by TheMongooseBytes** [comment]
@genesteinberg No I haven't I had hoped that Fotis would have one for all of us.

**Comment by TheMongooseBytes** [comment]
@fevangelou  Fotis, where can I find the engintron.sh file on our cpanel server ?

**Comment by highacid** [comment]
There are changed that can be done to install it also on EA4.

**Comment by highacid** [comment]
I just gave up, and since I would like to make use of varnish i moved to apache booster. The promise was to release some new version since January :)

**Comment by TheMongooseBytes** [comment]
@highacid What exactly are you saying ? I gave up on engintron ???

**Comment by laurfx** [comment]
@highacid , how the Apache booster performs?

**Comment by TheMongooseBytes** [comment]
@highacid on what price plan are you with Apache Booster and did it require you to uninstall Engintron ?

**Comment by fevangelou** [comment]
First off, no-one forces you to upgrade to EasyApache4. All the servers 
we manage use EA3 on cPanel 58 with Engintron.

Secondly, if I recall properly, @highacid <https://github.com/highacid> 
's server is so (badly) modified, he might as well try ApacheBooster 
(good luck with that). BTW, Engintron 1.5 (the new re-written code base) 
was released in Feb 2016, so it's kinda hard I promised v1.7.0 in January...

Be smart and be patient.

---

Regards,

Fotis Evangelou

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by laurfx** [comment]
@fevangelou we will wait the release of you awesome plugin.

I don't think you need to provide Let's Encrypt SSL's because CPanel added this at AutoSSL https://features.cpanel.net/topic/provide-support-for-lets-encrypt-automated-certificate-management-ssl

Thank you !

**Comment by TheMongooseBytes** [comment]
@fevangelou you wrote: 

> First off, no-one forces you to upgrade to EasyApache4. All the servers
we manage use EA3 on cPanel 58 with Engintron.

That might be true but our webstore is  hungry for PHP 7 and that is why we upgraded to EA4

**Comment by fevangelou** [comment]
I doubt the combination of Apache & PHP7 can surpass Nginx + Apache + 
PHP 5.5/5.6. Sorry.

---

Regards,

Fotis Evangelou

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by TheMongooseBytes** [comment]
Well I am not saying that Apache 2.4 + PHP 7 beats an good combo of Nginx  + Apache but I want it all

**Comment by highacid** [comment]
@TheMongooseBytes i picked the offer for 5 years with 60 bucks now they increased a bit the pricing. yes they do not allow any nginx installs since they do a check on yum installed nginx packages.

**Comment by highacid** [comment]
@laurfx it performs great, i am monitoring with nginx amplify, pushed the team up upgrade to latest nginx version, now i wait for varnish upgrades. moved nginx in ram and it works as a charm.

**Comment by highacid** [comment]
@fevangelou my server is not at all badly modified the fact that I was in BETA for EA4 for a long time doesn't make it badly configured, I am just an early adopter thats it. And excuse me not January, yet February it was replied from your side, that in one week, then two weeks, how you think this post got so many replies. 

 **_fevangelou commented on Mar 17
I'm looking to launch v1.7.0 by the weekend, so EA4 support will be in
if my tests conclude positively :)_**

**Comment by JPerkster** [comment]
@highacid Thanks for testing out EA4 so early! I've been on it since v52 without any issues at all, it's stable as hell. It's just the migrations that can be a bit painful. It's good to know that you've taken the platform and ran with it. After spending a year building a platform like this, it's good to see positive results :)

We recently released an update in v58.0.20 to the migration script that will allow you to use hooks during the migration from EA3 to EA4. This allows integrators like @fevangelou to ensure any actions for their plugins are kicked off during the migration as well. 

If there's anything that we at cPanel can do to assist, let me know.

**Comment by Keeperjoey** [comment]
How long do you think before there is EA4 support. I would really like to have nginx on my whm58 server but can't get it to work. I can't revert to EA3 because I never had EA3.

**Comment by TheMongooseBytes** [comment]
One thing that puzzles me is that is how Fotis is working many projects at the same time while claiming to be dedicated to work on EA4 support of his Engintron Nginx engine. Is it a question of funds then why not go for a fundraiser ? I am sure many here would like to contribute.

**Comment by highacid** [comment]
@TheMongooseBytes As i said it was promised with his words:
fevangelou commented on Mar 17
I'm looking to launch v1.7.0 by the weekend, so EA4 support will be in
if my tests conclude positively :)

I like people if they really care about a product to do something. Or people just hang in there, soon Cpanel will start working on Standalone Nginx, and hopefully they will also make. a hybrid config. As they said in Features, it should be late 2016 early 2017. I bet there is no full EA4 for engintron till then :). And after all who will need 3rd party plugins with full support from cpanel. IN this way Cpanel gain new market, and we are happy customers that dont need to ask and beg support, people forgot why is BETA releases out there, and a good developer should always make use of it. Hold on fox, 3 months left and I am sure cpanel will have it in Beta Edge release.

**Comment by brianjking** [comment]
@highacid - Check out nDeploy if you want to use EA4 + nginx as a proxy to Apache or skip Apache with PHP-FPM + nginx. 

* http://ndeploy.readthedocs.io/en/latest/
* https://github.com/AnoopAlias/nDeploy

**Comment by fevangelou** [comment]
@highacid Are you still here? You clearly don't understand open source 
either way.

---

Regards,

Fotis Evangelou

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by highacid** [comment]
@fevangelou yes I am. I understand it enough to know that EA4 is in stable release, and not only me, yet many would had expected at least a BETA testing version, or something.

@brianjking I am fine thanks, I bought worth 60$ a license for 5 years with ApacheBooster. Pushed them to do all updates to latest versions, and now waiting for varnish 4 upgrades. And yes so with developers listening to customers or future customers is the way to go. Improvement and moreover voice of the people always is developers guidance. As I mentioned Cpanel will release a new version with support for Nginx, then no one will need to use tools as nDeploy, nginxCP, engintron or any other 3rd party nginx related stack. I tested them all. Engintron was the winner I do not disagree, up until the EA4 where it got stuck. I used it also so, then having some issues with HTTPS and some sites, I moved to ApacheBooster.

**Comment by fevangelou** [comment]
Engintron v1.7.0 is now released.

Please post any bug reports related to EA4 and Engintron v1.7.0 here: https://github.com/engintron/engintron/issues/235

**Comment by fevangelou** [comment]
An update to those following this issue:

So far there have been no problems reported regarding Engintron and EA4 integration.

If you wanna stay in touch with future announcements, you should probably sign up in the Engintron mailing list/newsletter: https://tinyletter.com/engintron

**Comment by masteranalyze** [comment]
@highacid you could it donate those money to help the developing of engintron if your wanting things so faster.

Fotis,could been said from 1990 that he will release engintron with support for ea4,but on that date EA4 it was still in beta,so if you have an 3rd plugin working for EA4 ,that plugin is too maximum beta,and you can have all kinds of beta,beta are not at all for production,not even cpanel does not recomand to use it on production,on the date you mention EA4 was beta,if your an early adopter that is it,but it`s totally unproffesionally to offer to your hosted clients something that is marked at beta,and more then that your putting your clients at risk by using softwares that must be used only in developing purposes and testing.

Secondly as engintron depends on cpanel,you can see that after Jacob from cpanel,realesed what was need it for EA4 in 12 august,right after 5 days,on 17 august,Fotis did manage to lunch engintron with ea4 compatibility and after that,what is most important,there was no problem,else if he would lunch beta,and your server crashed and all your clients hosted in your server were down,would you been more gratefully?I don`t think so.

@highacid about the cpanel releasing the nginx,when they will do that,it won`t be an good solution,only maybe if your starting an new server from scratch,as nginx will be standalone ,no more .htaccess,no more reverse proxy on nginx,practically you will have to configure all stuff again,your my guest to go into that route.

Engintron is the only good implementation of nginx,as it does leverage the power of both world: APACHE+Nginx,and it was builded because in the market there was no other alternatives,Fotis first implemented the best varnish configuration for joomla,then he started this,as varnish also haves limitations,varnish does not know HTTPS,nginx knows https,and soon you will have engintron 1.8 with support of https and ssl.

For the guy in here who said that Fotis bogged Cpanel,please try to understand things,Fotis just notice something that was not working from cpanel side,and reported this,and they corected the problem,is absolutely normally,and i contacted them also regarding this,and what is the problem with that?!

Like someone very good said in this post : WAIT FOR THE CHANGE OR BE THE CHANGE!

Help the developer,instead of complaining that you want,contribute,and help,complaining does not help anyone,it`s only for kids and womans,real mans needs to do it and act,not to complain,that is of course if your man and not an woman or child.

So people enjoy now Engintron with EA4 but take notice of some things that might be very importantly for you:

-When going from Ea3 to Ea4 ,that does not mean ,all your php.ini files will be migrated,you will have to configure all things ,as ea4 is stable,but on migration side is not yet so ready
-Ea4 does not have fast cgi ,only su ,phpfm is coming in v60,that will be suitable if you have less users into your servers,but as i heared here people with over 1000 thousand accounts,that won`t help them,and fast cgi will be on ea4 on cpanel v62,so q1 2017 ,
-if you did not know this,and you need fastcgi and if your cpanel/whm v.58 ,you can`t revert back to Ea3 so you can use fastcgi,so you will have to wait
-phpfpm is not the same with fastcgi,and mostly both are needed based on your setup and number of accounts.
-Ea3 with php 5.6 is more fast then Ea4 with su php witch is the curently handler in EA4.
-in production always but always use only software marked as : STABLE ,else your not puting at risk only your business,but others business as well.
