### ISSUE TITLE
NGINX stopped serve static files

### ISSUE THREAD

**Issue by andreuka** [engintron/engintron#881]
After some point nginx stopped to serve static files directly and start to send them all to Apache, which created huge load to my server.

Im not expert in NGINX configuration files, so I`m interested where should I start learn from to understand why it became like that?

I didnt changed any configuration.

**Comment by ImLuke954** [comment]
I am having the same problem. Nginx no longer caches static files in the server side after updating to the latest version of engintron.

**Comment by texohost** [comment]
I too am seeing this - static files all being served by Apache.

**Comment by fevangelou** [comment]
Can you point me to some example URLs please? And how did you verify?

**Comment by andreuka** [comment]
Hi there, I dont think any url can help with this, because response headers from the server showing NGINX.

But when I `tail -f` apache access.log, I see every file are going to that log, like png, jpg, css, mp4, etc...

As I can understand this mean all static files are sending to apache from nginx, instead of sending php files only.

Thanks!

**Comment by texohost** [comment]
Viewing apache status in WHM I can see jpg, css etc files being served by Apache.
Am I interpreting this incorrectly?
![screen shot 2018-07-20 at 15 12 31](https://user-images.githubusercontent.com/8641488/43004298-9f67e798-8c2f-11e8-87d7-f7654d331d14.png)

**Comment by texohost** [comment]
Here is a sample URL: projectarian.com

**Comment by ImLuke954** [comment]
Any fix to this?

**Comment by ImLuke954** [comment]
Has anybody found a solution?

**Comment by fevangelou** [comment]
This is not a bug. Nginx passes over requests for static files to Apache. Apache responds with the files and Nginx caches them internally for up to 1 minute. For the next 1 minute, all requests to the previously cached static assets will be directly served by Nginx and not Apache.

This 1 min cache is enough to allow Nginx to serve files directly for most site visitors, while at the same time not causing issues to the site owners/developers who may be doing live changes in CSS or JS files.

As for WHY Nginx does not serve files directly, bypassing Apache, well, it's impossible for Nginx to know each site's root (so it knows from the URL requested WHERE to look for the actual files on disk) without fetching definition files from cPanel. This in turn is a costly operation, especially when Nginx vhosts could change every few seconds on busy cPanel servers with hundreds of domains hosted. Keep in mind that there is only 1 vhost for HTTP traffic and 1 vhosts for each HTTPS entry in Apache. Even if you have hundreds of domains, Engintron processes only 1 file (Apache's config).

To be able to serve static files directly, Engintron would have to traverse directories with thousands of files possibly near constantly on busy hosts.

That's why the 1 min cache for static files is both simple and effective.

Final notes: Carefully read the "curl -I" response of a URL and you'll see that the 2nd time you call a static URL, Nginx responds with HIT for "X-Nginx-Cache-Status". This means the file was served from Nginx's cache, not from Apache.

**Comment by ImLuke954** [comment]
I have set 10 min static cache. 
curl -I of a static file never returns the "X-Nginx-Cache-Status" header.
sample url : https://www.cricmatez.com/wp-content/uploads/2016/12/Cricmatez-Logo-site.png

**Comment by texohost** [comment]
I did exactly the same: 10 minute status cache. I also never see that header:

curl -I https://bizmag.co.za/wp-content/uploads/2018/07/PR-Release-Feature-Image--218x150.jpg

HTTP/2 200 
server: nginx
date: Fri, 17 Aug 2018 15:51:48 GMT
content-type: image/jpeg
content-length: 8889
last-modified: Mon, 09 Jul 2018 12:09:07 GMT
expires: Tue, 16 Oct 2018 15:51:48 GMT
cache-control: max-age=5184000
pragma: public
accept-ranges: bytes

**Comment by ImLuke954** [comment]
This issue should be reopened.

**Comment by fevangelou** [comment]
Guys, caching works as the header "cache-control" is already modified by Nginx. You don't see the "HIT" status because for some reason newest Nginx versions have stopped showing that flag for static assets (at least the way Engintron configures Nginx). I'll resolve the display of the flag, however like I said, actual caching works already. Simply change a file (e.g. a CSS file) and you'll see that it's not updated unless a minute passes (tops) or you re-request the file using cache-busting (random query in the file name URL).
