### ISSUE TITLE
Customize a definition block for a domain in default_https.conf?

### ISSUE THREAD

**Issue by standaniel** [engintron/engintron#901]
We need to be able to add to a server domain name in default_https.conf some customization for specific domains only like:

server {
.....
    ssl_client_certificate /ssl/location/here/ssl.pem;
    ssl_verify_client optional;
    ssl_verify_depth 1;
    include common_https.conf;
    if ($ssl_client_verify != SUCCESS) {
    return 403;
}
}

We can do that but the file gets written back when the scripts/cron runs.
How can we do that or can we do this?

Thanks.

**Comment by ChristianGabs** [comment]
Silly question and can't see your point. First Cpanel will generate all data as domain, subdomains etc will be placed win WHM.

To do custom options you must avoid default_https.conf to be changed by you as manual.

My advice do not try to add new stuff you don't have any knowledge on how it's working.

About can you do this, yes you can do :

1) Go to nginx.conf (/etc/nginx/nginx.conf)
Have a look on the last line 

    ## Virtual Host Configs ##
    include /etc/nginx/conf.d/*.conf;

In our case, all file which contains ".conf" will be loaded.

Create on /etc/nginx/conf.d/YOURDOMAIN.conf (Ex: /etc/nginx/conf.d/domain.com.conf)
Add in this file all settings you looking for and done.

Good, you finish with Nginx, BTW you not done yet :D

Because you passing true proxy you have to repeat steps but this time (/etc/apache2/conf.d)

Make sure your system supports conf file.

GL&HF

**Comment by fevangelou** [comment]
Or just use "custom rules". A .conf file will be deleted when Engintron is updated.

**Comment by josephcrowell** [comment]
Server blocks can't go in to "custom rules" and if statements are bad

**Comment by fevangelou** [comment]
If "if" statements were that bad, they wouldn't exist, now, would they? And sure server blocks can't be included in other server blocks. If you do that, it means you probably don't know what you want to do...

It all depends on the use case.
