### ISSUE TITLE
Instalation nginx 404

### ISSUE THREAD

**Issue by cheetos22** [engintron/engintron#907]
Hi, when i try to clean install engintron i have 404 error from nginx repository.

Log:

> Total download size: 758 k
> Installed size: 2.7 M
> Downloading packages:
> nginx-1.15.2-1.el7_4.ngx.x86_6 FAILED
> http://nginx.org/packages/centos/7/x86_64/RPMS/nginx-1.15.2-1.el7_4.ngx.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found                           ]  0.0 B/s |    0 B  --:--:-- ETA
> Trying other mirror.
> To address this issue please refer to the below knowledge base article
> 
> https://access.redhat.com/articles/1320623
> 
> If above article doesn't help to resolve this issue please open a ticket with CloudLinux Support.
> 
> 
> 
> Error downloading packages:
>   1:nginx-1.15.2-1.el7_4.ngx.x86_64: [Errno 256] No more mirrors to try.
> 
> error reading information on service nginx: No such file or directory

I use cloudlinux os
In repository http://nginx.org/packages/centos/7/x86_64/RPMS/ i don't see version nginx-1.15.2-1.el7_4.ngx.x86_64.rpm

Regards

**Comment by mhos** [comment]
Wow its now October and the latest installer 1.9.1 is still trying to install a package that does not exist in the repo.
This has just broken our server completely. Had to reach out to cpanel support to have the server fixed due to broken install.

cPanel 74.08
CentOS 7.5
Engintron 1.9.1 installer
Downloading packages:
No Presto metadata available for nginx
nginx-1.15.4-1.el7_4.ngx.x86_6 FAILED
http://nginx.org/packages/centos/7/x86_64/RPMS/nginx-1.15.4-1.el7_4.ngx.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found         ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
To address this issue please refer to the below wiki article

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.



Error downloading packages:
  1:nginx-1.15.4-1.el7_4.ngx.x86_64: [Errno 256] No more mirrors to try.

error reading information on service nginx: No such file or directory

**Comment by fevangelou** [comment]
The installer uses the official Nginx repo. It's not a bug nor can I control it somehow.

In any case, you can simply locate and directly install the RPM for your server OS version, e.g. http://nginx.org/packages/mainline/centos/7/x86_64/RPMS/nginx-1.15.5-1.el7_4.ngx.x86_64.rpm

Better still, switch to the "mainline" repo in Engintron.

**Comment by fevangelou** [comment]
@cheetos22 Yes, that's because v1.14.x is still the stable one. If you want 1.15.x switch to the mainline repo.

Read the Engintron and Nginx wikis folks before nagging.
