### ISSUE TITLE
engintron only installs version 1.14 of nginx

### ISSUE THREAD

**Issue by laracroftonline** [engintron/engintron#908]
i want to have nginx mainline version 1.15.x installed but it keeps installing 1.14

**Comment by ChristianGabs** [comment]
Lara,

It's not about Engintron, the main issue on you is your DISTRIBUTION or let say Version of your Linux.
If you have Centos 6 you will not get 1.15.x because nginx will not release for your version.

Looking on how Engintron install it :

 cat > "/etc/yum.repos.d/nginx.repo" <<EOFM
[nginx]
name=nginx repo
baseurl=http://nginx.org/packages/mainline/centos/$RELEASE_VERSION/\$basearch/
gpgcheck=0
enabled=1
EOFM


When Mainline version it's request to be installed Engintron will add to your repo automatic.

Because now your version will be (CENTOS 6) and 1.15.x is not set for that distribution you will not get that version.

**Comment by fevangelou** [comment]
Considering resolved.
