### ISSUE TITLE
URL Rewriting is broken when using UTF-8

### ISSUE THREAD

**Issue by avikostan** [engintron/engintron#951]
Hello,

Once I enable Engintron on my VPS, when trying to access a URL that has Hebrew characters on the URL for example : 
https://www.buissnes.cards/%D7%A9-%D7%9E-%D7%A7%D7%95%D7%A1%D7%98%D7%94-%D7%91%D7%A0%D7%99%D7%99%D7%94

I'm getting Error .... can someone please point me how can I solve this problem, seems like I need to unable utf8 support for URL Rewriting .

**Comment by fevangelou** [comment]
I'm not aware of something like that. Doesn't make sense really.

What I can only guess is that Nginx decodes the URL but Apache has trouble passing the URL data then back to Joomla.

I'm more than 10 years in the Joomla community and since my native language is Greek, I'm aware of any possible language related incompatibilities or issues and I can tell you for sure that neither Nginx nor Apache (to my knowledge) either have issues with UTF-8 characters on URLs.

Check your .htaccess file perhaps for any weird rules (also feel free to share it here if you want). Or, if you use some SEF/SEO extension, disable it temporarily as the issue may be spotted there.

I honestly can't think of anything else.
