### ISSUE TITLE
Content not showing on some mobile providers

### ISSUE THREAD

**Issue by strahinjanis** [engintron/engintron#996]
Hi friends,
we have a customer with cPanel Solo & Engitron, so after switching from naked Apache the site nativemedia.rs like the pulling from the partner network increased performances dramatically. Now, the bad news is the customer reported the issue, that on mobile devices, on some mobile (cellular) providers, the ad content doesn't show at all, instead the blank content, e.g.
http://recepti-i-zabava.live/?p=745 (the 6 pics. widget)
switching to wi-fi, the same phone, browser.... everything works fine.
I've tried to comment out the mobile section (dynamic), but still the same.
Any ideas?
Thanks!
Stan

**Comment by strahinjanis** [comment]
Addendum,
the problem persist with Chrome/Android devices, I've commented out the:
    # Comment the following line to disable 1 second micro-caching for dynamic HTML content
    #include proxy_params_dynamic;
but still the same, again, it works perfectly well on all desktop platforms.
Thanks,
Stan

**Comment by fevangelou** [comment]
If Engintron didn't work, then there would be no site at all. But the issue is specific to ads and a certain cellular network(s)/operator(s) as you say.

That's because some mobile operators inject JS code and/or cutoff or proxy content for performance reasons. Vodafone was known to do that a few years back, more seem to do so still. See for example: https://stackoverflow.com/questions/4113268/stop-mobile-network-proxy-from-injecting-javascript

Verify by using a mobile connection on a different cellular network.

As you can see in the link above, there are various solutions to the issue, the easiest being switching to HTTPS.
